/* Generated by Yosys 0.18+10 (git sha1 b6be8bb62, gcc 11.1.0-1ubuntu1~20.04 -fPIC -Os) */

module primitive_example_design_5(in, ibuf2_en, rst, clk, ibuf1_en, ibuf3_en, ibuf4_en, ibuf5_en, obuft_ds_en1, obuft_ds_en2, obuft_ds_en3, iddr_en, q_p, q_n);
  input clk;
  input ibuf1_en;
  input ibuf2_en;
  input ibuf3_en;
  input ibuf4_en;
  input ibuf5_en;
  input [2:0] iddr_en;
  input [2:0] in;
  input obuft_ds_en1;
  input obuft_ds_en2;
  input obuft_ds_en3;
  output [2:0] q_n;
  output [2:0] q_p;
  input rst;
  (* unused_bits = "0" *)
  wire _0_;
  (* unused_bits = "0" *)
  wire _1_;
  (* unused_bits = "0" *)
  wire _2_;
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_5.v:18.50-18.61" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  wire [2:0] dffre_out;
  (* src = "./rtl/primitive_example_design_5.v:15.16-15.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  wire ibuf4_en;
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  wire [2:0] iddr_en;
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  wire [2:0] iddr_out;
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  wire [2:0] in;
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  wire obuft_ds_en1;
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  wire obuft_ds_en2;
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  wire obuft_ds_en3;
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  wire [2:0] q_n;
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  wire [2:0] q_p;
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  wire rst_i_buf_out;
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:18.11-18.63" *)
  I_BUF clk_buf_inst (
    .EN(ibuf1_en),
    .I(clk),
    .O(clk_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:33.11-33.97" *)
  DFFRE ff_inst1 (
    .C(clk_buf_out),
    .D(iddr_out[0]),
    .E(1'h1),
    .Q(dffre_out[0]),
    .R(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:34.11-34.97" *)
  DFFRE ff_inst2 (
    .C(clk_buf_out),
    .D(iddr_out[1]),
    .E(1'h1),
    .Q(dffre_out[1]),
    .R(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:35.11-35.97" *)
  DFFRE ff_inst3 (
    .C(clk_buf_out),
    .D(iddr_out[2]),
    .E(1'h1),
    .Q(dffre_out[2]),
    .R(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:28.11-28.64" *)
  I_BUF ibuf_inst1 (
    .EN(ibuf2_en),
    .I(in[0]),
    .O(i_buf_out[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:29.11-29.64" *)
  I_BUF ibuf_inst2 (
    .EN(ibuf3_en),
    .I(in[1]),
    .O(i_buf_out[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:30.11-30.64" *)
  I_BUF ibuf_inst3 (
    .EN(ibuf4_en),
    .I(in[2]),
    .O(i_buf_out[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:31.11-31.63" *)
  I_BUF ibuf_inst4 (
    .EN(ibuf5_en),
    .I(rst),
    .O(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:20.11-20.94" *)
  I_DDR iddr_ist1 (
    .C(clk_buf_out),
    .D(i_buf_out[0]),
    .E(iddr_en[0]),
    .Q({ _2_, iddr_out[0] }),
    .R(rst)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:21.11-21.94" *)
  I_DDR iddr_ist2 (
    .C(clk_buf_out),
    .D(i_buf_out[1]),
    .E(iddr_en[1]),
    .Q({ _1_, iddr_out[1] }),
    .R(rst)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:22.11-22.94" *)
  I_DDR iddr_ist3 (
    .C(clk_buf_out),
    .D(i_buf_out[2]),
    .E(iddr_en[2]),
    .Q({ _0_, iddr_out[2] }),
    .R(rst)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:24.15-24.89" *)
  O_BUFT_DS o_buft_inst1 (
    .I(dffre_out[0]),
    .O_N(q_p[0]),
    .O_P(q_p[0]),
    .T(obuft_ds_en1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:25.15-25.89" *)
  O_BUFT_DS o_buft_inst2 (
    .I(dffre_out[1]),
    .O_N(q_p[1]),
    .O_P(q_p[1]),
    .T(obuft_ds_en2)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:26.15-26.89" *)
  O_BUFT_DS o_buft_inst3 (
    .I(dffre_out[2]),
    .O_N(q_p[2]),
    .O_P(q_p[2]),
    .T(obuft_ds_en3)
  );
  assign q_n = 3'hx;
endmodule
