/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module fabric_primitive_example_design_6(oddr_out, dffre_out, rst_i_buf_out, clk_buf_out);
  input clk_buf_out;
  output dffre_out;
  input oddr_out;
  input rst_i_buf_out;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap404$iopadmap$primitive_example_design_6.ibuf_oe4.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap404$iopadmap$primitive_example_design_6.ibuf_oe4.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap404$iopadmap$primitive_example_design_6.ibuf_oe4.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap405$iopadmap$primitive_example_design_6.q_n.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap405$iopadmap$primitive_example_design_6.q_n.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap405$iopadmap$primitive_example_design_6.q_n.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap406$iopadmap$primitive_example_design_6.ibuf_oe3.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap406$iopadmap$primitive_example_design_6.ibuf_oe3.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap406$iopadmap$primitive_example_design_6.ibuf_oe3.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap407$iopadmap$primitive_example_design_6.ibuf_oe1.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap407$iopadmap$primitive_example_design_6.ibuf_oe1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap407$iopadmap$primitive_example_design_6.ibuf_oe1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap403$iopadmap$primitive_example_design_6.q_p.C ;
  (* src = "./rtl/primitive_example_design_6.v:15.46-15.57" *)
  (* src = "./rtl/primitive_example_design_6.v:15.46-15.57" *)
  wire clk_buf_out;
  wire dffre_out;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap400$auto$clkbufmap.cc:262:execute$398.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap402$iopadmap$primitive_example_design_6.oddr_en.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap402$iopadmap$primitive_example_design_6.oddr_en.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap402$iopadmap$primitive_example_design_6.oddr_en.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap401$iopadmap$primitive_example_design_6.ibuf_oe2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap401$iopadmap$primitive_example_design_6.ibuf_oe2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap401$iopadmap$primitive_example_design_6.ibuf_oe2.EN ;
  wire oddr_out;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap403$iopadmap$primitive_example_design_6.q_p.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap403$iopadmap$primitive_example_design_6.q_p.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap400$auto$clkbufmap.cc:262:execute$398.O ;
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  wire rst_i_buf_out;
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_6.v:25.7-25.87" *)
  DFFRE ff_inst1 (
    .C(clk_buf_out),
    .D(oddr_out),
    .E(1'h1),
    .Q(dffre_out),
    .R(rst_i_buf_out)
  );
endmodule
