/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_6(oddr_out, dffre_out, rst_i_buf_out);
  input oddr_out;
  output dffre_out;
  input rst_i_buf_out;
  wire oddr_out;
  wire dffre_out;
  (* src = "./rtl/primitive_example_design_6.v:15.46-15.57" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  wire rst_i_buf_out;
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_6.v:25.7-25.87" *)
  DFFRE ff_inst1 (
    .C(clk_buf_out),
    .D(oddr_out),
    .E(1'h1),
    .Q(dffre_out),
    .R(rst_i_buf_out)
  );
endmodule
