/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_6(clk, in, rst, q_p, q_n, oddr_en, ibuf_oe1, ibuf_oe2, ibuf_oe3, ibuf_oe4);
  input ibuf_oe3;
  input ibuf_oe4;
  input [1:0] in;
  output q_p;
  input rst;
  input ibuf_oe1;
  output q_n;
  input clk;
  input ibuf_oe2;
  input oddr_en;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$auto$clkbufmap.cc:263:execute$399 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe1 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe2 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe3 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe4 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$oddr_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p ;
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.rst_i_buf_out ;
  (* src = "./rtl/primitive_example_design_6.v:4.12-4.15" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.rst ;
  (* src = "./rtl/primitive_example_design_6.v:4.7-4.10" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.clk ;
  (* src = "./rtl/primitive_example_design_6.v:12.12-12.21" *)
  wire [1:0] \$auto$rs_design_edit.cc:682:execute$409.i_buf_out ;
  (* src = "./rtl/primitive_example_design_6.v:5.16-5.24" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe2 ;
  (* src = "./rtl/primitive_example_design_6.v:7.8-7.11" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.q_p ;
  wire \$auto$rs_design_edit.cc:682:execute$409.dffre_out ;
  (* src = "./rtl/primitive_example_design_6.v:8.8-8.11" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.q_n ;
  wire \$auto$rs_design_edit.cc:682:execute$409.oddr_out ;
  (* src = "./rtl/primitive_example_design_6.v:6.7-6.14" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.oddr_en ;
  (* src = "./rtl/primitive_example_design_6.v:15.46-15.57" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.clk_buf_out ;
  (* src = "./rtl/primitive_example_design_6.v:5.25-5.33" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe3 ;
  (* src = "./rtl/primitive_example_design_6.v:3.13-3.15" *)
  wire [1:0] \$auto$rs_design_edit.cc:682:execute$409.in ;
  (* src = "./rtl/primitive_example_design_6.v:5.7-5.15" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe1 ;
  (* src = "./rtl/primitive_example_design_6.v:5.34-5.42" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe4 ;
  wire dffre_out;
  (* src = "./rtl/primitive_example_design_6.v:5.25-5.33" *)
  (* src = "./rtl/primitive_example_design_6.v:5.25-5.33" *)
  wire ibuf_oe3;
  (* src = "./rtl/primitive_example_design_6.v:15.46-15.57" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_6.v:12.12-12.21" *)
  wire [1:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_6.v:5.34-5.42" *)
  (* src = "./rtl/primitive_example_design_6.v:5.34-5.42" *)
  wire ibuf_oe4;
  (* src = "./rtl/primitive_example_design_6.v:3.13-3.15" *)
  (* src = "./rtl/primitive_example_design_6.v:3.13-3.15" *)
  wire [1:0] in;
  wire oddr_out;
  (* src = "./rtl/primitive_example_design_6.v:7.8-7.11" *)
  (* src = "./rtl/primitive_example_design_6.v:7.8-7.11" *)
  wire q_p;
  (* src = "./rtl/primitive_example_design_6.v:4.12-4.15" *)
  (* src = "./rtl/primitive_example_design_6.v:4.12-4.15" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_6.v:5.7-5.15" *)
  (* src = "./rtl/primitive_example_design_6.v:5.7-5.15" *)
  wire ibuf_oe1;
  (* src = "./rtl/primitive_example_design_6.v:8.8-8.11" *)
  (* src = "./rtl/primitive_example_design_6.v:8.8-8.11" *)
  wire q_n;
  (* src = "./rtl/primitive_example_design_6.v:4.7-4.10" *)
  (* src = "./rtl/primitive_example_design_6.v:4.7-4.10" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_6.v:5.16-5.24" *)
  (* src = "./rtl/primitive_example_design_6.v:5.16-5.24" *)
  wire ibuf_oe2;
  (* src = "./rtl/primitive_example_design_6.v:6.7-6.14" *)
  (* src = "./rtl/primitive_example_design_6.v:6.7-6.14" *)
  wire oddr_en;
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  wire rst_i_buf_out;
  wire \$iopadmap$q_p ;
  wire \$iopadmap$q_n ;
  wire \$iopadmap$oddr_en ;
  wire \$iopadmap$ibuf_oe4 ;
  wire \$iopadmap$ibuf_oe3 ;
  wire \$iopadmap$ibuf_oe2 ;
  wire \$iopadmap$ibuf_oe1 ;
  wire \$auto$clkbufmap.cc:263:execute$399 ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_6.ibuf_oe1  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf_oe1 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe1 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_6.ibuf_oe2  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf_oe2 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe2 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_6.ibuf_oe3  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf_oe3 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe3 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_6.ibuf_oe4  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf_oe4 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe4 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_6.oddr_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.oddr_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$oddr_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_6.q_n  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n ),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_n )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_6.q_p  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p ),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_p )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:15.7-15.59" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.clk_buf_inst  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe1 ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$auto$clkbufmap.cc:263:execute$399 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:19.11-19.69" *)
  O_BUFT_DS \$auto$rs_design_edit.cc:682:execute$409.o_buft_inst1  (
    .I(\$auto$rs_design_edit.cc:682:execute$409.in [0]),
    .O_N(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n ),
    .O_P(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p ),
    .T(\$auto$rs_design_edit.cc:682:execute$409.dffre_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:21.7-21.60" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.ibuf_inst1  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe2 ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.in [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.i_buf_out [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:22.7-22.60" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.ibuf_inst2  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe3 ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.in [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.i_buf_out [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:23.7-23.59" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.ibuf_inst4  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf_oe4 ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.rst ),
    .O(\$auto$rs_design_edit.cc:682:execute$409.rst_i_buf_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:17.7-17.81" *)
  O_DDR \$auto$rs_design_edit.cc:682:execute$409.iddr_ist1  (
    .C(\$auto$rs_design_edit.cc:682:execute$409.clk_buf_out ),
    .D(\$auto$rs_design_edit.cc:682:execute$409.i_buf_out ),
    .E(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$oddr_en ),
    .Q(\$auto$rs_design_edit.cc:682:execute$409.oddr_out ),
    .R(\$auto$rs_design_edit.cc:682:execute$409.rst )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$auto$clkbufmap.cc:262:execute$398  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$auto$clkbufmap.cc:263:execute$399 ),
    .O(\$auto$rs_design_edit.cc:682:execute$409.clk_buf_out )
  );
  fabric_primitive_example_design_6 \$auto$rs_design_edit.cc:680:execute$408  (
    .clk_buf_out(clk_buf_out),
    .dffre_out(dffre_out),
    .oddr_out(oddr_out),
    .rst_i_buf_out(rst_i_buf_out)
  );
  assign \$auto$rs_design_edit.cc:682:execute$409.clk  = clk;
  assign clk_buf_out = \$auto$rs_design_edit.cc:682:execute$409.clk_buf_out ;
  assign \$auto$rs_design_edit.cc:682:execute$409.dffre_out  = dffre_out;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe1  = ibuf_oe1;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe2  = ibuf_oe2;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe3  = ibuf_oe3;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf_oe4  = ibuf_oe4;
  assign \$auto$rs_design_edit.cc:682:execute$409.in  = in;
  assign \$auto$rs_design_edit.cc:682:execute$409.oddr_en  = oddr_en;
  assign oddr_out = \$auto$rs_design_edit.cc:682:execute$409.oddr_out ;
  assign q_n = \$auto$rs_design_edit.cc:682:execute$409.q_n ;
  assign q_p = \$auto$rs_design_edit.cc:682:execute$409.q_p ;
  assign \$auto$rs_design_edit.cc:682:execute$409.rst  = rst;
  assign rst_i_buf_out = \$auto$rs_design_edit.cc:682:execute$409.rst_i_buf_out ;
endmodule
