/* Generated by Yosys 0.44 (git sha1 86a09ee26, g++ 11.2.1 -fPIC -O3) */

module GJC31(data_i, reset_n_buf, enable_buf, clk_i_buf, dly_inc_pulse_inv_buf, data_o_buf);
  input clk_i_buf;
  input data_i;
  output [1:0] data_o_buf;
  input dly_inc_pulse_inv_buf;
  input enable_buf;
  input reset_n_buf;
  wire \$abc$238$auto_53 ;
  wire \$abc$250$li0_li0 ;
  wire \$abc$250$li1_li1 ;
  wire \$abc$250$li2_li2 ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:25.10-25.16" *)
  wire \$f2g_in_en_enable ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:23.10-23.17" *)
  wire \$f2g_trx_dly_adj_dly_adj ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:23.10-23.17" *)
  wire \$f2g_trx_dly_inc_dly_adj ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:22.9-22.15" *)
  wire \$f2g_trx_dly_ld_dly_ld ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:24.10-24.17" *)
  wire \$f2g_trx_reset_n_reset_n ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:28.16-28.22" *)
  wire \$f2g_tx_out_data_o[0] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:28.16-28.22" *)
  wire \$f2g_tx_out_data_o[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:25.10-25.16" *)
  wire \$ofab_enable ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:26.16-26.25" *)
  wire clk_buf_i;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:26.10-26.15" *)
  wire clk_i;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:15.18-15.27" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:15.18-15.27" *)
  wire clk_i_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:26.26-26.33" *)
  wire clk_pll;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:12.18-12.24" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:12.18-12.24" *)
  wire data_i;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:21.10-21.20" *)
  wire data_i_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:21.22-21.40" *)
  wire data_i_buf_delayed;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:28.16-28.22" *)
  wire \data_o[0] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:28.16-28.22" *)
  wire \data_o[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:17.24-17.34" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:17.24-17.34" *)
  wire [1:0] data_o_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:20.16-20.24" *)
  wire \data_reg[0] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:20.16-20.24" *)
  wire \data_reg[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:23.10-23.17" *)
  wire dly_adj;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:27.10-27.27" *)
  wire dly_inc_pulse_inv;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:16.18-16.39" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:16.18-16.39" *)
  wire dly_inc_pulse_inv_buf;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:22.9-22.15" *)
  wire dly_ld;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:25.10-25.16" *)
  wire enable;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:14.18-14.28" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:14.18-14.28" *)
  wire enable_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:24.10-24.17" *)
  wire reset_n;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:13.18-13.29" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:13.18-13.29" *)
  wire reset_n_buf;
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$250$auto_251  (
    .C(clk_i),
    .D(\$abc$250$li0_li0 ),
    .E(\$abc$238$auto_53 ),
    .Q(\data_o[0] ),
    .R(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$250$auto_252  (
    .C(clk_i),
    .D(\$abc$250$li1_li1 ),
    .E(\$abc$238$auto_53 ),
    .Q(\data_o[1] ),
    .R(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$250$auto_253  (
    .C(clk_i),
    .D(\$abc$250$li2_li2 ),
    .E(\$abc$238$auto_53 ),
    .Q(dly_ld),
    .R(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) \$abc$596$auto_597  (
    .A({ \data_reg[1] , reset_n }),
    .Y(\$abc$250$li1_li1 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) \$abc$596$auto_598  (
    .A({ \data_reg[0] , reset_n }),
    .Y(\$abc$250$li0_li0 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'hb)
  ) \$abc$596$auto_599  (
    .A({ reset_n, enable }),
    .Y(\$abc$238$auto_53 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$596$auto_600  (
    .A(dly_inc_pulse_inv),
    .Y(dly_adj)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$596$auto_601  (
    .A(reset_n),
    .Y(\$abc$250$li2_li2 )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_in_en_enable_1  (
    .I(enable),
    .O(\$f2g_in_en_enable )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_dly_adj_dly_adj_1  (
    .I(dly_adj),
    .O(\$f2g_trx_dly_adj_dly_adj )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_dly_inc_dly_adj_1  (
    .I(dly_adj),
    .O(\$f2g_trx_dly_inc_dly_adj )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_dly_ld_dly_ld_1  (
    .I(dly_ld),
    .O(\$f2g_trx_dly_ld_dly_ld )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_reset_n_reset_n_1  (
    .I(reset_n),
    .O(\$f2g_trx_reset_n_reset_n )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_o[0]_1  (
    .I(\data_o[0] ),
    .O(\$f2g_tx_out_data_o[0] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_o[1]_1  (
    .I(\data_o[1] ),
    .O(\$f2g_tx_out_data_o[1] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$ofab_enable_1  (
    .I(enable),
    .O(\$ofab_enable )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:31.39-31.73" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf0_ (
    .EN(1'h1),
    .I(reset_n_buf),
    .O(reset_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:32.39-32.71" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf1_ (
    .EN(1'h1),
    .I(enable_buf),
    .O(enable)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:33.39-33.73" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf2_ (
    .EN(1'h1),
    .I(clk_i_buf),
    .O(clk_buf_i)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:34.39-34.93" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf3_ (
    .EN(1'h1),
    .I(dly_inc_pulse_inv_buf),
    .O(dly_inc_pulse_inv)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:42.60-46.10" *)
  PLL #(
    .DEV_FAMILY("VIRGO"),
    .DIVIDE_CLK_IN_BY_2("FALSE"),
    .PLL_DIV(32'sh00000020),
    .PLL_MULT(32'sh00000064),
    .PLL_MULT_FRAC(32'sh00000000),
    .PLL_POST_DIV(32'sh00000011)
  ) clk_pll_gen (
    .CLK_IN(clk_pll),
    .CLK_OUT(clk_i),
    .PLL_EN(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:40.13-40.45" *)
  CLK_BUF clock_buffer (
    .I(clk_buf_i),
    .O(clk_pll)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:51.11-51.46" *)
  I_BUF data_buf (
    .EN(\$f2g_in_en_enable ),
    .I(data_i),
    .O(data_i_buf)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:58.11-58.76" *)
  I_DDR data_i_ddr (
    .C(clk_i),
    .D(data_i),
    .E(\$ofab_enable ),
    .Q({ \data_reg[1] , \data_reg[0]  }),
    .R(\$f2g_trx_reset_n_reset_n )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:52.13-57.52" *)
  I_DELAY #(
    .DELAY(32'sh00000000)
  ) data_i_delay (
    .CLK_IN(clk_i),
    .DLY_ADJ(\$f2g_trx_dly_adj_dly_adj ),
    .DLY_INCDEC(\$f2g_trx_dly_inc_dly_adj ),
    .DLY_LOAD(\$f2g_trx_dly_ld_dly_ld ),
    .I(data_i_buf),
    .O(data_i_buf_delayed)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:35.11-35.44" *)
  O_BUFT obuf0_ (
    .I(\$f2g_tx_out_data_o[0] ),
    .O(data_o_buf[0]),
    .T(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC31/results_dir/.././rtl/GJC31.v:36.11-36.44" *)
  O_BUFT obuf1_ (
    .I(\$f2g_tx_out_data_o[1] ),
    .O(data_o_buf[1]),
    .T(1'h1)
  );
endmodule
