/* Generated by Yosys 0.44 (git sha1 7a4a3768c, g++ 11.2.1 -fPIC -O3) */

module GJC46_post_synth(reset, enable_n, data_i, bitslip_ctrl_n, clkGHz, data_o, ready);
  input bitslip_ctrl_n;
  input clkGHz;
  input data_i;
  output data_o;
  input enable_n;
  output ready;
  input reset;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97.17-97.42" *)
  wire \$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ;
  wire \$abc$1161$abc$702$li0_li0 ;
  wire \$abc$1161$abc$702$li1_li1 ;
  wire \$abc$1161$abc$702$li2_li2 ;
  wire \$abc$1161$abc$702$li3_li3 ;
  wire \$abc$1161$abc$702$li4_li4 ;
  wire \$abc$1161$abc$702$li5_li5 ;
  wire \$abc$1161$abc$702$li6_li6 ;
  wire \$abc$1161$abc$702$li7_li7 ;
  wire \$abc$1729$new_new_n29__ ;
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.54-89.56" *)
  wire \$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:22.10-22.20" *)
  wire \$f2g_trx_dvalid_enable_buf ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:20.10-20.21" *)
  wire \$f2g_trx_reset_n_reset_buf_n ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:20.10-20.21" *)
  wire \$f2g_trx_reset_n_reset_buf_n_2 ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:38.10-38.27" *)
  wire \$f2g_tx_oe_buf_output_enable ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[0] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[1] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[2] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[3] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[4] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[5] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[6] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[7] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[8] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \$f2g_tx_out_data_i_serdes_reg[9] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:33.10-33.19" *)
  wire \$f2g_tx_out_ready_buf ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:38.10-38.27" *)
  wire \$ifab_buf_output_enable ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:31.10-31.22" *)
  wire \$ifab_data_i_valid ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:34.10-34.25" *)
  wire \$ifab_serdes_dpa_lock ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:36.10-36.22" *)
  wire \$ofab_bitslip_ctrl ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:22.10-22.20" *)
  wire \$ofab_enable_buf ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:22.10-22.20" *)
  wire \$ofab_enable_buf_2 ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:36.10-36.22" *)
  wire bitslip_ctrl;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:13.18-13.32" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:13.18-13.32" *)
  wire bitslip_ctrl_n;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:35.10-35.28" *)
  wire bitslip_ctrl_n_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:38.10-38.27" *)
  wire buf_output_enable;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:14.18-14.24" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:14.18-14.24" *)
  wire clkGHz;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:37.10-37.20" *)
  wire clkGHz_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:26.10-26.23" *)
  wire clkGHz_clkbuf;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:12.18-12.24" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:12.18-12.24" *)
  wire data_i;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:23.10-23.20" *)
  wire data_i_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:24.10-24.22" *)
  wire data_i_delay;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[0] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[2] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[3] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[4] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[5] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[6] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[7] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[8] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:29.26-29.39" *)
  wire \data_i_serdes[9] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[0] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[1] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[2] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[3] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[4] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[5] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[6] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[7] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[8] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:30.25-30.42" *)
  wire \data_i_serdes_reg[9] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:31.10-31.22" *)
  wire data_i_valid;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:15.18-15.24" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:15.18-15.24" *)
  wire data_o;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:39.10-39.18" *)
  wire delay_in;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:39.10-39.18" *)
  wire delay_in_;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:40.10-40.19" *)
  wire delay_out;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:22.10-22.20" *)
  wire enable_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:21.10-21.22" *)
  wire enable_buf_n;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:11.18-11.26" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:11.18-11.26" *)
  wire enable_n;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:28.10-28.24" *)
  wire fabric_clk_div;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:27.10-27.17" *)
  wire pll_clk;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:16.17-16.22" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:16.17-16.22" *)
  wire ready;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:33.10-33.19" *)
  wire ready_buf;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:10.18-10.23" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:10.18-10.23" *)
  wire reset;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:19.10-19.19" *)
  wire reset_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:20.10-20.21" *)
  wire reset_buf_n;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:34.10-34.25" *)
  wire serdes_dpa_lock;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[0] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[1] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[2] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[3] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[4] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[5] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[6] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:32.15-32.23" *)
  wire \wait_pll[7] ;
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:37.38-37.69" *)
  LUT6 #(
    .INIT_VALUE(64'h8000000000000000)
  ) \$abc$1729$auto_1730  (
    .A({ \wait_pll[2] , \wait_pll[1] , \wait_pll[0] , \wait_pll[5] , \wait_pll[4] , \wait_pll[3]  }),
    .Y(\$abc$1729$new_new_n29__ )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h78)
  ) \$abc$1729$auto_1731  (
    .A({ \wait_pll[7] , \$abc$1729$new_new_n29__ , \wait_pll[6]  }),
    .Y(\$abc$1161$abc$702$li7_li7 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h6)
  ) \$abc$1729$auto_1732  (
    .A({ \$abc$1729$new_new_n29__ , \wait_pll[6]  }),
    .Y(\$abc$1161$abc$702$li6_li6 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:37.38-37.69" *)
  LUT6 #(
    .INIT_VALUE(64'h7fffffff80000000)
  ) \$abc$1729$auto_1733  (
    .A({ \wait_pll[5] , \wait_pll[2] , \wait_pll[1] , \wait_pll[0] , \wait_pll[4] , \wait_pll[3]  }),
    .Y(\$abc$1161$abc$702$li5_li5 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:33.38-33.69" *)
  LUT5 #(
    .INIT_VALUE(32'h7fff8000)
  ) \$abc$1729$auto_1734  (
    .A({ \wait_pll[4] , \wait_pll[2] , \wait_pll[1] , \wait_pll[0] , \wait_pll[3]  }),
    .Y(\$abc$1161$abc$702$li4_li4 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:29.38-29.69" *)
  LUT4 #(
    .INIT_VALUE(16'h7f80)
  ) \$abc$1729$auto_1735  (
    .A({ \wait_pll[3] , \wait_pll[2] , \wait_pll[1] , \wait_pll[0]  }),
    .Y(\$abc$1161$abc$702$li3_li3 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h78)
  ) \$abc$1729$auto_1736  (
    .A({ \wait_pll[2] , \wait_pll[1] , \wait_pll[0]  }),
    .Y(\$abc$1161$abc$702$li2_li2 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h6)
  ) \$abc$1729$auto_1737  (
    .A({ \wait_pll[1] , \wait_pll[0]  }),
    .Y(\$abc$1161$abc$702$li1_li1 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:33.38-33.69" *)
  LUT5 #(
    .INIT_VALUE(32'h80000000)
  ) \$abc$1729$auto_1738  (
    .A({ \$abc$1729$new_new_n29__ , data_i_valid, serdes_dpa_lock, \wait_pll[7] , \wait_pll[6]  }),
    .Y(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:29.38-29.69" *)
  LUT4 #(
    .INIT_VALUE(16'h8000)
  ) \$abc$1729$auto_1739  (
    .A({ \$abc$1729$new_new_n29__ , serdes_dpa_lock, \wait_pll[7] , \wait_pll[6]  }),
    .Y(ready_buf)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h7f)
  ) \$abc$1729$auto_1740  (
    .A({ \$abc$1729$new_new_n29__ , \wait_pll[7] , \wait_pll[6]  }),
    .Y(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$1729$auto_1741  (
    .A(bitslip_ctrl_n_buf),
    .Y(bitslip_ctrl)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$1729$auto_1742  (
    .A(enable_buf_n),
    .Y(enable_buf)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$1729$auto_1743  (
    .A(\wait_pll[0] ),
    .Y(\$abc$1161$abc$702$li0_li0 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$1729$auto_1744  (
    .A(reset_buf),
    .Y(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_667  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[0] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[0] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_668  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[1] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[1] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_669  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[2] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[2] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_670  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[3] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[3] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_671  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[4] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[4] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_672  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[5] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[5] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_673  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[6] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[6] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_674  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[7] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[7] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_675  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[8] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[8] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$666$auto_676  (
    .C(fabric_clk_div),
    .D(\data_i_serdes[9] ),
    .E(\$abc$1161$abc$489$logic_and$/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:97$12_Y ),
    .Q(\data_i_serdes_reg[9] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_703  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li0_li0 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[0] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_704  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li1_li1 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[1] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_705  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li2_li2 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[2] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_706  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li3_li3 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[3] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_707  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li4_li4 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[4] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_708  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li5_li5 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[5] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_709  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li6_li6 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[6] ),
    .R(reset_buf_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89.11-89.66" *)
  DFFRE \$abc$702$auto_710  (
    .C(clkGHz_clkbuf),
    .D(\$abc$1161$abc$702$li7_li7 ),
    .E(\$abc$1729$techmap$techmap1312$abc$702$auto_709.$logic_not$/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:89$1262_Y ),
    .Q(\wait_pll[7] ),
    .R(reset_buf_n)
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_dvalid_enable_buf_1  (
    .I(enable_buf),
    .O(\$f2g_trx_dvalid_enable_buf )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_reset_n_reset_buf_n_1  (
    .I(reset_buf_n),
    .O(\$f2g_trx_reset_n_reset_buf_n )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_reset_n_reset_buf_n_3  (
    .I(reset_buf_n),
    .O(\$f2g_trx_reset_n_reset_buf_n_2 )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_oe_buf_output_enable_1  (
    .I(buf_output_enable),
    .O(\$f2g_tx_oe_buf_output_enable )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[0]_1  (
    .I(\data_i_serdes_reg[0] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[0] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[1]_1  (
    .I(\data_i_serdes_reg[1] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[1] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[2]_1  (
    .I(\data_i_serdes_reg[2] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[2] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[3]_1  (
    .I(\data_i_serdes_reg[3] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[3] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[4]_1  (
    .I(\data_i_serdes_reg[4] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[4] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[5]_1  (
    .I(\data_i_serdes_reg[5] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[5] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[6]_1  (
    .I(\data_i_serdes_reg[6] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[6] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[7]_1  (
    .I(\data_i_serdes_reg[7] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[7] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[8]_1  (
    .I(\data_i_serdes_reg[8] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[8] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_i_serdes_reg[9]_1  (
    .I(\data_i_serdes_reg[9] ),
    .O(\$f2g_tx_out_data_i_serdes_reg[9] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_ready_buf_1  (
    .I(ready_buf),
    .O(\$f2g_tx_out_ready_buf )
  );
  (* keep = 32'sh00000001 *)
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$ibuf$GJC46.$ibuf_bitslip_ctrl_n  (
    .EN(1'h1),
    .I(bitslip_ctrl_n),
    .O(bitslip_ctrl_n_buf)
  );
  (* keep = 32'sh00000001 *)
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$ibuf$GJC46.$ibuf_clkGHz  (
    .EN(1'h1),
    .I(clkGHz),
    .O(clkGHz_buf)
  );
  (* keep = 32'sh00000001 *)
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$ibuf$GJC46.$ibuf_data_i  (
    .EN(1'h1),
    .I(data_i),
    .O(data_i_buf)
  );
  (* keep = 32'sh00000001 *)
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$ibuf$GJC46.$ibuf_enable_n  (
    .EN(1'h1),
    .I(enable_n),
    .O(enable_buf_n)
  );
  (* keep = 32'sh00000001 *)
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$ibuf$GJC46.$ibuf_reset  (
    .EN(1'h1),
    .I(reset),
    .O(reset_buf)
  );
  (* keep = 32'sh00000001 *)
  I_FAB \$ifab_buf_output_enable_1  (
    .I(\$ifab_buf_output_enable ),
    .O(buf_output_enable)
  );
  (* keep = 32'sh00000001 *)
  I_FAB \$ifab_data_i_valid_1  (
    .I(\$ifab_data_i_valid ),
    .O(data_i_valid)
  );
  (* keep = 32'sh00000001 *)
  I_FAB \$ifab_serdes_dpa_lock_1  (
    .I(\$ifab_serdes_dpa_lock ),
    .O(serdes_dpa_lock)
  );
  (* keep = 32'sh00000001 *)
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$obuf$GJC46.$obuf_ready  (
    .I(\$f2g_tx_out_ready_buf ),
    .O(ready),
    .T(1'h1)
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$ofab_bitslip_ctrl_1  (
    .I(bitslip_ctrl),
    .O(\$ofab_bitslip_ctrl )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$ofab_enable_buf_1  (
    .I(enable_buf),
    .O(\$ofab_enable_buf )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$ofab_enable_buf_3  (
    .I(enable_buf),
    .O(\$ofab_enable_buf_2 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:61.58-65.6" *)
  PLL #(
    .DEV_FAMILY("VIRGO"),
    .DIVIDE_CLK_IN_BY_2("FALSE"),
    .PLL_DIV(32'sh00000001),
    .PLL_MULT(32'sh00000032),
    .PLL_MULT_FRAC(32'sh00000000),
    .PLL_POST_DIV(32'sh00000011)
  ) clk_pll_gen0 (
    .CLK_IN(clkGHz_clkbuf),
    .FAST_CLK(pll_clk),
    .PLL_EN(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:56.13-56.53" *)
  CLK_BUF clock_buffer (
    .I(clkGHz_buf),
    .O(clkGHz_clkbuf)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:134.12-138.6" *)
  O_BUFT counter_o_buft (
    .I(delay_out),
    .O(data_o),
    .T(\$f2g_tx_oe_buf_output_enable )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:125.7-132.6" *)
  O_DELAY #(
    .DELAY(32'sh00000000)
  ) counter_o_delay (
    .CLK_IN(clkGHz_clkbuf),
    .DLY_ADJ(1'h0),
    .DLY_INCDEC(1'h0),
    .DLY_LOAD(1'h0),
    .I(delay_in),
    .O(delay_out)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:111.7-121.6" *)
  O_SERDES #(
    .DATA_RATE("SDR"),
    .WIDTH(32'sh0000000a)
  ) counter_o_serdes (
    .CLK_IN(clkGHz_clkbuf),
    .D({ \$f2g_tx_out_data_i_serdes_reg[9] , \$f2g_tx_out_data_i_serdes_reg[8] , \$f2g_tx_out_data_i_serdes_reg[7] , \$f2g_tx_out_data_i_serdes_reg[6] , \$f2g_tx_out_data_i_serdes_reg[5] , \$f2g_tx_out_data_i_serdes_reg[4] , \$f2g_tx_out_data_i_serdes_reg[3] , \$f2g_tx_out_data_i_serdes_reg[2] , \$f2g_tx_out_data_i_serdes_reg[1] , \$f2g_tx_out_data_i_serdes_reg[0]  }),
    .DATA_VALID(\$f2g_trx_dvalid_enable_buf ),
    .OE_IN(\$ofab_enable_buf_2 ),
    .OE_OUT(\$ifab_buf_output_enable ),
    .PLL_CLK(pll_clk),
    .PLL_LOCK(1'h1),
    .Q(delay_in_),
    .RST(\$f2g_trx_reset_n_reset_buf_n_2 )
  );
  (* keep = 32'sh00000001 *)
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_12_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$ibuf$GJC46.$delay_in  (
    .EN(1'h1),
    .I(delay_in_),
    .O(delay_in)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:67.13-74.6" *)
  I_DELAY #(
    .DELAY(32'sh00000000)
  ) input_data_delay (
    .CLK_IN(clkGHz_clkbuf),
    .DLY_ADJ(1'h0),
    .DLY_INCDEC(1'h0),
    .DLY_LOAD(1'h0),
    .I(data_i_buf),
    .O(data_i_delay)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC46/results_dir/.././rtl/GJC46.v:80.7-92.6" *)
  I_SERDES #(
    .DATA_RATE("SDR"),
    .DPA_MODE("DPA"),
    .WIDTH(32'sh0000000a)
  ) input_data_serdes (
    .BITSLIP_ADJ(\$ofab_bitslip_ctrl ),
    .CLK_IN(clkGHz_clkbuf),
    .CLK_OUT(fabric_clk_div),
    .D(data_i_delay),
    .DATA_VALID(\$ifab_data_i_valid ),
    .DPA_LOCK(\$ifab_serdes_dpa_lock ),
    .EN(\$ofab_enable_buf ),
    .PLL_CLK(pll_clk),
    .PLL_LOCK(1'h1),
    .Q({ \data_i_serdes[9] , \data_i_serdes[8] , \data_i_serdes[7] , \data_i_serdes[6] , \data_i_serdes[5] , \data_i_serdes[4] , \data_i_serdes[3] , \data_i_serdes[2] , \data_i_serdes[1] , \data_i_serdes[0]  }),
    .RST(\$f2g_trx_reset_n_reset_buf_n )
  );
endmodule

