/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_4(in, clk, rst, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en, ibuf5_en, q_n, q_p);
  output [2:0] q_p;
  input ibuf1_en;
  input ibuf4_en;
  input clk;
  input [2:0] in;
  input ibuf2_en;
  input ibuf3_en;
  output [2:0] q_n;
  input rst;
  input ibuf5_en;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$clk ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf1_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf2_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf3_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf4_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf5_en ;
  wire [2:0] \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n ;
  wire [2:0] \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p ;
  (* src = "./rtl/primitive_example_design_4.v:10.10-10.23" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.rst_i_buf_out ;
  (* src = "./rtl/primitive_example_design_4.v:3.16-3.19" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.rst ;
  (* src = "./rtl/primitive_example_design_4.v:11.16-11.25" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$409.dffre_out ;
  (* src = "./rtl/primitive_example_design_4.v:9.16-9.25" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$409.i_buf_out ;
  (* src = "./rtl/primitive_example_design_4.v:3.11-3.14" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.clk ;
  (* src = "./rtl/primitive_example_design_4.v:6.18-6.21" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$409.q_p ;
  (* src = "./rtl/primitive_example_design_4.v:5.18-5.21" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$409.q_n ;
  (* src = "./rtl/primitive_example_design_4.v:4.20-4.28" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf2_en ;
  (* src = "./rtl/primitive_example_design_4.v:2.17-2.19" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$409.in ;
  (* src = "./rtl/primitive_example_design_4.v:4.38-4.46" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf4_en ;
  (* src = "./rtl/primitive_example_design_4.v:4.11-4.19" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf1_en ;
  (* src = "./rtl/primitive_example_design_4.v:4.29-4.37" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf3_en ;
  (* src = "./rtl/primitive_example_design_4.v:4.47-4.55" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.ibuf5_en ;
  (* src = "./rtl/primitive_example_design_4.v:13.38-13.49" *)
  wire \$auto$rs_design_edit.cc:682:execute$409.clk_buf_out ;
  (* src = "./rtl/primitive_example_design_4.v:6.18-6.21" *)
  (* src = "./rtl/primitive_example_design_4.v:6.18-6.21" *)
  wire [2:0] q_p;
  (* src = "./rtl/primitive_example_design_4.v:4.11-4.19" *)
  (* src = "./rtl/primitive_example_design_4.v:4.11-4.19" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_4.v:4.38-4.46" *)
  (* src = "./rtl/primitive_example_design_4.v:4.38-4.46" *)
  wire ibuf4_en;
  (* src = "./rtl/primitive_example_design_4.v:3.11-3.14" *)
  (* src = "./rtl/primitive_example_design_4.v:3.11-3.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_4.v:11.16-11.25" *)
  wire [2:0] dffre_out;
  (* src = "./rtl/primitive_example_design_4.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_4.v:2.17-2.19" *)
  wire [2:0] in;
  (* src = "./rtl/primitive_example_design_4.v:4.20-4.28" *)
  (* src = "./rtl/primitive_example_design_4.v:4.20-4.28" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_4.v:4.29-4.37" *)
  (* src = "./rtl/primitive_example_design_4.v:4.29-4.37" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_4.v:5.18-5.21" *)
  (* src = "./rtl/primitive_example_design_4.v:5.18-5.21" *)
  wire [2:0] q_n;
  (* src = "./rtl/primitive_example_design_4.v:9.16-9.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_4.v:13.38-13.49" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_4.v:3.16-3.19" *)
  (* src = "./rtl/primitive_example_design_4.v:3.16-3.19" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_4.v:10.10-10.23" *)
  wire rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_4.v:4.47-4.55" *)
  (* src = "./rtl/primitive_example_design_4.v:4.47-4.55" *)
  wire ibuf5_en;
  wire [2:0] \$iopadmap$q_p ;
  wire [2:0] \$iopadmap$q_n ;
  wire \$iopadmap$ibuf5_en ;
  wire \$iopadmap$ibuf4_en ;
  wire \$iopadmap$ibuf3_en ;
  wire \$iopadmap$ibuf2_en ;
  wire \$iopadmap$ibuf1_en ;
  wire \$iopadmap$clk ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.ibuf1_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf1_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf1_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.ibuf2_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf2_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf2_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.ibuf3_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf3_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf3_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.ibuf4_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf4_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf4_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.ibuf5_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.ibuf5_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf5_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.q_n  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_n [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.q_n_1  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_n [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.q_n_2  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n [2]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_n [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.q_p  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_p [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.q_p_1  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_p [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.q_p_2  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p [2]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.q_p [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:13.13-13.51" *)
  CLK_BUF \$auto$rs_design_edit.cc:682:execute$409.clk_buf_inst  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$clk ),
    .O(\$auto$rs_design_edit.cc:682:execute$409.clk_buf_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:15.14-15.72" *)
  O_BUF_DS \$auto$rs_design_edit.cc:682:execute$409.obuf_ds_inst1  (
    .I(\$auto$rs_design_edit.cc:682:execute$409.dffre_out [0]),
    .O_N(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n [0]),
    .O_P(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:16.14-16.72" *)
  O_BUF_DS \$auto$rs_design_edit.cc:682:execute$409.obuf_ds_inst2  (
    .I(\$auto$rs_design_edit.cc:682:execute$409.dffre_out [1]),
    .O_N(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n [1]),
    .O_P(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:17.14-17.72" *)
  O_BUF_DS \$auto$rs_design_edit.cc:682:execute$409.obuf_ds_inst3  (
    .I(\$auto$rs_design_edit.cc:682:execute$409.dffre_out [2]),
    .O_N(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_n [2]),
    .O_P(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$q_p [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:19.11-19.64" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.ibuf_inst1  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf2_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.in [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.i_buf_out [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:20.11-20.64" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.ibuf_inst2  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf3_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.in [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.i_buf_out [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:21.11-21.64" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.ibuf_inst3  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf4_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.in [2]),
    .O(\$auto$rs_design_edit.cc:682:execute$409.i_buf_out [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:22.11-22.63" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$409.ibuf_inst4  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf5_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$409.rst ),
    .O(\$auto$rs_design_edit.cc:682:execute$409.rst_i_buf_out )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$primitive_example_design_4.clk  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$409.clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$clk )
  );
  fabric_primitive_example_design_4 \$auto$rs_design_edit.cc:680:execute$408  (
    .\$iopadmap$ibuf1_en (\$iopadmap$ibuf1_en ),
    .clk_buf_out(clk_buf_out),
    .dffre_out(dffre_out),
    .i_buf_out(i_buf_out),
    .rst_i_buf_out(rst_i_buf_out)
  );
  assign \$iopadmap$ibuf1_en  = \$flatten$auto$rs_design_edit.cc:682:execute$409.$iopadmap$ibuf1_en ;
  assign \$auto$rs_design_edit.cc:682:execute$409.clk  = clk;
  assign clk_buf_out = \$auto$rs_design_edit.cc:682:execute$409.clk_buf_out ;
  assign \$auto$rs_design_edit.cc:682:execute$409.dffre_out  = dffre_out;
  assign i_buf_out = \$auto$rs_design_edit.cc:682:execute$409.i_buf_out ;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf1_en  = ibuf1_en;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf2_en  = ibuf2_en;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf3_en  = ibuf3_en;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf4_en  = ibuf4_en;
  assign \$auto$rs_design_edit.cc:682:execute$409.ibuf5_en  = ibuf5_en;
  assign \$auto$rs_design_edit.cc:682:execute$409.in  = in;
  assign q_n = \$auto$rs_design_edit.cc:682:execute$409.q_n ;
  assign q_p = \$auto$rs_design_edit.cc:682:execute$409.q_p ;
  assign \$auto$rs_design_edit.cc:682:execute$409.rst  = rst;
  assign rst_i_buf_out = \$auto$rs_design_edit.cc:682:execute$409.rst_i_buf_out ;
endmodule
