/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_4(in, clk, rst, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en, ibuf5_en, q_n, q_p);
  input rst;
  input clk;
  input ibuf3_en;
  input ibuf1_en;
  output [2:0] q_p;
  input ibuf2_en;
  input ibuf5_en;
  output [2:0] q_n;
  input [2:0] in;
  input ibuf4_en;
  (* src = "./rtl/primitive_example_design_4.v:11.16-11.25" *)
  wire [2:0] dffre_out;
  (* src = "./rtl/primitive_example_design_4.v:10.10-10.23" *)
  wire rst_i_buf_out;
  wire \$iopadmap$ibuf5_en ;
  (* src = "./rtl/primitive_example_design_4.v:3.16-3.19" *)
  (* src = "./rtl/primitive_example_design_4.v:3.16-3.19" *)
  wire rst;
  wire \$iopadmap$ibuf1_en ;
  wire \$iopadmap$rst ;
  wire [2:0] \$iopadmap$q_p ;
  wire [2:0] \$iopadmap$q_n ;
  wire [2:0] \$iopadmap$in ;
  wire \$iopadmap$ibuf4_en ;
  wire \$iopadmap$ibuf3_en ;
  wire \$iopadmap$ibuf2_en ;
  wire \$iopadmap$clk ;
  (* src = "./rtl/primitive_example_design_4.v:3.11-3.14" *)
  (* src = "./rtl/primitive_example_design_4.v:3.11-3.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_4.v:9.16-9.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_4.v:4.29-4.37" *)
  (* src = "./rtl/primitive_example_design_4.v:4.29-4.37" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_4.v:4.11-4.19" *)
  (* src = "./rtl/primitive_example_design_4.v:4.11-4.19" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_4.v:13.38-13.49" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_4.v:6.18-6.21" *)
  (* src = "./rtl/primitive_example_design_4.v:6.18-6.21" *)
  wire [2:0] q_p;
  (* src = "./rtl/primitive_example_design_4.v:4.20-4.28" *)
  (* src = "./rtl/primitive_example_design_4.v:4.20-4.28" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_4.v:4.47-4.55" *)
  (* src = "./rtl/primitive_example_design_4.v:4.47-4.55" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_4.v:5.18-5.21" *)
  (* src = "./rtl/primitive_example_design_4.v:5.18-5.21" *)
  wire [2:0] q_n;
  (* src = "./rtl/primitive_example_design_4.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_4.v:2.17-2.19" *)
  wire [2:0] in;
  (* src = "./rtl/primitive_example_design_4.v:4.38-4.46" *)
  (* src = "./rtl/primitive_example_design_4.v:4.38-4.46" *)
  wire ibuf4_en;
  fabric_primitive_example_design_4 \$auto$rs_design_edit.cc:578:execute$412  (
    .clk_buf_out(clk_buf_out),
    .dffre_out(dffre_out),
    .i_buf_out(i_buf_out),
    .\$iopadmap$ibuf1_en (\$iopadmap$ibuf1_en ),
    .rst_i_buf_out(rst_i_buf_out)
  );
  interface_primitive_example_design_4 \$auto$rs_design_edit.cc:580:execute$413  (
    .clk(clk),
    .ibuf1_en(ibuf1_en),
    .ibuf2_en(ibuf2_en),
    .ibuf3_en(ibuf3_en),
    .ibuf4_en(ibuf4_en),
    .ibuf5_en(ibuf5_en),
    .in(in),
    .q_n(q_n),
    .q_p(q_p),
    .rst(rst),
    .clk_buf_out(clk_buf_out),
    .dffre_out(dffre_out),
    .i_buf_out(i_buf_out),
    .\$iopadmap$ibuf1_en (\$iopadmap$ibuf1_en ),
    .rst_i_buf_out(rst_i_buf_out)
  );
endmodule

module interface_primitive_example_design_4(in, clk, rst, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en, ibuf5_en, q_n, q_p, i_buf_out, rst_i_buf_out, dffre_out, clk_buf_out, \$iopadmap$ibuf1_en );
  output rst_i_buf_out;
  output \$iopadmap$ibuf1_en ;
  input clk;
  input ibuf5_en;
  output clk_buf_out;
  input [2:0] in;
  input ibuf2_en;
  output [2:0] q_p;
  output [2:0] i_buf_out;
  input ibuf1_en;
  input [2:0] dffre_out;
  output [2:0] q_n;
  input rst;
  input ibuf3_en;
  input ibuf4_en;
  (* src = "./rtl/primitive_example_design_4.v:10.10-10.23" *)
  (* src = "./rtl/primitive_example_design_4.v:10.10-10.23" *)
  wire rst_i_buf_out;
  wire \$iopadmap$ibuf1_en ;
  (* src = "./rtl/primitive_example_design_4.v:3.11-3.14" *)
  (* src = "./rtl/primitive_example_design_4.v:3.11-3.14" *)
  wire clk;
  wire \$iopadmap$rst ;
  wire [2:0] \$iopadmap$q_p ;
  (* src = "./rtl/primitive_example_design_4.v:4.47-4.55" *)
  (* src = "./rtl/primitive_example_design_4.v:4.47-4.55" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_4.v:13.38-13.49" *)
  (* src = "./rtl/primitive_example_design_4.v:13.38-13.49" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_4.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_4.v:2.17-2.19" *)
  wire [2:0] in;
  wire [2:0] \$iopadmap$q_n ;
  wire [2:0] \$iopadmap$in ;
  wire \$iopadmap$ibuf5_en ;
  (* src = "./rtl/primitive_example_design_4.v:4.20-4.28" *)
  (* src = "./rtl/primitive_example_design_4.v:4.20-4.28" *)
  wire ibuf2_en;
  wire \$iopadmap$ibuf4_en ;
  wire \$iopadmap$ibuf3_en ;
  wire \$iopadmap$ibuf2_en ;
  (* src = "./rtl/primitive_example_design_4.v:6.18-6.21" *)
  (* src = "./rtl/primitive_example_design_4.v:6.18-6.21" *)
  wire [2:0] q_p;
  (* src = "./rtl/primitive_example_design_4.v:9.16-9.25" *)
  (* src = "./rtl/primitive_example_design_4.v:9.16-9.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_4.v:4.11-4.19" *)
  (* src = "./rtl/primitive_example_design_4.v:4.11-4.19" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_4.v:11.16-11.25" *)
  (* src = "./rtl/primitive_example_design_4.v:11.16-11.25" *)
  wire [2:0] dffre_out;
  (* src = "./rtl/primitive_example_design_4.v:5.18-5.21" *)
  (* src = "./rtl/primitive_example_design_4.v:5.18-5.21" *)
  wire [2:0] q_n;
  (* src = "./rtl/primitive_example_design_4.v:3.16-3.19" *)
  (* src = "./rtl/primitive_example_design_4.v:3.16-3.19" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_4.v:4.29-4.37" *)
  (* src = "./rtl/primitive_example_design_4.v:4.29-4.37" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_4.v:4.38-4.46" *)
  (* src = "./rtl/primitive_example_design_4.v:4.38-4.46" *)
  wire ibuf4_en;
  wire \$iopadmap$clk ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.ibuf1_en  (
    .O(\$iopadmap$ibuf1_en ),
    .EN(1'h1),
    .I(ibuf1_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_4.q_n_2  (
    .O(q_n[2]),
    .I(\$iopadmap$q_n [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_4.q_n  (
    .O(q_n[0]),
    .I(\$iopadmap$q_n [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_4.q_p_2  (
    .O(q_p[2]),
    .I(\$iopadmap$q_p [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.clk  (
    .O(\$iopadmap$clk ),
    .EN(1'h1),
    .I(clk)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.ibuf5_en  (
    .O(\$iopadmap$ibuf5_en ),
    .EN(1'h1),
    .I(ibuf5_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.in_1  (
    .O(\$iopadmap$in [1]),
    .EN(1'h1),
    .I(in[1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.rst  (
    .O(\$iopadmap$rst ),
    .EN(1'h1),
    .I(rst)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_4.q_n_1  (
    .O(q_n[1]),
    .I(\$iopadmap$q_n [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_4.q_p_1  (
    .O(q_p[1]),
    .I(\$iopadmap$q_p [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.in_2  (
    .O(\$iopadmap$in [2]),
    .EN(1'h1),
    .I(in[2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.ibuf3_en  (
    .O(\$iopadmap$ibuf3_en ),
    .EN(1'h1),
    .I(ibuf3_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.ibuf2_en  (
    .O(\$iopadmap$ibuf2_en ),
    .EN(1'h1),
    .I(ibuf2_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.in  (
    .O(\$iopadmap$in [0]),
    .EN(1'h1),
    .I(in[0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_4.ibuf4_en  (
    .O(\$iopadmap$ibuf4_en ),
    .EN(1'h1),
    .I(ibuf4_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_4.q_p  (
    .O(q_p[0]),
    .I(\$iopadmap$q_p [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:13.13-13.51" *)
  CLK_BUF clk_buf_inst (
    .I(\$iopadmap$clk ),
    .O(clk_buf_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:15.14-15.72" *)
  O_BUF_DS obuf_ds_inst1 (
    .I(dffre_out[0]),
    .O_N(\$iopadmap$q_n [0]),
    .O_P(\$iopadmap$q_p [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:16.14-16.72" *)
  O_BUF_DS obuf_ds_inst2 (
    .I(dffre_out[1]),
    .O_N(\$iopadmap$q_n [1]),
    .O_P(\$iopadmap$q_p [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:17.14-17.72" *)
  O_BUF_DS obuf_ds_inst3 (
    .I(dffre_out[2]),
    .O_N(\$iopadmap$q_n [2]),
    .O_P(\$iopadmap$q_p [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:19.11-19.64" *)
  I_BUF ibuf_inst1 (
    .EN(\$iopadmap$ibuf2_en ),
    .I(\$iopadmap$in [0]),
    .O(i_buf_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:20.11-20.64" *)
  I_BUF ibuf_inst2 (
    .EN(\$iopadmap$ibuf3_en ),
    .I(\$iopadmap$in [1]),
    .O(i_buf_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:21.11-21.64" *)
  I_BUF ibuf_inst3 (
    .EN(\$iopadmap$ibuf4_en ),
    .I(\$iopadmap$in [2]),
    .O(i_buf_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_4.v:22.11-22.63" *)
  I_BUF ibuf_inst4 (
    .EN(\$iopadmap$ibuf5_en ),
    .I(\$iopadmap$rst ),
    .O(rst_i_buf_out)
  );
endmodule
