/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module fabric_flop2flop(_13_, _00_, _12_);
  output _00_;
  input _12_;
  input _13_;
  wire _00_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire _01_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire _02_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire _03_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire _04_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire _05_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire _06_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire _07_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire _08_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire _09_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire _10_;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* keep = 32'h00000001 *)
  (* src = "flop2flop.v:17.5-17.7" *)
  wire q1;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE _15_ (
    .C(_12_),
    .D(_13_),
    .E(1'h1),
    .Q(q1),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE _16_ (
    .C(_12_),
    .D(q1),
    .E(1'h1),
    .Q(_00_),
    .R(1'h1)
  );
endmodule
