/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module flop2flop(din, dout, clk);
  input din;
  input clk;
  output dout;
  (* src = "flop2flop.v:13.7-13.10" *)
  wire \$auto$rs_design_edit.cc:682:execute$436.din ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$436.$auto$clkbufmap.cc:295:execute$430 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$clk ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$din ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$dout ;
  (* src = "flop2flop.v:14.7-14.10" *)
  wire \$auto$rs_design_edit.cc:682:execute$436.clk ;
  (* keep = 32'd1 *)
  (* src = "flop2flop.v:15.12-15.16" *)
  wire \$auto$rs_design_edit.cc:682:execute$436.dout ;
  (* src = "flop2flop.v:13.7-13.10" *)
  (* src = "flop2flop.v:13.7-13.10" *)
  wire din;
  wire \$iopadmap$dout ;
  wire \$iopadmap$din ;
  (* src = "flop2flop.v:14.7-14.10" *)
  (* src = "flop2flop.v:14.7-14.10" *)
  wire clk;
  wire \$auto$clkbufmap.cc:295:execute$430 ;
  (* keep = 32'd1 *)
  (* src = "flop2flop.v:15.12-15.16" *)
  (* keep = 32'd1 *)
  (* src = "flop2flop.v:15.12-15.16" *)
  wire dout;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$flop2flop.dout  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$dout ),
    .O(\$auto$rs_design_edit.cc:682:execute$436.dout )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$436.$auto$clkbufmap.cc:262:execute$428  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$436.$auto$clkbufmap.cc:295:execute$430 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$flop2flop.clk  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$436.clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$clk )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$flop2flop.din  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$436.din ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$din )
  );
  fabric_flop2flop \$auto$rs_design_edit.cc:680:execute$435  (
    .\$auto$clkbufmap.cc:295:execute$430 (\$auto$clkbufmap.cc:295:execute$430 ),
    .\$iopadmap$din (\$iopadmap$din ),
    .\$iopadmap$dout (\$iopadmap$dout )
  );
  assign \$auto$clkbufmap.cc:295:execute$430  = \$flatten$auto$rs_design_edit.cc:682:execute$436.$auto$clkbufmap.cc:295:execute$430 ;
  assign \$iopadmap$din  = \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$din ;
  assign \$flatten$auto$rs_design_edit.cc:682:execute$436.$iopadmap$dout  = \$iopadmap$dout ;
  assign \$auto$rs_design_edit.cc:682:execute$436.clk  = clk;
  assign \$auto$rs_design_edit.cc:682:execute$436.din  = din;
  assign dout = \$auto$rs_design_edit.cc:682:execute$436.dout ;
endmodule
