/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_5(q_n, iddr_out, dffre_out, rst_i_buf_out, \$auto$hierarchy.cc:1408:execute$1 , \$auto$hierarchy.cc:1408:execute$2 , \$auto$hierarchy.cc:1408:execute$3 );
  input \$auto$hierarchy.cc:1408:execute$1 ;
  input \$auto$hierarchy.cc:1408:execute$3 ;
  output [2:0] dffre_out;
  output [2:0] q_n;
  input [2:0] iddr_out;
  input \$auto$hierarchy.cc:1408:execute$2 ;
  input rst_i_buf_out;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$1 ;
  (* src = "./rtl/primitive_example_design_5.v:18.50-18.61" *)
  wire clk_buf_out;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$3 ;
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  wire [2:0] dffre_out;
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  wire [2:0] q_n;
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  wire [2:0] iddr_out;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$2 ;
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  wire rst_i_buf_out;
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:34.11-34.97" *)
  DFFRE ff_inst2 (
    .C(clk_buf_out),
    .D(iddr_out[1]),
    .E(1'h1),
    .Q(dffre_out[1]),
    .R(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:35.11-35.97" *)
  DFFRE ff_inst3 (
    .C(clk_buf_out),
    .D(iddr_out[2]),
    .E(1'h1),
    .Q(dffre_out[2]),
    .R(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:33.11-33.97" *)
  DFFRE ff_inst1 (
    .C(clk_buf_out),
    .D(iddr_out[0]),
    .E(1'h1),
    .Q(dffre_out[0]),
    .R(rst_i_buf_out)
  );
  assign q_n = 3'hx;
endmodule
