/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module fabric_primitive_example_design_5(iddr_out, dffre_out, rst_i_buf_out, \$auto$hierarchy.cc:1408:execute$1 , \$auto$hierarchy.cc:1408:execute$2 , \$auto$hierarchy.cc:1408:execute$3 , \$iopadmap$q_n );
  input \$auto$hierarchy.cc:1408:execute$1 ;
  input \$auto$hierarchy.cc:1408:execute$2 ;
  input \$auto$hierarchy.cc:1408:execute$3 ;
  output [2:0] dffre_out;
  input [2:0] iddr_out;
  output [2:0] \$iopadmap$q_n ;
  input rst_i_buf_out;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap414$iopadmap$primitive_example_design_5.obuft_ds_en3.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap413$iopadmap$primitive_example_design_5.q_p.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap413$iopadmap$primitive_example_design_5.q_p.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap413$iopadmap$primitive_example_design_5.q_p.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap412$iopadmap$primitive_example_design_5.q_n.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap412$iopadmap$primitive_example_design_5.q_n.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap412$iopadmap$primitive_example_design_5.q_n.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap411$iopadmap$primitive_example_design_5.q_p_1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap411$iopadmap$primitive_example_design_5.q_p_1.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap411$iopadmap$primitive_example_design_5.q_p_1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap410$iopadmap$primitive_example_design_5.obuft_ds_en2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap410$iopadmap$primitive_example_design_5.obuft_ds_en2.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap410$iopadmap$primitive_example_design_5.obuft_ds_en2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap409$iopadmap$primitive_example_design_5.ibuf4_en.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap409$iopadmap$primitive_example_design_5.ibuf4_en.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap409$iopadmap$primitive_example_design_5.ibuf4_en.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap408$iopadmap$primitive_example_design_5.in_2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap408$iopadmap$primitive_example_design_5.in_2.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap408$iopadmap$primitive_example_design_5.in_2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap407$iopadmap$primitive_example_design_5.obuft_ds_en1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap407$iopadmap$primitive_example_design_5.obuft_ds_en1.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap407$iopadmap$primitive_example_design_5.obuft_ds_en1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap406$iopadmap$primitive_example_design_5.iddr_en_1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap406$iopadmap$primitive_example_design_5.iddr_en_1.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap406$iopadmap$primitive_example_design_5.iddr_en_1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap405$iopadmap$primitive_example_design_5.ibuf1_en.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap405$iopadmap$primitive_example_design_5.ibuf1_en.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap405$iopadmap$primitive_example_design_5.ibuf1_en.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap404$iopadmap$primitive_example_design_5.iddr_en_2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap404$iopadmap$primitive_example_design_5.iddr_en_2.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap404$iopadmap$primitive_example_design_5.iddr_en_2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap403$iopadmap$primitive_example_design_5.in_1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap403$iopadmap$primitive_example_design_5.in_1.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap403$iopadmap$primitive_example_design_5.in_1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap402$iopadmap$primitive_example_design_5.rst.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap402$iopadmap$primitive_example_design_5.rst.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap402$iopadmap$primitive_example_design_5.rst.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap422$iopadmap$primitive_example_design_5.clk.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap415$iopadmap$primitive_example_design_5.q_n_2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap415$iopadmap$primitive_example_design_5.q_n_2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap415$iopadmap$primitive_example_design_5.q_n_2.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap416$iopadmap$primitive_example_design_5.iddr_en.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap416$iopadmap$primitive_example_design_5.iddr_en.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap417$iopadmap$primitive_example_design_5.ibuf3_en.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap417$iopadmap$primitive_example_design_5.ibuf3_en.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap418$iopadmap$primitive_example_design_5.ibuf5_en.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap417$iopadmap$primitive_example_design_5.ibuf3_en.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap418$iopadmap$primitive_example_design_5.ibuf5_en.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap418$iopadmap$primitive_example_design_5.ibuf5_en.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap414$iopadmap$primitive_example_design_5.obuft_ds_en3.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap414$iopadmap$primitive_example_design_5.obuft_ds_en3.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap416$iopadmap$primitive_example_design_5.iddr_en.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap401$auto$clkbufmap.cc:261:execute$399.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap420$iopadmap$primitive_example_design_5.q_n_1.O ;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$1 ;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$2 ;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$3 ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap422$iopadmap$primitive_example_design_5.clk.EN ;
  (* src = "./rtl/primitive_example_design_5.v:18.50-18.61" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  wire [2:0] dffre_out;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap420$iopadmap$primitive_example_design_5.q_n_1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap423$iopadmap$primitive_example_design_5.q_p_2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap421$iopadmap$primitive_example_design_5.ibuf2_en.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap419$iopadmap$primitive_example_design_5.in.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap422$iopadmap$primitive_example_design_5.clk.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap419$iopadmap$primitive_example_design_5.in.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap419$iopadmap$primitive_example_design_5.in.O ;
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  wire [2:0] iddr_out;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap421$iopadmap$primitive_example_design_5.ibuf2_en.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap420$iopadmap$primitive_example_design_5.q_n_1.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap421$iopadmap$primitive_example_design_5.ibuf2_en.I ;
  wire [2:0] \$iopadmap$q_n ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap423$iopadmap$primitive_example_design_5.q_p_2.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap423$iopadmap$primitive_example_design_5.q_p_2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap401$auto$clkbufmap.cc:261:execute$399.I ;
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  wire rst_i_buf_out;
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:34.11-34.97" *)
  DFFRE ff_inst2 (
    .C(clk_buf_out),
    .D(iddr_out[1]),
    .E(1'h1),
    .Q(dffre_out[1]),
    .R(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:35.11-35.97" *)
  DFFRE ff_inst3 (
    .C(clk_buf_out),
    .D(iddr_out[2]),
    .E(1'h1),
    .Q(dffre_out[2]),
    .R(rst_i_buf_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_5.v:33.11-33.97" *)
  DFFRE ff_inst1 (
    .C(clk_buf_out),
    .D(iddr_out[0]),
    .E(1'h1),
    .Q(dffre_out[0]),
    .R(rst_i_buf_out)
  );
  assign \$iopadmap$q_n  = 3'hx;
endmodule
