/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_5(in, ibuf2_en, rst, clk, ibuf1_en, ibuf3_en, ibuf4_en, ibuf5_en, obuft_ds_en1, obuft_ds_en2, obuft_ds_en3, iddr_en, q_p, q_n);
  input ibuf2_en;
  input rst;
  output [2:0] q_p;
  input clk;
  input [2:0] in;
  input ibuf1_en;
  input ibuf4_en;
  input obuft_ds_en3;
  input ibuf3_en;
  input obuft_ds_en1;
  input obuft_ds_en2;
  output [2:0] q_n;
  input ibuf5_en;
  input [2:0] iddr_en;
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  wire [2:0] dffre_out;
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  wire rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  wire ibuf2_en;
  wire \$iopadmap$clk ;
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  wire [2:0] q_p;
  wire \$iopadmap$rst ;
  wire [2:0] \$iopadmap$q_p ;
  wire [2:0] \$iopadmap$q_n ;
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  wire clk;
  wire \$iopadmap$ibuf2_en ;
  wire \$iopadmap$ibuf1_en ;
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  wire [2:0] in;
  wire \$iopadmap$obuft_ds_en3 ;
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  wire ibuf1_en;
  wire \$iopadmap$ibuf4_en ;
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  wire ibuf4_en;
  wire \$iopadmap$obuft_ds_en1 ;
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$3 ;
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  wire obuft_ds_en3;
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  wire obuft_ds_en1;
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  wire [2:0] iddr_out;
  wire [2:0] \$iopadmap$iddr_en ;
  wire \$iopadmap$ibuf3_en ;
  (* src = "./rtl/primitive_example_design_5.v:18.50-18.61" *)
  wire clk_buf_out;
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$1 ;
  (* src = "./rtl/primitive_example_design_5.v:15.16-15.25" *)
  wire [2:0] i_buf_out;
  wire \$iopadmap$obuft_ds_en2 ;
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$2 ;
  wire [2:0] \$iopadmap$in ;
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  wire obuft_ds_en2;
  wire \$auto$clkbufmap.cc:262:execute$400 ;
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  wire [2:0] q_n;
  wire \$iopadmap$ibuf5_en ;
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  wire [2:0] iddr_en;
  fabric_primitive_example_design_5 \$auto$rs_design_edit.cc:578:execute$424  (
    .\$auto$hierarchy.cc:1408:execute$1 (\$auto$hierarchy.cc:1408:execute$1 ),
    .\$auto$hierarchy.cc:1408:execute$2 (\$auto$hierarchy.cc:1408:execute$2 ),
    .\$auto$hierarchy.cc:1408:execute$3 (\$auto$hierarchy.cc:1408:execute$3 ),
    .dffre_out(dffre_out),
    .iddr_out(iddr_out),
    .\$iopadmap$q_n (\$iopadmap$q_n ),
    .rst_i_buf_out(rst_i_buf_out)
  );
  interface_primitive_example_design_5 \$auto$rs_design_edit.cc:580:execute$425  (
    .clk(clk),
    .ibuf1_en(ibuf1_en),
    .ibuf2_en(ibuf2_en),
    .ibuf3_en(ibuf3_en),
    .ibuf4_en(ibuf4_en),
    .ibuf5_en(ibuf5_en),
    .iddr_en(iddr_en),
    .in(in),
    .obuft_ds_en1(obuft_ds_en1),
    .obuft_ds_en2(obuft_ds_en2),
    .obuft_ds_en3(obuft_ds_en3),
    .q_n(q_n),
    .q_p(q_p),
    .rst(rst),
    .\$auto$hierarchy.cc:1408:execute$1 (\$auto$hierarchy.cc:1408:execute$1 ),
    .\$auto$hierarchy.cc:1408:execute$2 (\$auto$hierarchy.cc:1408:execute$2 ),
    .\$auto$hierarchy.cc:1408:execute$3 (\$auto$hierarchy.cc:1408:execute$3 ),
    .dffre_out(dffre_out),
    .iddr_out(iddr_out),
    .\$iopadmap$q_n (\$iopadmap$q_n ),
    .rst_i_buf_out(rst_i_buf_out)
  );
endmodule

module interface_primitive_example_design_5(in, ibuf2_en, rst, clk, ibuf1_en, ibuf3_en, ibuf4_en, ibuf5_en, obuft_ds_en1, obuft_ds_en2, obuft_ds_en3, iddr_en, q_p, q_n, iddr_out, dffre_out, rst_i_buf_out, \$auto$hierarchy.cc:1408:execute$1 , \$auto$hierarchy.cc:1408:execute$2 , \$auto$hierarchy.cc:1408:execute$3 , \$iopadmap$q_n 
);
  output rst_i_buf_out;
  output [2:0] q_n;
  input [2:0] dffre_out;
  output \$auto$hierarchy.cc:1408:execute$2 ;
  input clk;
  input ibuf4_en;
  input ibuf5_en;
  input obuft_ds_en3;
  input [2:0] \$iopadmap$q_n ;
  output \$auto$hierarchy.cc:1408:execute$1 ;
  input [2:0] in;
  input ibuf2_en;
  input ibuf1_en;
  input ibuf3_en;
  output [2:0] iddr_out;
  input obuft_ds_en1;
  input rst;
  input [2:0] iddr_en;
  input obuft_ds_en2;
  output [2:0] q_p;
  output \$auto$hierarchy.cc:1408:execute$3 ;
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  wire rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  wire [2:0] q_n;
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  wire [2:0] dffre_out;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$2 ;
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  wire clk;
  wire \$iopadmap$rst ;
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  wire ibuf4_en;
  wire \$iopadmap$ibuf1_en ;
  wire [2:0] \$iopadmap$q_p ;
  wire \$iopadmap$ibuf2_en ;
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  wire obuft_ds_en3;
  wire \$iopadmap$obuft_ds_en1 ;
  wire [2:0] \$iopadmap$q_n ;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$1 ;
  wire \$iopadmap$ibuf5_en ;
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  wire [2:0] in;
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  wire ibuf1_en;
  wire \$auto$clkbufmap.cc:262:execute$400 ;
  wire \$iopadmap$obuft_ds_en2 ;
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  wire [2:0] iddr_out;
  wire [2:0] \$iopadmap$iddr_en ;
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  wire obuft_ds_en1;
  wire \$iopadmap$obuft_ds_en3 ;
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  wire rst;
  wire \$iopadmap$ibuf4_en ;
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  wire [2:0] iddr_en;
  (* src = "./rtl/primitive_example_design_5.v:15.16-15.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:18.50-18.61" *)
  wire clk_buf_out;
  wire \$iopadmap$ibuf3_en ;
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  wire obuft_ds_en2;
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  wire [2:0] q_p;
  wire [2:0] \$iopadmap$in ;
  (* unused_bits = "0" *)
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$3 ;
  wire \$iopadmap$clk ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_5.q_p_2  (
    .O(q_p[2]),
    .I(\$iopadmap$q_p [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.clk  (
    .O(\$iopadmap$clk ),
    .EN(1'h1),
    .I(clk)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.obuft_ds_en2  (
    .O(\$iopadmap$obuft_ds_en2 ),
    .EN(1'h1),
    .I(obuft_ds_en2)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_5.q_n  (
    .O(q_n[0]),
    .I(\$iopadmap$q_n [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.obuft_ds_en3  (
    .O(\$iopadmap$obuft_ds_en3 ),
    .EN(1'h1),
    .I(obuft_ds_en3)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.in  (
    .O(\$iopadmap$in [0]),
    .EN(1'h1),
    .I(in[0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_5.q_p_1  (
    .O(q_p[1]),
    .I(\$iopadmap$q_p [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_5.q_p  (
    .O(q_p[0]),
    .I(\$iopadmap$q_p [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.ibuf4_en  (
    .O(\$iopadmap$ibuf4_en ),
    .EN(1'h1),
    .I(ibuf4_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.iddr_en_1  (
    .O(\$iopadmap$iddr_en [1]),
    .EN(1'h1),
    .I(iddr_en[1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.obuft_ds_en1  (
    .O(\$iopadmap$obuft_ds_en1 ),
    .EN(1'h1),
    .I(obuft_ds_en1)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.rst  (
    .O(\$iopadmap$rst ),
    .EN(1'h1),
    .I(rst)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.ibuf5_en  (
    .O(\$iopadmap$ibuf5_en ),
    .EN(1'h1),
    .I(ibuf5_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.in_1  (
    .O(\$iopadmap$in [1]),
    .EN(1'h1),
    .I(in[1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.ibuf1_en  (
    .O(\$iopadmap$ibuf1_en ),
    .EN(1'h1),
    .I(ibuf1_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_5.q_n_2  (
    .O(q_n[2]),
    .I(\$iopadmap$q_n [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.ibuf3_en  (
    .O(\$iopadmap$ibuf3_en ),
    .EN(1'h1),
    .I(ibuf3_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.in_2  (
    .O(\$iopadmap$in [2]),
    .EN(1'h1),
    .I(in[2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.iddr_en  (
    .O(\$iopadmap$iddr_en [0]),
    .EN(1'h1),
    .I(iddr_en[0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_5.q_n_1  (
    .O(q_n[1]),
    .I(\$iopadmap$q_n [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.iddr_en_2  (
    .O(\$iopadmap$iddr_en [2]),
    .EN(1'h1),
    .I(iddr_en[2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_5.ibuf2_en  (
    .O(\$iopadmap$ibuf2_en ),
    .EN(1'h1),
    .I(ibuf2_en)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:261:execute$399  (
    .O(clk_buf_out),
    .I(\$auto$clkbufmap.cc:262:execute$400 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:18.11-18.63" *)
  I_BUF clk_buf_inst (
    .EN(\$iopadmap$ibuf1_en ),
    .I(\$iopadmap$clk ),
    .O(\$auto$clkbufmap.cc:262:execute$400 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:24.15-24.89" *)
  O_BUFT_DS o_buft_inst1 (
    .I(dffre_out[0]),
    .O_N(\$iopadmap$q_p [0]),
    .O_P(\$iopadmap$q_p [0]),
    .T(\$iopadmap$obuft_ds_en1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:25.15-25.89" *)
  O_BUFT_DS o_buft_inst2 (
    .I(dffre_out[1]),
    .O_N(\$iopadmap$q_p [1]),
    .O_P(\$iopadmap$q_p [1]),
    .T(\$iopadmap$obuft_ds_en2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:26.15-26.89" *)
  O_BUFT_DS o_buft_inst3 (
    .I(dffre_out[2]),
    .O_N(\$iopadmap$q_p [2]),
    .O_P(\$iopadmap$q_p [2]),
    .T(\$iopadmap$obuft_ds_en3 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:28.11-28.64" *)
  I_BUF ibuf_inst1 (
    .EN(\$iopadmap$ibuf2_en ),
    .I(\$iopadmap$in [0]),
    .O(i_buf_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:29.11-29.64" *)
  I_BUF ibuf_inst2 (
    .EN(\$iopadmap$ibuf3_en ),
    .I(\$iopadmap$in [1]),
    .O(i_buf_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:30.11-30.64" *)
  I_BUF ibuf_inst3 (
    .EN(\$iopadmap$ibuf4_en ),
    .I(\$iopadmap$in [2]),
    .O(i_buf_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:31.11-31.63" *)
  I_BUF ibuf_inst4 (
    .EN(\$iopadmap$ibuf5_en ),
    .I(\$iopadmap$rst ),
    .O(rst_i_buf_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:20.11-20.94" *)
  I_DDR iddr_ist1 (
    .C(clk_buf_out),
    .D(i_buf_out[0]),
    .E(\$iopadmap$iddr_en [0]),
    .Q({ \$auto$hierarchy.cc:1408:execute$3 , iddr_out[0] }),
    .R(\$iopadmap$rst )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:21.11-21.94" *)
  I_DDR iddr_ist2 (
    .C(clk_buf_out),
    .D(i_buf_out[1]),
    .E(\$iopadmap$iddr_en [1]),
    .Q({ \$auto$hierarchy.cc:1408:execute$2 , iddr_out[1] }),
    .R(\$iopadmap$rst )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:22.11-22.94" *)
  I_DDR iddr_ist3 (
    .C(clk_buf_out),
    .D(i_buf_out[2]),
    .E(\$iopadmap$iddr_en [2]),
    .Q({ \$auto$hierarchy.cc:1408:execute$1 , iddr_out[2] }),
    .R(\$iopadmap$rst )
  );
endmodule
