/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_5(in, ibuf2_en, rst, clk, ibuf1_en, ibuf3_en, ibuf4_en, ibuf5_en, obuft_ds_en1, obuft_ds_en2, obuft_ds_en3, iddr_en, q_p, q_n);
  input ibuf1_en;
  input obuft_ds_en2;
  input obuft_ds_en3;
  output [2:0] q_n;
  input clk;
  input [2:0] iddr_en;
  output [2:0] q_p;
  input ibuf5_en;
  input ibuf4_en;
  input rst;
  input obuft_ds_en1;
  input ibuf2_en;
  input [2:0] in;
  input ibuf3_en;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$clkbufmap.cc:263:execute$400 ;
  (* unused_bits = "0" *)
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$1 ;
  (* unused_bits = "0" *)
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$2 ;
  (* unused_bits = "0" *)
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$3 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf1_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf2_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf3_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf4_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf5_en ;
  wire [2:0] \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$iddr_en ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en1 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en2 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en3 ;
  wire [2:0] \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_n ;
  wire [2:0] \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p ;
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.rst_i_buf_out ;
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.rst ;
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$420.q_p ;
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.ibuf4_en ;
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$420.q_n ;
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en3 ;
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en2 ;
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.ibuf2_en ;
  (* src = "./rtl/primitive_example_design_5.v:18.50-18.61" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.clk_buf_out ;
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en1 ;
  (* src = "./rtl/primitive_example_design_5.v:15.16-15.25" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$420.i_buf_out ;
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.ibuf3_en ;
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.ibuf1_en ;
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$420.in ;
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$420.dffre_out ;
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.clk ;
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$420.iddr_out ;
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  wire [2:0] \$auto$rs_design_edit.cc:682:execute$420.iddr_en ;
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  wire \$auto$rs_design_edit.cc:682:execute$420.ibuf5_en ;
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  (* src = "./rtl/primitive_example_design_5.v:6.11-6.19" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  (* src = "./rtl/primitive_example_design_5.v:7.24-7.36" *)
  wire obuft_ds_en2;
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  (* src = "./rtl/primitive_example_design_5.v:7.37-7.49" *)
  wire obuft_ds_en3;
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  (* src = "./rtl/primitive_example_design_5.v:10.18-10.21" *)
  wire [2:0] q_n;
  (* src = "./rtl/primitive_example_design_5.v:13.16-13.24" *)
  wire [2:0] iddr_out;
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  (* src = "./rtl/primitive_example_design_5.v:5.11-5.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  (* src = "./rtl/primitive_example_design_5.v:8.17-8.24" *)
  wire [2:0] iddr_en;
  (* src = "./rtl/primitive_example_design_5.v:14.16-14.25" *)
  wire [2:0] dffre_out;
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  (* src = "./rtl/primitive_example_design_5.v:9.18-9.21" *)
  wire [2:0] q_p;
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  (* src = "./rtl/primitive_example_design_5.v:6.47-6.55" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_5.v:18.50-18.61" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  (* src = "./rtl/primitive_example_design_5.v:6.38-6.46" *)
  wire ibuf4_en;
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  (* src = "./rtl/primitive_example_design_5.v:4.11-4.14" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  (* src = "./rtl/primitive_example_design_5.v:7.11-7.23" *)
  wire obuft_ds_en1;
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  (* src = "./rtl/primitive_example_design_5.v:3.11-3.19" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_5.v:2.17-2.19" *)
  wire [2:0] in;
  (* src = "./rtl/primitive_example_design_5.v:16.10-16.23" *)
  wire rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:15.16-15.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  (* src = "./rtl/primitive_example_design_5.v:6.29-6.37" *)
  wire ibuf3_en;
  wire [2:0] \$iopadmap$q_p ;
  wire [2:0] \$iopadmap$q_n ;
  wire \$iopadmap$obuft_ds_en3 ;
  wire \$iopadmap$obuft_ds_en2 ;
  wire \$iopadmap$obuft_ds_en1 ;
  wire [2:0] \$iopadmap$iddr_en ;
  wire \$iopadmap$ibuf5_en ;
  wire \$iopadmap$ibuf4_en ;
  wire \$iopadmap$ibuf3_en ;
  wire \$iopadmap$ibuf2_en ;
  wire \$iopadmap$ibuf1_en ;
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$3 ;
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$2 ;
  (* unused_bits = "0" *)
  wire \$auto$hierarchy.cc:1408:execute$1 ;
  wire \$auto$clkbufmap.cc:263:execute$400 ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.ibuf1_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.ibuf1_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf1_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.ibuf2_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.ibuf2_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf2_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.ibuf3_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.ibuf3_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf3_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.ibuf4_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.ibuf4_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf4_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.ibuf5_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.ibuf5_en ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf5_en )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.iddr_en  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.iddr_en [0]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$iddr_en [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.iddr_en_1  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.iddr_en [1]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$iddr_en [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.iddr_en_2  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.iddr_en [2]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$iddr_en [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.obuft_ds_en1  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en1 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en1 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.obuft_ds_en2  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en2 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en2 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.obuft_ds_en3  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en3 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en3 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.q_n  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_n [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.q_n [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.q_n_1  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_n [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.q_n [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.q_n_2  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_n [2]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.q_n [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.q_p  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.q_p [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.q_p_1  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.q_p [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$primitive_example_design_5.q_p_2  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [2]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.q_p [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:18.11-18.63" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$420.clk_buf_inst  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf1_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$420.clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$clkbufmap.cc:263:execute$400 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:24.15-24.89" *)
  O_BUFT_DS \$auto$rs_design_edit.cc:682:execute$420.o_buft_inst1  (
    .I(\$auto$rs_design_edit.cc:682:execute$420.dffre_out [0]),
    .O_N(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [0]),
    .O_P(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [0]),
    .T(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:25.15-25.89" *)
  O_BUFT_DS \$auto$rs_design_edit.cc:682:execute$420.o_buft_inst2  (
    .I(\$auto$rs_design_edit.cc:682:execute$420.dffre_out [1]),
    .O_N(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [1]),
    .O_P(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [1]),
    .T(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:26.15-26.89" *)
  O_BUFT_DS \$auto$rs_design_edit.cc:682:execute$420.o_buft_inst3  (
    .I(\$auto$rs_design_edit.cc:682:execute$420.dffre_out [2]),
    .O_N(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [2]),
    .O_P(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_p [2]),
    .T(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$obuft_ds_en3 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:28.11-28.64" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$420.ibuf_inst1  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf2_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$420.in [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.i_buf_out [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:29.11-29.64" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$420.ibuf_inst2  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf3_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$420.in [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.i_buf_out [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:30.11-30.64" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$420.ibuf_inst3  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf4_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$420.in [2]),
    .O(\$auto$rs_design_edit.cc:682:execute$420.i_buf_out [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:31.11-31.63" *)
  I_BUF \$auto$rs_design_edit.cc:682:execute$420.ibuf_inst4  (
    .EN(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$ibuf5_en ),
    .I(\$auto$rs_design_edit.cc:682:execute$420.rst ),
    .O(\$auto$rs_design_edit.cc:682:execute$420.rst_i_buf_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:20.11-20.94" *)
  I_DDR \$auto$rs_design_edit.cc:682:execute$420.iddr_ist1  (
    .C(\$auto$rs_design_edit.cc:682:execute$420.clk_buf_out ),
    .D(\$auto$rs_design_edit.cc:682:execute$420.i_buf_out [0]),
    .E(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$iddr_en [0]),
    .Q({ \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$3 , \$auto$rs_design_edit.cc:682:execute$420.iddr_out [0] }),
    .R(\$auto$rs_design_edit.cc:682:execute$420.rst )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:21.11-21.94" *)
  I_DDR \$auto$rs_design_edit.cc:682:execute$420.iddr_ist2  (
    .C(\$auto$rs_design_edit.cc:682:execute$420.clk_buf_out ),
    .D(\$auto$rs_design_edit.cc:682:execute$420.i_buf_out [1]),
    .E(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$iddr_en [1]),
    .Q({ \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$2 , \$auto$rs_design_edit.cc:682:execute$420.iddr_out [1] }),
    .R(\$auto$rs_design_edit.cc:682:execute$420.rst )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_5.v:22.11-22.94" *)
  I_DDR \$auto$rs_design_edit.cc:682:execute$420.iddr_ist3  (
    .C(\$auto$rs_design_edit.cc:682:execute$420.clk_buf_out ),
    .D(\$auto$rs_design_edit.cc:682:execute$420.i_buf_out [2]),
    .E(\$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$iddr_en [2]),
    .Q({ \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$1 , \$auto$rs_design_edit.cc:682:execute$420.iddr_out [2] }),
    .R(\$auto$rs_design_edit.cc:682:execute$420.rst )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$clkbufmap.cc:262:execute$399  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$clkbufmap.cc:263:execute$400 ),
    .O(\$auto$rs_design_edit.cc:682:execute$420.clk_buf_out )
  );
  fabric_primitive_example_design_5 \$auto$rs_design_edit.cc:680:execute$419  (
    .\$auto$hierarchy.cc:1408:execute$1 (\$auto$hierarchy.cc:1408:execute$1 ),
    .\$auto$hierarchy.cc:1408:execute$2 (\$auto$hierarchy.cc:1408:execute$2 ),
    .\$auto$hierarchy.cc:1408:execute$3 (\$auto$hierarchy.cc:1408:execute$3 ),
    .\$iopadmap$q_n (\$iopadmap$q_n ),
    .clk_buf_out(clk_buf_out),
    .dffre_out(dffre_out),
    .iddr_out(iddr_out),
    .rst_i_buf_out(rst_i_buf_out)
  );
  assign \$auto$hierarchy.cc:1408:execute$1  = \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$1 ;
  assign \$auto$hierarchy.cc:1408:execute$2  = \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$2 ;
  assign \$auto$hierarchy.cc:1408:execute$3  = \$flatten$auto$rs_design_edit.cc:682:execute$420.$auto$hierarchy.cc:1408:execute$3 ;
  assign \$flatten$auto$rs_design_edit.cc:682:execute$420.$iopadmap$q_n  = \$iopadmap$q_n ;
  assign \$auto$rs_design_edit.cc:682:execute$420.clk  = clk;
  assign clk_buf_out = \$auto$rs_design_edit.cc:682:execute$420.clk_buf_out ;
  assign \$auto$rs_design_edit.cc:682:execute$420.dffre_out  = dffre_out;
  assign \$auto$rs_design_edit.cc:682:execute$420.ibuf1_en  = ibuf1_en;
  assign \$auto$rs_design_edit.cc:682:execute$420.ibuf2_en  = ibuf2_en;
  assign \$auto$rs_design_edit.cc:682:execute$420.ibuf3_en  = ibuf3_en;
  assign \$auto$rs_design_edit.cc:682:execute$420.ibuf4_en  = ibuf4_en;
  assign \$auto$rs_design_edit.cc:682:execute$420.ibuf5_en  = ibuf5_en;
  assign \$auto$rs_design_edit.cc:682:execute$420.iddr_en  = iddr_en;
  assign iddr_out = \$auto$rs_design_edit.cc:682:execute$420.iddr_out ;
  assign \$auto$rs_design_edit.cc:682:execute$420.in  = in;
  assign \$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en1  = obuft_ds_en1;
  assign \$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en2  = obuft_ds_en2;
  assign \$auto$rs_design_edit.cc:682:execute$420.obuft_ds_en3  = obuft_ds_en3;
  assign q_n = \$auto$rs_design_edit.cc:682:execute$420.q_n ;
  assign q_p = \$auto$rs_design_edit.cc:682:execute$420.q_p ;
  assign \$auto$rs_design_edit.cc:682:execute$420.rst  = rst;
  assign rst_i_buf_out = \$auto$rs_design_edit.cc:682:execute$420.rst_i_buf_out ;
endmodule
