/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module ft(din, dout);
  output dout;
  input din;
  wire \$iopadmap$dout ;
  (* keep = 32'd1 *)
  (* src = "ft.v:11.10-11.14" *)
  (* keep = 32'd1 *)
  (* src = "ft.v:11.10-11.14" *)
  wire dout;
  (* keep = 32'd1 *)
  (* src = "ft.v:10.9-10.12" *)
  (* keep = 32'd1 *)
  (* src = "ft.v:10.9-10.12" *)
  wire din;
  wire \$iopadmap$din ;
  fabric_ft \$auto$rs_design_edit.cc:578:execute$394  (
    .\$iopadmap$din (\$iopadmap$din ),
    .\$iopadmap$dout (\$iopadmap$dout )
  );
  interface_ft \$auto$rs_design_edit.cc:580:execute$395  (
    .\$iopadmap$din (\$iopadmap$din ),
    .din(din),
    .dout(dout),
    .\$iopadmap$dout (\$iopadmap$dout )
  );
endmodule

module interface_ft(din, dout, \$iopadmap$dout , \$iopadmap$din );
  input \$iopadmap$dout ;
  output dout;
  input din;
  output \$iopadmap$din ;
  wire \$iopadmap$dout ;
  (* keep = 32'd1 *)
  (* src = "ft.v:11.10-11.14" *)
  (* keep = 32'd1 *)
  (* src = "ft.v:11.10-11.14" *)
  wire dout;
  (* keep = 32'd1 *)
  (* src = "ft.v:10.9-10.12" *)
  (* keep = 32'd1 *)
  (* src = "ft.v:10.9-10.12" *)
  wire din;
  wire \$iopadmap$din ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$ft.dout  (
    .O(dout),
    .I(\$iopadmap$dout )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$ft.din  (
    .O(\$iopadmap$din ),
    .EN(1'h1),
    .I(din)
  );
endmodule
