/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module flop2flop(din, dout, clk);
  input clk;
  input din;
  output dout;
  (* src = "flop2flop.v:14.7-14.10" *)
  (* src = "flop2flop.v:14.7-14.10" *)
  wire clk;
  (* src = "flop2flop.v:13.7-13.10" *)
  (* src = "flop2flop.v:13.7-13.10" *)
  wire din;
  wire \$iopadmap$clk ;
  wire \$iopadmap$din ;
  (* keep = 32'd1 *)
  (* src = "flop2flop.v:15.12-15.16" *)
  (* keep = 32'd1 *)
  (* src = "flop2flop.v:15.12-15.16" *)
  wire dout;
  wire \$iopadmap$dout ;
  wire \$auto$clkbufmap.cc:262:execute$429 ;
  wire \$auto$clkbufmap.cc:294:execute$430 ;
  fabric_flop2flop \$auto$rs_design_edit.cc:559:execute$435  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .\$auto$clkbufmap.cc:294:execute$430 (\$auto$clkbufmap.cc:294:execute$430 ),
    .\$iopadmap$din (\$iopadmap$din ),
    .\$auto$clkbufmap.cc:262:execute$429 (\$auto$clkbufmap.cc:262:execute$429 ),
    .\$iopadmap$dout (\$iopadmap$dout )
  );
  interface_flop2flop \$auto$rs_design_edit.cc:561:execute$436  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .clk(clk),
    .din(din),
    .dout(dout),
    .\$auto$clkbufmap.cc:294:execute$430 (\$auto$clkbufmap.cc:294:execute$430 ),
    .\$iopadmap$din (\$iopadmap$din ),
    .\$auto$clkbufmap.cc:262:execute$429 (\$auto$clkbufmap.cc:262:execute$429 ),
    .\$iopadmap$dout (\$iopadmap$dout )
  );
endmodule

module interface_flop2flop(din, dout, clk, \$auto$clkbufmap.cc:262:execute$429 , \$iopadmap$clk , \$iopadmap$din , \$iopadmap$dout , \$auto$clkbufmap.cc:294:execute$430 );
  input \$auto$clkbufmap.cc:262:execute$429 ;
  output \$auto$clkbufmap.cc:294:execute$430 ;
  output dout;
  input clk;
  input din;
  output \$iopadmap$clk ;
  input \$iopadmap$dout ;
  output \$iopadmap$din ;
  wire \$auto$clkbufmap.cc:262:execute$429 ;
  wire \$auto$clkbufmap.cc:294:execute$430 ;
  (* keep = 32'd1 *)
  (* src = "flop2flop.v:15.12-15.16" *)
  (* keep = 32'd1 *)
  (* src = "flop2flop.v:15.12-15.16" *)
  wire dout;
  (* src = "flop2flop.v:14.7-14.10" *)
  (* src = "flop2flop.v:14.7-14.10" *)
  wire clk;
  (* src = "flop2flop.v:13.7-13.10" *)
  (* src = "flop2flop.v:13.7-13.10" *)
  wire din;
  wire \$iopadmap$clk ;
  wire \$iopadmap$dout ;
  wire \$iopadmap$din ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/alain/os-fpga/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$flop2flop.clk  (
    .O(\$iopadmap$clk ),
    .EN(1'h1),
    .I(clk)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/alain/os-fpga/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$flop2flop.din  (
    .O(\$iopadmap$din ),
    .EN(1'h1),
    .I(din)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/alain/os-fpga/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$flop2flop.dout  (
    .O(dout),
    .I(\$iopadmap$dout )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/alain/os-fpga/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:261:execute$428  (
    .O(\$auto$clkbufmap.cc:294:execute$430 ),
    .I(\$auto$clkbufmap.cc:262:execute$429 )
  );
endmodule
