/* Generated by Yosys 0.18+10 (git sha1 b6be8bb62, gcc 11.1.0-1ubuntu1~20.04 -fPIC -Os) */

module primitive_example_design_3(A, B, i_buft_oe, ACC_FIR, Z, DLY_B, CLK, RESET, FEEDBACK, LOAD_ACC, SATURATE, SHIFT_RIGHT, ROUND, SUBTRACT, UNSIGNED_A, UNSIGNED_B, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en);
  input [19:0] A;
  input [5:0] ACC_FIR;
  input [17:0] B;
  input CLK;
  output [17:0] DLY_B;
  input [2:0] FEEDBACK;
  input LOAD_ACC;
  input RESET;
  input ROUND;
  input SATURATE;
  input [5:0] SHIFT_RIGHT;
  input SUBTRACT;
  input UNSIGNED_A;
  input UNSIGNED_B;
  output [37:0] Z;
  input [37:0] i_buft_oe;
  input [19:0] ibuf1_en;
  input [17:0] ibuf2_en;
  input [5:0] ibuf3_en;
  input [17:0] ibuf4_en;
  (* src = "./rtl/primitive_example_design_3.v:2.18-2.19" *)
  (* src = "./rtl/primitive_example_design_3.v:2.18-2.19" *)
  wire [19:0] A;
  (* src = "./rtl/primitive_example_design_3.v:5.17-5.24" *)
  (* src = "./rtl/primitive_example_design_3.v:5.17-5.24" *)
  wire [5:0] ACC_FIR;
  (* src = "./rtl/primitive_example_design_3.v:3.18-3.19" *)
  (* src = "./rtl/primitive_example_design_3.v:3.18-3.19" *)
  wire [17:0] B;
  (* src = "./rtl/primitive_example_design_3.v:8.11-8.14" *)
  (* src = "./rtl/primitive_example_design_3.v:8.11-8.14" *)
  wire CLK;
  (* src = "./rtl/primitive_example_design_3.v:7.23-7.28" *)
  (* src = "./rtl/primitive_example_design_3.v:7.23-7.28" *)
  wire [17:0] DLY_B;
  (* src = "./rtl/primitive_example_design_3.v:10.17-10.25" *)
  (* src = "./rtl/primitive_example_design_3.v:10.17-10.25" *)
  wire [2:0] FEEDBACK;
  (* src = "./rtl/primitive_example_design_3.v:11.11-11.19" *)
  (* src = "./rtl/primitive_example_design_3.v:11.11-11.19" *)
  wire LOAD_ACC;
  (* src = "./rtl/primitive_example_design_3.v:9.11-9.16" *)
  (* src = "./rtl/primitive_example_design_3.v:9.11-9.16" *)
  wire RESET;
  (* src = "./rtl/primitive_example_design_3.v:14.11-14.16" *)
  (* src = "./rtl/primitive_example_design_3.v:14.11-14.16" *)
  wire ROUND;
  (* src = "./rtl/primitive_example_design_3.v:12.11-12.19" *)
  (* src = "./rtl/primitive_example_design_3.v:12.11-12.19" *)
  wire SATURATE;
  (* src = "./rtl/primitive_example_design_3.v:13.17-13.28" *)
  (* src = "./rtl/primitive_example_design_3.v:13.17-13.28" *)
  wire [5:0] SHIFT_RIGHT;
  (* src = "./rtl/primitive_example_design_3.v:15.11-15.19" *)
  (* src = "./rtl/primitive_example_design_3.v:15.11-15.19" *)
  wire SUBTRACT;
  (* src = "./rtl/primitive_example_design_3.v:16.11-16.21" *)
  (* src = "./rtl/primitive_example_design_3.v:16.11-16.21" *)
  wire UNSIGNED_A;
  (* src = "./rtl/primitive_example_design_3.v:17.11-17.21" *)
  (* src = "./rtl/primitive_example_design_3.v:17.11-17.21" *)
  wire UNSIGNED_B;
  (* src = "./rtl/primitive_example_design_3.v:6.19-6.20" *)
  (* src = "./rtl/primitive_example_design_3.v:6.19-6.20" *)
  wire [37:0] Z;
  (* src = "./rtl/primitive_example_design_3.v:25.15-25.20" *)
  wire [19:0] a_out;
  (* src = "./rtl/primitive_example_design_3.v:26.15-26.20" *)
  wire [17:0] b_out;
  (* src = "./rtl/primitive_example_design_3.v:28.14-28.27" *)
  wire [5:0] i_buf_ACC_FIR;
  (* src = "./rtl/primitive_example_design_3.v:27.63-27.72" *)
  wire i_buf_clk;
  (* src = "./rtl/primitive_example_design_3.v:30.14-30.28" *)
  wire [2:0] i_buf_feedback;
  (* src = "./rtl/primitive_example_design_3.v:27.33-27.47" *)
  wire i_buf_load_acc;
  (* src = "./rtl/primitive_example_design_3.v:27.21-27.32" *)
  wire i_buf_reset;
  (* src = "./rtl/primitive_example_design_3.v:32.8-32.19" *)
  wire i_buf_round;
  (* src = "./rtl/primitive_example_design_3.v:27.48-27.62" *)
  wire i_buf_saturate;
  (* src = "./rtl/primitive_example_design_3.v:31.14-31.31" *)
  wire [5:0] i_buf_shift_right;
  (* src = "./rtl/primitive_example_design_3.v:32.20-32.34" *)
  wire i_buf_subtract;
  (* src = "./rtl/primitive_example_design_3.v:32.35-32.51" *)
  wire i_buf_unsigned_a;
  (* src = "./rtl/primitive_example_design_3.v:32.52-32.68" *)
  wire i_buf_unsigned_b;
  (* src = "./rtl/primitive_example_design_3.v:4.18-4.27" *)
  (* src = "./rtl/primitive_example_design_3.v:4.18-4.27" *)
  wire [37:0] i_buft_oe;
  (* src = "./rtl/primitive_example_design_3.v:27.8-27.20" *)
  wire i_buft_oe_in;
  (* src = "./rtl/primitive_example_design_3.v:18.18-18.26" *)
  (* src = "./rtl/primitive_example_design_3.v:18.18-18.26" *)
  wire [19:0] ibuf1_en;
  (* src = "./rtl/primitive_example_design_3.v:19.18-19.26" *)
  (* src = "./rtl/primitive_example_design_3.v:19.18-19.26" *)
  wire [17:0] ibuf2_en;
  (* src = "./rtl/primitive_example_design_3.v:20.17-20.25" *)
  (* src = "./rtl/primitive_example_design_3.v:20.17-20.25" *)
  wire [5:0] ibuf3_en;
  (* src = "./rtl/primitive_example_design_3.v:21.18-21.26" *)
  (* src = "./rtl/primitive_example_design_3.v:21.18-21.26" *)
  wire [17:0] ibuf4_en;
  wire [17:0] o_buf_dly_b;
  (* src = "./rtl/primitive_example_design_3.v:24.15-24.20" *)
  (* unused_bits = "37" *)
  wire [37:0] z_out;
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:97.6-111.17" *)
  DSP38 #(
    .COEFF_0(20'h00000),
    .COEFF_1(20'h00000),
    .COEFF_2(20'h00000),
    .COEFF_3(20'h00000),
    .DSP_MODE("MULTIPLY_ACCUMULATE"),
    .INPUT_REG_EN("TRUE"),
    .OUTPUT_REG_EN("TRUE")
  ) dsp38_inst (
    .A(a_out),
    .ACC_FIR(i_buf_ACC_FIR),
    .B(b_out),
    .CLK(i_buf_clk),
    .DLY_B(o_buf_dly_b),
    .FEEDBACK(i_buf_feedback),
    .LOAD_ACC(i_buf_load_acc),
    .RESET(i_buf_reset),
    .ROUND(i_buf_round),
    .SATURATE(i_buf_saturate),
    .SHIFT_RIGHT(i_buf_shift_right),
    .SUBTRACT(i_buf_subtract),
    .UNSIGNED_A(i_buf_unsigned_a),
    .UNSIGNED_B(i_buf_unsigned_b),
    .Z(z_out)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[0].i_buf_instance  (
    .EN(1'hx),
    .I(A[0]),
    .O(a_out[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[0].i_buf_instance_b  (
    .EN(ibuf2_en[0]),
    .I(B[0]),
    .O(b_out[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:51.13-51.96" *)
  I_BUF \gen_i_buf[0].i_buf_instance_shift  (
    .EN(ibuf3_en[0]),
    .I(SHIFT_RIGHT[0]),
    .O(i_buf_shift_right[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[10].i_buf_instance  (
    .EN(1'hx),
    .I(A[10]),
    .O(a_out[10])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[10].i_buf_instance_b  (
    .EN(ibuf2_en[10]),
    .I(B[10]),
    .O(b_out[10])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[11].i_buf_instance  (
    .EN(1'hx),
    .I(A[11]),
    .O(a_out[11])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[11].i_buf_instance_b  (
    .EN(ibuf2_en[11]),
    .I(B[11]),
    .O(b_out[11])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[12].i_buf_instance  (
    .EN(1'hx),
    .I(A[12]),
    .O(a_out[12])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[12].i_buf_instance_b  (
    .EN(ibuf2_en[12]),
    .I(B[12]),
    .O(b_out[12])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[13].i_buf_instance  (
    .EN(1'hx),
    .I(A[13]),
    .O(a_out[13])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[13].i_buf_instance_b  (
    .EN(ibuf2_en[13]),
    .I(B[13]),
    .O(b_out[13])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[14].i_buf_instance  (
    .EN(1'hx),
    .I(A[14]),
    .O(a_out[14])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[14].i_buf_instance_b  (
    .EN(ibuf2_en[14]),
    .I(B[14]),
    .O(b_out[14])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[15].i_buf_instance  (
    .EN(1'hx),
    .I(A[15]),
    .O(a_out[15])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[15].i_buf_instance_b  (
    .EN(ibuf2_en[15]),
    .I(B[15]),
    .O(b_out[15])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[16].i_buf_instance  (
    .EN(1'hx),
    .I(A[16]),
    .O(a_out[16])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[16].i_buf_instance_b  (
    .EN(ibuf2_en[16]),
    .I(B[16]),
    .O(b_out[16])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[17].i_buf_instance  (
    .EN(1'hx),
    .I(A[17]),
    .O(a_out[17])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[17].i_buf_instance_b  (
    .EN(ibuf2_en[17]),
    .I(B[17]),
    .O(b_out[17])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[18].i_buf_instance  (
    .EN(1'hx),
    .I(A[18]),
    .O(a_out[18])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[19].i_buf_instance  (
    .EN(1'hx),
    .I(A[19]),
    .O(a_out[19])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[1].i_buf_instance  (
    .EN(1'hx),
    .I(A[1]),
    .O(a_out[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[1].i_buf_instance_b  (
    .EN(ibuf2_en[1]),
    .I(B[1]),
    .O(b_out[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:51.13-51.96" *)
  I_BUF \gen_i_buf[1].i_buf_instance_shift  (
    .EN(ibuf3_en[1]),
    .I(SHIFT_RIGHT[1]),
    .O(i_buf_shift_right[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[2].i_buf_instance  (
    .EN(1'hx),
    .I(A[2]),
    .O(a_out[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[2].i_buf_instance_b  (
    .EN(ibuf2_en[2]),
    .I(B[2]),
    .O(b_out[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:51.13-51.96" *)
  I_BUF \gen_i_buf[2].i_buf_instance_shift  (
    .EN(ibuf3_en[2]),
    .I(SHIFT_RIGHT[2]),
    .O(i_buf_shift_right[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[3].i_buf_instance  (
    .EN(1'hx),
    .I(A[3]),
    .O(a_out[3])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[3].i_buf_instance_b  (
    .EN(ibuf2_en[3]),
    .I(B[3]),
    .O(b_out[3])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:51.13-51.96" *)
  I_BUF \gen_i_buf[3].i_buf_instance_shift  (
    .EN(ibuf3_en[3]),
    .I(SHIFT_RIGHT[3]),
    .O(i_buf_shift_right[3])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[4].i_buf_instance  (
    .EN(1'hx),
    .I(A[4]),
    .O(a_out[4])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[4].i_buf_instance_b  (
    .EN(ibuf2_en[4]),
    .I(B[4]),
    .O(b_out[4])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:51.13-51.96" *)
  I_BUF \gen_i_buf[4].i_buf_instance_shift  (
    .EN(ibuf3_en[4]),
    .I(SHIFT_RIGHT[4]),
    .O(i_buf_shift_right[4])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[5].i_buf_instance  (
    .EN(1'hx),
    .I(A[5]),
    .O(a_out[5])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[5].i_buf_instance_b  (
    .EN(ibuf2_en[5]),
    .I(B[5]),
    .O(b_out[5])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:51.13-51.96" *)
  I_BUF \gen_i_buf[5].i_buf_instance_shift  (
    .EN(ibuf3_en[5]),
    .I(SHIFT_RIGHT[5]),
    .O(i_buf_shift_right[5])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[6].i_buf_instance  (
    .EN(1'hx),
    .I(A[6]),
    .O(a_out[6])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[6].i_buf_instance_b  (
    .EN(ibuf2_en[6]),
    .I(B[6]),
    .O(b_out[6])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[7].i_buf_instance  (
    .EN(1'hx),
    .I(A[7]),
    .O(a_out[7])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[7].i_buf_instance_b  (
    .EN(ibuf2_en[7]),
    .I(B[7]),
    .O(b_out[7])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[8].i_buf_instance  (
    .EN(1'hx),
    .I(A[8]),
    .O(a_out[8])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[8].i_buf_instance_b  (
    .EN(ibuf2_en[8]),
    .I(B[8]),
    .O(b_out[8])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:37.13-37.67" *)
  I_BUF \gen_i_buf[9].i_buf_instance  (
    .EN(1'hx),
    .I(A[9]),
    .O(a_out[9])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:44.13-44.70" *)
  I_BUF \gen_i_buf[9].i_buf_instance_b  (
    .EN(ibuf2_en[9]),
    .I(B[9]),
    .O(b_out[9])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[0].o_buf_instance_a  (
    .I(o_buf_dly_b[0]),
    .O(DLY_B[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[10].o_buf_instance_a  (
    .I(o_buf_dly_b[10]),
    .O(DLY_B[10])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[11].o_buf_instance_a  (
    .I(o_buf_dly_b[11]),
    .O(DLY_B[11])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[12].o_buf_instance_a  (
    .I(o_buf_dly_b[12]),
    .O(DLY_B[12])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[13].o_buf_instance_a  (
    .I(o_buf_dly_b[13]),
    .O(DLY_B[13])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[14].o_buf_instance_a  (
    .I(o_buf_dly_b[14]),
    .O(DLY_B[14])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[15].o_buf_instance_a  (
    .I(o_buf_dly_b[15]),
    .O(DLY_B[15])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[16].o_buf_instance_a  (
    .I(o_buf_dly_b[16]),
    .O(DLY_B[16])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[17].o_buf_instance_a  (
    .I(o_buf_dly_b[17]),
    .O(DLY_B[17])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[1].o_buf_instance_a  (
    .I(o_buf_dly_b[1]),
    .O(DLY_B[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[2].o_buf_instance_a  (
    .I(o_buf_dly_b[2]),
    .O(DLY_B[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[3].o_buf_instance_a  (
    .I(o_buf_dly_b[3]),
    .O(DLY_B[3])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[4].o_buf_instance_a  (
    .I(o_buf_dly_b[4]),
    .O(DLY_B[4])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[5].o_buf_instance_a  (
    .I(o_buf_dly_b[5]),
    .O(DLY_B[5])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[6].o_buf_instance_a  (
    .I(o_buf_dly_b[6]),
    .O(DLY_B[6])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[7].o_buf_instance_a  (
    .I(o_buf_dly_b[7]),
    .O(DLY_B[7])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[8].o_buf_instance_a  (
    .I(o_buf_dly_b[8]),
    .O(DLY_B[8])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:85.13-85.63" *)
  O_BUF \gen_o_buf[9].o_buf_instance_a  (
    .I(o_buf_dly_b[9]),
    .O(DLY_B[9])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[0].o_buft_inst  (
    .I(z_out[0]),
    .O(Z[0]),
    .T(i_buft_oe_in)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[10].o_buft_inst  (
    .I(z_out[10]),
    .O(Z[10]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[11].o_buft_inst  (
    .I(z_out[11]),
    .O(Z[11]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[12].o_buft_inst  (
    .I(z_out[12]),
    .O(Z[12]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[13].o_buft_inst  (
    .I(z_out[13]),
    .O(Z[13]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[14].o_buft_inst  (
    .I(z_out[14]),
    .O(Z[14]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[15].o_buft_inst  (
    .I(z_out[15]),
    .O(Z[15]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[16].o_buft_inst  (
    .I(z_out[16]),
    .O(Z[16]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[17].o_buft_inst  (
    .I(z_out[17]),
    .O(Z[17]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[18].o_buft_inst  (
    .I(z_out[18]),
    .O(Z[18]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[19].o_buft_inst  (
    .I(z_out[19]),
    .O(Z[19]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[1].o_buft_inst  (
    .I(z_out[1]),
    .O(Z[1]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[20].o_buft_inst  (
    .I(z_out[20]),
    .O(Z[20]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[21].o_buft_inst  (
    .I(z_out[21]),
    .O(Z[21]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[22].o_buft_inst  (
    .I(z_out[22]),
    .O(Z[22]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[23].o_buft_inst  (
    .I(z_out[23]),
    .O(Z[23]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[24].o_buft_inst  (
    .I(z_out[24]),
    .O(Z[24]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[25].o_buft_inst  (
    .I(z_out[25]),
    .O(Z[25]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[26].o_buft_inst  (
    .I(z_out[26]),
    .O(Z[26]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[27].o_buft_inst  (
    .I(z_out[27]),
    .O(Z[27]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[28].o_buft_inst  (
    .I(z_out[28]),
    .O(Z[28]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[29].o_buft_inst  (
    .I(z_out[29]),
    .O(Z[29]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[2].o_buft_inst  (
    .I(z_out[2]),
    .O(Z[2]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[30].o_buft_inst  (
    .I(z_out[30]),
    .O(Z[30]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[31].o_buft_inst  (
    .I(z_out[31]),
    .O(Z[31]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[32].o_buft_inst  (
    .I(z_out[32]),
    .O(Z[32]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[33].o_buft_inst  (
    .I(z_out[33]),
    .O(Z[33]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[34].o_buft_inst  (
    .I(z_out[34]),
    .O(Z[34]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[35].o_buft_inst  (
    .I(z_out[35]),
    .O(Z[35]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[36].o_buft_inst  (
    .I(z_out[36]),
    .O(Z[36]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[3].o_buft_inst  (
    .I(z_out[3]),
    .O(Z[3]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[4].o_buft_inst  (
    .I(z_out[4]),
    .O(Z[4]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[5].o_buft_inst  (
    .I(z_out[5]),
    .O(Z[5]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[6].o_buft_inst  (
    .I(z_out[6]),
    .O(Z[6]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[7].o_buft_inst  (
    .I(z_out[7]),
    .O(Z[7]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[8].o_buft_inst  (
    .I(z_out[8]),
    .O(Z[8]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:78.16-78.71" *)
  O_BUFT \gen_o_buft[9].o_buft_inst  (
    .I(z_out[9]),
    .O(Z[9]),
    .T(1'hx)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:63.9-63.70" *)
  I_BUF i_buf_instance10 (
    .EN(ibuf4_en[8]),
    .I(RESET),
    .O(i_buf_reset)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:64.9-64.82" *)
  I_BUF i_buf_instance11 (
    .EN(ibuf4_en[9]),
    .I(FEEDBACK[0]),
    .O(i_buf_feedback[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:65.9-65.83" *)
  I_BUF i_buf_instance12 (
    .EN(ibuf4_en[10]),
    .I(FEEDBACK[1]),
    .O(i_buf_feedback[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:66.9-66.83" *)
  I_BUF i_buf_instance13 (
    .EN(ibuf4_en[11]),
    .I(FEEDBACK[2]),
    .O(i_buf_feedback[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:67.9-67.77" *)
  I_BUF i_buf_instance14 (
    .EN(ibuf4_en[12]),
    .I(LOAD_ACC),
    .O(i_buf_load_acc)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:68.9-68.77" *)
  I_BUF i_buf_instance15 (
    .EN(ibuf4_en[13]),
    .I(SATURATE),
    .O(i_buf_saturate)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:69.9-69.71" *)
  I_BUF i_buf_instance16 (
    .EN(ibuf4_en[14]),
    .I(ROUND),
    .O(i_buf_round)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:70.9-70.77" *)
  I_BUF i_buf_instance17 (
    .EN(ibuf4_en[15]),
    .I(SUBTRACT),
    .O(i_buf_subtract)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:71.9-71.81" *)
  I_BUF i_buf_instance18 (
    .EN(ibuf4_en[16]),
    .I(UNSIGNED_A),
    .O(i_buf_unsigned_a)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:72.9-72.81" *)
  I_BUF i_buf_instance19 (
    .EN(ibuf4_en[17]),
    .I(UNSIGNED_B),
    .O(i_buf_unsigned_b)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:55.9-55.65" *)
  I_BUF i_buf_instance2 (
    .EN(ibuf4_en[0]),
    .I(CLK),
    .O(i_buf_clk)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:56.9-56.74" *)
  I_BUF i_buf_instance3 (
    .EN(ibuf4_en[1]),
    .I(i_buft_oe[0]),
    .O(i_buft_oe_in)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:57.9-57.79" *)
  I_BUF i_buf_instance4 (
    .EN(ibuf4_en[2]),
    .I(ACC_FIR[0]),
    .O(i_buf_ACC_FIR[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:58.9-58.79" *)
  I_BUF i_buf_instance5 (
    .EN(ibuf4_en[3]),
    .I(ACC_FIR[1]),
    .O(i_buf_ACC_FIR[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:59.9-59.79" *)
  I_BUF i_buf_instance6 (
    .EN(ibuf4_en[4]),
    .I(ACC_FIR[2]),
    .O(i_buf_ACC_FIR[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:60.9-60.79" *)
  I_BUF i_buf_instance7 (
    .EN(ibuf4_en[5]),
    .I(ACC_FIR[3]),
    .O(i_buf_ACC_FIR[3])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:61.9-61.79" *)
  I_BUF i_buf_instance8 (
    .EN(ibuf4_en[6]),
    .I(ACC_FIR[4]),
    .O(i_buf_ACC_FIR[4])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/primitive_example_design_3.v:62.9-62.79" *)
  I_BUF i_buf_instance9 (
    .EN(ibuf4_en[7]),
    .I(ACC_FIR[5]),
    .O(i_buf_ACC_FIR[5])
  );
  assign Z[37] = 1'hx;
endmodule
