/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module fabric_and2(\$auto$clkbufmap.cc:295:execute$499 , \$iopadmap$reset , \$iopadmap$a , \$iopadmap$b , \$iopadmap$c );
  input \$iopadmap$b ;
  output \$iopadmap$c ;
  input \$iopadmap$reset ;
  input \$iopadmap$a ;
  input \$auto$clkbufmap.cc:295:execute$499 ;
  wire \$iopadmap$b ;
  (* init = 1'h0 *)
  (* init = 1'h0 *)
  wire \$iopadmap$c ;
  wire \$iopadmap$clk ;
  wire \$iopadmap$reset ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap500$auto$clkbufmap.cc:262:execute$497.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap500$auto$clkbufmap.cc:262:execute$497.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap501$iopadmap$and2.a.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap501$iopadmap$and2.a.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap501$iopadmap$and2.a.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap502$iopadmap$and2.c.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap502$iopadmap$and2.c.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap502$iopadmap$and2.c.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap503$iopadmap$and2.b.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap503$iopadmap$and2.b.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap503$iopadmap$and2.b.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap504$iopadmap$and2.reset.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap504$iopadmap$and2.reset.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap504$iopadmap$and2.reset.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap505$iopadmap$and2.clk.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap505$iopadmap$and2.clk.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap505$iopadmap$and2.clk.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [2:0] \$techmap506$abc$493$auto$blifparse.cc:515:parse_blif$495.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap506$abc$493$auto$blifparse.cc:515:parse_blif$495.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] \$techmap507$abc$493$auto$blifparse.cc:515:parse_blif$496.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap507$abc$493$auto$blifparse.cc:515:parse_blif$496.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] \$techmap508$abc$493$auto$blifparse.cc:515:parse_blif$494.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap508$abc$493$auto$blifparse.cc:515:parse_blif$494.Y ;
  wire \$iopadmap$a ;
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2.v:16.7-16.12" *)
  wire a_reg;
  wire \$abc$221$li2_li2 ;
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2.v:16.14-16.19" *)
  wire b_reg;
  wire \$auto$clkbufmap.cc:295:execute$499 ;
  wire \$abc$221$li1_li1 ;
  wire \$abc$221$li0_li0 ;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$221$auto$blifparse.cc:362:parse_blif$222  (
    .C(\$auto$clkbufmap.cc:295:execute$499 ),
    .D(\$abc$221$li0_li0 ),
    .E(1'h1),
    .Q(a_reg),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$221$auto$blifparse.cc:362:parse_blif$223  (
    .C(\$auto$clkbufmap.cc:295:execute$499 ),
    .D(\$abc$221$li1_li1 ),
    .E(1'h1),
    .Q(b_reg),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$221$auto$blifparse.cc:362:parse_blif$224  (
    .C(\$auto$clkbufmap.cc:295:execute$499 ),
    .D(\$abc$221$li2_li2 ),
    .E(1'h1),
    .Q(\$iopadmap$c ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h4)
  ) \$abc$493$auto$blifparse.cc:515:parse_blif$494  (
    .A({ \$iopadmap$b , \$iopadmap$reset  }),
    .Y(\$abc$221$li1_li1 )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h40)
  ) \$abc$493$auto$blifparse.cc:515:parse_blif$495  (
    .A({ b_reg, a_reg, \$iopadmap$reset  }),
    .Y(\$abc$221$li2_li2 )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h4)
  ) \$abc$493$auto$blifparse.cc:515:parse_blif$496  (
    .A({ \$iopadmap$a , \$iopadmap$reset  }),
    .Y(\$abc$221$li0_li0 )
  );
endmodule
