/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module and2(a, b, clk, reset, c);
  output c;
  input b;
  input a;
  input clk;
  input reset;
  (* src = "./Src/and2.v:10.9-10.10" *)
  wire \$auto$rs_design_edit.cc:682:execute$510.b ;
  (* src = "./Src/and2.v:12.9-12.14" *)
  wire \$auto$rs_design_edit.cc:682:execute$510.reset ;
  (* src = "./Src/and2.v:11.9-11.12" *)
  wire \$auto$rs_design_edit.cc:682:execute$510.clk ;
  (* keep = 32'd1 *)
  (* src = "./Src/and2.v:13.14-13.15" *)
  wire \$auto$rs_design_edit.cc:682:execute$510.c ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$510.$auto$clkbufmap.cc:295:execute$499 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$a ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$b ;
  (* init = 1'h0 *)
  wire \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$c ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$clk ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$reset ;
  (* src = "./Src/and2.v:9.9-9.10" *)
  wire \$auto$rs_design_edit.cc:682:execute$510.a ;
  wire \$iopadmap$reset ;
  (* keep = 32'd1 *)
  (* src = "./Src/and2.v:13.14-13.15" *)
  (* keep = 32'd1 *)
  (* src = "./Src/and2.v:13.14-13.15" *)
  wire c;
  (* init = 1'h0 *)
  wire \$iopadmap$c ;
  wire \$iopadmap$b ;
  wire \$iopadmap$a ;
  wire \$auto$clkbufmap.cc:295:execute$499 ;
  (* src = "./Src/and2.v:10.9-10.10" *)
  (* src = "./Src/and2.v:10.9-10.10" *)
  wire b;
  (* src = "./Src/and2.v:9.9-9.10" *)
  (* src = "./Src/and2.v:9.9-9.10" *)
  wire a;
  (* src = "./Src/and2.v:11.9-11.12" *)
  (* src = "./Src/and2.v:11.9-11.12" *)
  wire clk;
  (* src = "./Src/and2.v:12.9-12.14" *)
  (* src = "./Src/and2.v:12.9-12.14" *)
  wire reset;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$and2.a  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$510.a ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$a )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$and2.b  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$510.b ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$b )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$and2.c  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$c ),
    .O(\$auto$rs_design_edit.cc:682:execute$510.c )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$and2.clk  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$510.clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$clk )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$and2.reset  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$510.reset ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$reset )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$510.$auto$clkbufmap.cc:262:execute$497  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$510.$auto$clkbufmap.cc:295:execute$499 )
  );
  fabric_and2 \$auto$rs_design_edit.cc:680:execute$509  (
    .\$auto$clkbufmap.cc:295:execute$499 (\$auto$clkbufmap.cc:295:execute$499 ),
    .\$iopadmap$a (\$iopadmap$a ),
    .\$iopadmap$b (\$iopadmap$b ),
    .\$iopadmap$c (\$iopadmap$c ),
    .\$iopadmap$reset (\$iopadmap$reset )
  );
  assign \$auto$clkbufmap.cc:295:execute$499  = \$flatten$auto$rs_design_edit.cc:682:execute$510.$auto$clkbufmap.cc:295:execute$499 ;
  assign \$iopadmap$a  = \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$a ;
  assign \$iopadmap$b  = \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$b ;
  assign \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$c  = \$iopadmap$c ;
  assign \$iopadmap$reset  = \$flatten$auto$rs_design_edit.cc:682:execute$510.$iopadmap$reset ;
  assign \$auto$rs_design_edit.cc:682:execute$510.a  = a;
  assign \$auto$rs_design_edit.cc:682:execute$510.b  = b;
  assign c = \$auto$rs_design_edit.cc:682:execute$510.c ;
  assign \$auto$rs_design_edit.cc:682:execute$510.clk  = clk;
  assign \$auto$rs_design_edit.cc:682:execute$510.reset  = reset;
endmodule
