/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_1(clk, in, rst, Q, mux1_sel, mux2_sel, P, G, ram_addr, ram_we, buft_out, obuft_oe, ibuf0_en, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en, ibuf5_en, ibuf6_en, ibuf7_en, ibuf8_en
, ibuf9_en, ibuf10_en, ibuf11_en, ibuf12_en, ibuf13_en, ibuf14_en, ibuf15_en, ibuf16_en);
  input mux1_sel;
  input ibuf1_en;
  input [5:0] ram_addr;
  output Q;
  input ibuf2_en;
  input P;
  input [2:0] in;
  input rst;
  input ibuf15_en;
  input ibuf8_en;
  input G;
  input clk;
  input ibuf4_en;
  input ibuf14_en;
  input ibuf16_en;
  input ibuf5_en;
  input ibuf6_en;
  input ram_we;
  input ibuf13_en;
  input ibuf3_en;
  output buft_out;
  input ibuf9_en;
  input ibuf0_en;
  input mux2_sel;
  input ibuf7_en;
  input obuft_oe;
  input ibuf12_en;
  input ibuf11_en;
  input ibuf10_en;
  wire \$iopadmap$ibuf5_en ;
  (* src = "./rtl/primitive_example_design_1.v:16.10-16.23" *)
  wire rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_1.v:4.11-4.19" *)
  (* src = "./rtl/primitive_example_design_1.v:4.11-4.19" *)
  wire mux1_sel;
  (* src = "./rtl/primitive_example_design_1.v:5.20-5.28" *)
  (* src = "./rtl/primitive_example_design_1.v:5.20-5.28" *)
  wire ibuf1_en;
  wire \$iopadmap$rst ;
  (* src = "./rtl/primitive_example_design_1.v:22.10-22.17" *)
  wire ram_out;
  wire \$iopadmap$ibuf7_en ;
  (* hdlname = "ram_inst we" *)
  (* src = "./rtl/primitive_example_design_1.v:60.27-60.116|./rtl/primitive_example_design_1.v:95.8-95.10" *)
  wire \ram_inst.we ;
  wire \$iopadmap$Q ;
  (* hdlname = "ram_inst addr" *)
  (* src = "./rtl/primitive_example_design_1.v:60.27-60.116|./rtl/primitive_example_design_1.v:94.27-94.31" *)
  wire [5:0] \ram_inst.addr ;
  wire \$iopadmap$ibuf14_en ;
  wire \$iopadmap$mux1_sel ;
  (* src = "./rtl/primitive_example_design_1.v:7.17-7.25" *)
  (* src = "./rtl/primitive_example_design_1.v:7.17-7.25" *)
  wire [5:0] ram_addr;
  wire \$iopadmap$ram_we ;
  (* src = "./rtl/primitive_example_design_1.v:17.14-17.20" *)
  wire p_ibuf;
  (* src = "./rtl/primitive_example_design_1.v:10.12-10.13" *)
  (* src = "./rtl/primitive_example_design_1.v:10.12-10.13" *)
  wire Q;
  (* src = "./rtl/primitive_example_design_1.v:5.29-5.37" *)
  (* src = "./rtl/primitive_example_design_1.v:5.29-5.37" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_1.v:6.11-6.12" *)
  (* src = "./rtl/primitive_example_design_1.v:6.11-6.12" *)
  wire P;
  wire \$auto$clkbufmap.cc:262:execute$667 ;
  wire \$iopadmap$ibuf3_en ;
  wire \$auto$clkbufmap.cc:294:execute$665 ;
  wire \$iopadmap$ibuf9_en ;
  wire [5:0] \$iopadmap$ram_addr ;
  wire \$iopadmap$ibuf13_en ;
  (* src = "./rtl/primitive_example_design_1.v:16.24-16.38" *)
  wire i_buf_mux1_sel;
  wire \$iopadmap$ibuf10_en ;
  (* src = "./rtl/primitive_example_design_1.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_1.v:2.17-2.19" *)
  wire [2:0] in;
  (* src = "./rtl/primitive_example_design_1.v:3.16-3.19" *)
  (* src = "./rtl/primitive_example_design_1.v:3.16-3.19" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_1.v:14.21-14.32" *)
  wire clk_buf_out;
  wire \$iopadmap$ibuf12_en ;
  wire \$iopadmap$P ;
  (* src = "./rtl/primitive_example_design_1.v:5.151-5.160" *)
  (* src = "./rtl/primitive_example_design_1.v:5.151-5.160" *)
  wire ibuf15_en;
  (* src = "./rtl/primitive_example_design_1.v:5.83-5.91" *)
  (* src = "./rtl/primitive_example_design_1.v:5.83-5.91" *)
  wire ibuf8_en;
  (* src = "./rtl/primitive_example_design_1.v:6.13-6.14" *)
  (* src = "./rtl/primitive_example_design_1.v:6.13-6.14" *)
  wire G;
  (* src = "./rtl/primitive_example_design_1.v:3.11-3.14" *)
  (* src = "./rtl/primitive_example_design_1.v:3.11-3.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_1.v:5.47-5.55" *)
  (* src = "./rtl/primitive_example_design_1.v:5.47-5.55" *)
  wire ibuf4_en;
  (* src = "./rtl/primitive_example_design_1.v:5.141-5.150" *)
  (* src = "./rtl/primitive_example_design_1.v:5.141-5.150" *)
  wire ibuf14_en;
  (* src = "./rtl/primitive_example_design_1.v:5.161-5.170" *)
  (* src = "./rtl/primitive_example_design_1.v:5.161-5.170" *)
  wire ibuf16_en;
  (* src = "./rtl/primitive_example_design_1.v:5.56-5.64" *)
  (* src = "./rtl/primitive_example_design_1.v:5.56-5.64" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_1.v:23.16-23.29" *)
  wire ibuf_obuft_oe;
  wire [2:0] \$iopadmap$in ;
  wire \$iopadmap$ibuf11_en ;
  wire \$iopadmap$ibuf8_en ;
  (* src = "./rtl/primitive_example_design_1.v:5.65-5.73" *)
  (* src = "./rtl/primitive_example_design_1.v:5.65-5.73" *)
  wire ibuf6_en;
  (* src = "./rtl/primitive_example_design_1.v:8.11-8.17" *)
  (* src = "./rtl/primitive_example_design_1.v:8.11-8.17" *)
  wire ram_we;
  (* src = "./rtl/primitive_example_design_1.v:5.131-5.140" *)
  (* src = "./rtl/primitive_example_design_1.v:5.131-5.140" *)
  wire ibuf13_en;
  wire \$iopadmap$obuft_oe ;
  wire \$iopadmap$mux2_sel ;
  (* src = "./rtl/primitive_example_design_1.v:5.38-5.46" *)
  (* src = "./rtl/primitive_example_design_1.v:5.38-5.46" *)
  wire ibuf3_en;
  wire \$iopadmap$clk ;
  (* src = "./rtl/primitive_example_design_1.v:10.14-10.22" *)
  (* src = "./rtl/primitive_example_design_1.v:10.14-10.22" *)
  wire buft_out;
  (* src = "./rtl/primitive_example_design_1.v:5.92-5.100" *)
  (* src = "./rtl/primitive_example_design_1.v:5.92-5.100" *)
  wire ibuf9_en;
  wire \$iopadmap$ibuf6_en ;
  wire \$iopadmap$ibuf2_en ;
  wire \$iopadmap$ibuf16_en ;
  wire \$iopadmap$G ;
  (* src = "./rtl/primitive_example_design_1.v:5.11-5.19" *)
  (* src = "./rtl/primitive_example_design_1.v:5.11-5.19" *)
  wire ibuf0_en;
  wire \$iopadmap$buft_out ;
  (* src = "./rtl/primitive_example_design_1.v:4.20-4.28" *)
  (* src = "./rtl/primitive_example_design_1.v:4.20-4.28" *)
  wire mux2_sel;
  (* src = "./rtl/primitive_example_design_1.v:5.74-5.82" *)
  (* src = "./rtl/primitive_example_design_1.v:5.74-5.82" *)
  wire ibuf7_en;
  (* src = "./rtl/primitive_example_design_1.v:9.11-9.19" *)
  (* src = "./rtl/primitive_example_design_1.v:9.11-9.19" *)
  wire obuft_oe;
  wire \$iopadmap$ibuf4_en ;
  wire \$iopadmap$ibuf15_en ;
  (* hdlname = "ff_inst1 Q" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:48.15-48.66|./rtl/primitive_example_design_1.v:80.16-80.17" *)
  wire \ff_inst1.Q ;
  wire \$iopadmap$ibuf1_en ;
  (* src = "./rtl/primitive_example_design_1.v:5.121-5.130" *)
  (* src = "./rtl/primitive_example_design_1.v:5.121-5.130" *)
  wire ibuf12_en;
  wire \$iopadmap$ibuf0_en ;
  (* src = "./rtl/primitive_example_design_1.v:17.21-17.27" *)
  wire g_ibuf;
  (* src = "./rtl/primitive_example_design_1.v:16.39-16.53" *)
  wire i_buf_mux2_sel;
  (* src = "./rtl/primitive_example_design_1.v:12.16-12.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_1.v:5.111-5.120" *)
  (* src = "./rtl/primitive_example_design_1.v:5.111-5.120" *)
  wire ibuf11_en;
  (* src = "./rtl/primitive_example_design_1.v:5.101-5.110" *)
  (* src = "./rtl/primitive_example_design_1.v:5.101-5.110" *)
  wire ibuf10_en;
  wire \$auto$clkbufmap.cc:262:execute$664 ;
  fabric_primitive_example_design_1 \$auto$rs_design_edit.cc:578:execute$712  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .\$auto$clkbufmap.cc:262:execute$664 (\$auto$clkbufmap.cc:262:execute$664 ),
    .clk_buf_out(clk_buf_out),
    .\ff_inst1.Q (\ff_inst1.Q ),
    .g_ibuf(g_ibuf),
    .i_buf_mux1_sel(i_buf_mux1_sel),
    .i_buf_mux2_sel(i_buf_mux2_sel),
    .i_buf_out(i_buf_out),
    .p_ibuf(p_ibuf),
    .\ram_inst.addr (\ram_inst.addr ),
    .\ram_inst.we (\ram_inst.we ),
    .ram_out(ram_out),
    .rst_i_buf_out(rst_i_buf_out)
  );
  interface_primitive_example_design_1 \$auto$rs_design_edit.cc:580:execute$713  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .clk(clk),
    .G(G),
    .P(P),
    .Q(Q),
    .buft_out(buft_out),
    .ibuf0_en(ibuf0_en),
    .ibuf10_en(ibuf10_en),
    .ibuf11_en(ibuf11_en),
    .ibuf12_en(ibuf12_en),
    .ibuf13_en(ibuf13_en),
    .ibuf14_en(ibuf14_en),
    .ibuf15_en(ibuf15_en),
    .ibuf16_en(ibuf16_en),
    .ibuf1_en(ibuf1_en),
    .ibuf2_en(ibuf2_en),
    .ibuf3_en(ibuf3_en),
    .ibuf4_en(ibuf4_en),
    .ibuf5_en(ibuf5_en),
    .ibuf6_en(ibuf6_en),
    .ibuf7_en(ibuf7_en),
    .ibuf8_en(ibuf8_en),
    .ibuf9_en(ibuf9_en),
    .in(in),
    .mux1_sel(mux1_sel),
    .mux2_sel(mux2_sel),
    .obuft_oe(obuft_oe),
    .ram_addr(ram_addr),
    .ram_we(ram_we),
    .rst(rst),
    .\$auto$clkbufmap.cc:262:execute$664 (\$auto$clkbufmap.cc:262:execute$664 ),
    .clk_buf_out(clk_buf_out),
    .\ff_inst1.Q (\ff_inst1.Q ),
    .g_ibuf(g_ibuf),
    .i_buf_mux1_sel(i_buf_mux1_sel),
    .i_buf_mux2_sel(i_buf_mux2_sel),
    .i_buf_out(i_buf_out),
    .p_ibuf(p_ibuf),
    .\ram_inst.addr (\ram_inst.addr ),
    .\ram_inst.we (\ram_inst.we ),
    .ram_out(ram_out),
    .rst_i_buf_out(rst_i_buf_out)
  );
endmodule

module interface_primitive_example_design_1(clk, in, rst, Q, mux1_sel, mux2_sel, P, G, ram_addr, ram_we, buft_out, obuft_oe, ibuf0_en, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en, ibuf5_en, ibuf6_en, ibuf7_en, ibuf8_en
, ibuf9_en, ibuf10_en, ibuf11_en, ibuf12_en, ibuf13_en, ibuf14_en, ibuf15_en, ibuf16_en, i_buf_out, clk_buf_out, rst_i_buf_out, i_buf_mux1_sel, i_buf_mux2_sel, p_ibuf, g_ibuf, ram_out, \$auto$clkbufmap.cc:262:execute$664 , \ram_inst.addr , \$iopadmap$clk , \ram_inst.we , \ff_inst1.Q 
);
  output rst_i_buf_out;
  input ram_out;
  input ibuf3_en;
  output \ram_inst.we ;
  output [5:0] \ram_inst.addr ;
  output p_ibuf;
  input \$auto$clkbufmap.cc:262:execute$664 ;
  input ibuf5_en;
  input ibuf2_en;
  output [2:0] i_buf_out;
  output \$iopadmap$clk ;
  output clk_buf_out;
  input [2:0] in;
  output Q;
  input ibuf14_en;
  output i_buf_mux1_sel;
  input G;
  input ibuf13_en;
  input ibuf0_en;
  input ibuf1_en;
  input clk;
  output g_ibuf;
  input rst;
  input ibuf4_en;
  output buft_out;
  input ibuf7_en;
  input ibuf10_en;
  input ibuf16_en;
  input ibuf11_en;
  input obuft_oe;
  output i_buf_mux2_sel;
  input ibuf6_en;
  input ibuf12_en;
  input ibuf15_en;
  input P;
  input mux2_sel;
  input [5:0] ram_addr;
  input mux1_sel;
  input ibuf9_en;
  input ibuf8_en;
  input \ff_inst1.Q ;
  input ram_we;
  (* src = "./rtl/primitive_example_design_1.v:16.10-16.23" *)
  (* src = "./rtl/primitive_example_design_1.v:16.10-16.23" *)
  wire rst_i_buf_out;
  wire \$iopadmap$ibuf1_en ;
  wire \$iopadmap$rst ;
  (* src = "./rtl/primitive_example_design_1.v:22.10-22.17" *)
  (* src = "./rtl/primitive_example_design_1.v:22.10-22.17" *)
  wire ram_out;
  (* src = "./rtl/primitive_example_design_1.v:5.38-5.46" *)
  (* src = "./rtl/primitive_example_design_1.v:5.38-5.46" *)
  wire ibuf3_en;
  (* hdlname = "ram_inst we" *)
  (* src = "./rtl/primitive_example_design_1.v:60.27-60.116|./rtl/primitive_example_design_1.v:95.8-95.10" *)
  (* hdlname = "ram_inst we" *)
  (* src = "./rtl/primitive_example_design_1.v:60.27-60.116|./rtl/primitive_example_design_1.v:95.8-95.10" *)
  wire \ram_inst.we ;
  (* hdlname = "ram_inst addr" *)
  (* src = "./rtl/primitive_example_design_1.v:60.27-60.116|./rtl/primitive_example_design_1.v:94.27-94.31" *)
  (* hdlname = "ram_inst addr" *)
  (* src = "./rtl/primitive_example_design_1.v:60.27-60.116|./rtl/primitive_example_design_1.v:94.27-94.31" *)
  wire [5:0] \ram_inst.addr ;
  wire \$iopadmap$ram_we ;
  (* src = "./rtl/primitive_example_design_1.v:17.14-17.20" *)
  (* src = "./rtl/primitive_example_design_1.v:17.14-17.20" *)
  wire p_ibuf;
  wire \$auto$clkbufmap.cc:262:execute$664 ;
  wire [5:0] \$iopadmap$ram_addr ;
  wire \$iopadmap$obuft_oe ;
  (* src = "./rtl/primitive_example_design_1.v:5.56-5.64" *)
  (* src = "./rtl/primitive_example_design_1.v:5.56-5.64" *)
  wire ibuf5_en;
  wire \$iopadmap$mux2_sel ;
  (* src = "./rtl/primitive_example_design_1.v:5.29-5.37" *)
  (* src = "./rtl/primitive_example_design_1.v:5.29-5.37" *)
  wire ibuf2_en;
  wire \$iopadmap$ibuf2_en ;
  (* src = "./rtl/primitive_example_design_1.v:12.16-12.25" *)
  (* src = "./rtl/primitive_example_design_1.v:12.16-12.25" *)
  wire [2:0] i_buf_out;
  wire \$iopadmap$clk ;
  (* src = "./rtl/primitive_example_design_1.v:14.21-14.32" *)
  (* src = "./rtl/primitive_example_design_1.v:14.21-14.32" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_1.v:2.17-2.19" *)
  (* src = "./rtl/primitive_example_design_1.v:2.17-2.19" *)
  wire [2:0] in;
  (* src = "./rtl/primitive_example_design_1.v:10.12-10.13" *)
  (* src = "./rtl/primitive_example_design_1.v:10.12-10.13" *)
  wire Q;
  wire \$iopadmap$ibuf5_en ;
  (* src = "./rtl/primitive_example_design_1.v:5.141-5.150" *)
  (* src = "./rtl/primitive_example_design_1.v:5.141-5.150" *)
  wire ibuf14_en;
  (* src = "./rtl/primitive_example_design_1.v:16.24-16.38" *)
  (* src = "./rtl/primitive_example_design_1.v:16.24-16.38" *)
  wire i_buf_mux1_sel;
  (* src = "./rtl/primitive_example_design_1.v:6.13-6.14" *)
  (* src = "./rtl/primitive_example_design_1.v:6.13-6.14" *)
  wire G;
  (* src = "./rtl/primitive_example_design_1.v:5.131-5.140" *)
  (* src = "./rtl/primitive_example_design_1.v:5.131-5.140" *)
  wire ibuf13_en;
  (* src = "./rtl/primitive_example_design_1.v:5.11-5.19" *)
  (* src = "./rtl/primitive_example_design_1.v:5.11-5.19" *)
  wire ibuf0_en;
  (* src = "./rtl/primitive_example_design_1.v:5.20-5.28" *)
  (* src = "./rtl/primitive_example_design_1.v:5.20-5.28" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_1.v:3.11-3.14" *)
  (* src = "./rtl/primitive_example_design_1.v:3.11-3.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_1.v:17.21-17.27" *)
  (* src = "./rtl/primitive_example_design_1.v:17.21-17.27" *)
  wire g_ibuf;
  (* src = "./rtl/primitive_example_design_1.v:3.16-3.19" *)
  (* src = "./rtl/primitive_example_design_1.v:3.16-3.19" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_1.v:5.47-5.55" *)
  (* src = "./rtl/primitive_example_design_1.v:5.47-5.55" *)
  wire ibuf4_en;
  (* src = "./rtl/primitive_example_design_1.v:10.14-10.22" *)
  (* src = "./rtl/primitive_example_design_1.v:10.14-10.22" *)
  wire buft_out;
  wire \$auto$clkbufmap.cc:262:execute$667 ;
  (* src = "./rtl/primitive_example_design_1.v:5.74-5.82" *)
  (* src = "./rtl/primitive_example_design_1.v:5.74-5.82" *)
  wire ibuf7_en;
  (* src = "./rtl/primitive_example_design_1.v:5.101-5.110" *)
  (* src = "./rtl/primitive_example_design_1.v:5.101-5.110" *)
  wire ibuf10_en;
  wire \$iopadmap$G ;
  wire \$iopadmap$Q ;
  (* src = "./rtl/primitive_example_design_1.v:5.161-5.170" *)
  (* src = "./rtl/primitive_example_design_1.v:5.161-5.170" *)
  wire ibuf16_en;
  (* src = "./rtl/primitive_example_design_1.v:5.111-5.120" *)
  (* src = "./rtl/primitive_example_design_1.v:5.111-5.120" *)
  wire ibuf11_en;
  wire \$iopadmap$mux1_sel ;
  wire \$iopadmap$ibuf0_en ;
  wire \$iopadmap$buft_out ;
  (* src = "./rtl/primitive_example_design_1.v:9.11-9.19" *)
  (* src = "./rtl/primitive_example_design_1.v:9.11-9.19" *)
  wire obuft_oe;
  wire \$iopadmap$ibuf7_en ;
  (* src = "./rtl/primitive_example_design_1.v:16.39-16.53" *)
  (* src = "./rtl/primitive_example_design_1.v:16.39-16.53" *)
  wire i_buf_mux2_sel;
  wire \$iopadmap$ibuf8_en ;
  (* src = "./rtl/primitive_example_design_1.v:5.65-5.73" *)
  (* src = "./rtl/primitive_example_design_1.v:5.65-5.73" *)
  wire ibuf6_en;
  (* src = "./rtl/primitive_example_design_1.v:5.121-5.130" *)
  (* src = "./rtl/primitive_example_design_1.v:5.121-5.130" *)
  wire ibuf12_en;
  (* src = "./rtl/primitive_example_design_1.v:5.151-5.160" *)
  (* src = "./rtl/primitive_example_design_1.v:5.151-5.160" *)
  wire ibuf15_en;
  (* src = "./rtl/primitive_example_design_1.v:6.11-6.12" *)
  (* src = "./rtl/primitive_example_design_1.v:6.11-6.12" *)
  wire P;
  wire [2:0] \$iopadmap$in ;
  wire \$iopadmap$ibuf12_en ;
  (* src = "./rtl/primitive_example_design_1.v:4.20-4.28" *)
  (* src = "./rtl/primitive_example_design_1.v:4.20-4.28" *)
  wire mux2_sel;
  (* src = "./rtl/primitive_example_design_1.v:7.17-7.25" *)
  (* src = "./rtl/primitive_example_design_1.v:7.17-7.25" *)
  wire [5:0] ram_addr;
  wire \$iopadmap$ibuf9_en ;
  (* src = "./rtl/primitive_example_design_1.v:4.11-4.19" *)
  (* src = "./rtl/primitive_example_design_1.v:4.11-4.19" *)
  wire mux1_sel;
  (* src = "./rtl/primitive_example_design_1.v:5.92-5.100" *)
  (* src = "./rtl/primitive_example_design_1.v:5.92-5.100" *)
  wire ibuf9_en;
  (* src = "./rtl/primitive_example_design_1.v:5.83-5.91" *)
  (* src = "./rtl/primitive_example_design_1.v:5.83-5.91" *)
  wire ibuf8_en;
  wire \$iopadmap$ibuf6_en ;
  wire \$iopadmap$ibuf16_en ;
  wire \$iopadmap$ibuf3_en ;
  wire \$iopadmap$ibuf11_en ;
  wire \$iopadmap$ibuf14_en ;
  wire \$iopadmap$ibuf13_en ;
  (* src = "./rtl/primitive_example_design_1.v:23.16-23.29" *)
  wire ibuf_obuft_oe;
  (* hdlname = "ff_inst1 Q" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:48.15-48.66|./rtl/primitive_example_design_1.v:80.16-80.17" *)
  (* hdlname = "ff_inst1 Q" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:48.15-48.66|./rtl/primitive_example_design_1.v:80.16-80.17" *)
  wire \ff_inst1.Q ;
  wire \$iopadmap$ibuf10_en ;
  wire \$auto$clkbufmap.cc:294:execute$665 ;
  wire \$iopadmap$P ;
  wire \$iopadmap$ibuf4_en ;
  wire \$iopadmap$ibuf15_en ;
  (* src = "./rtl/primitive_example_design_1.v:8.11-8.17" *)
  (* src = "./rtl/primitive_example_design_1.v:8.11-8.17" *)
  wire ram_we;
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:41.11-41.77" *)
  I_BUF ibuf_inst15 (
    .EN(\$iopadmap$ibuf15_en ),
    .I(\$iopadmap$ram_addr [5]),
    .O(\ram_inst.addr [5])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ram_addr_5  (
    .O(\$iopadmap$ram_addr [5]),
    .EN(1'h1),
    .I(ram_addr[5])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.in_2  (
    .O(\$iopadmap$in [2]),
    .EN(1'h1),
    .I(in[2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.rst  (
    .O(\$iopadmap$rst ),
    .EN(1'h1),
    .I(rst)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.P  (
    .O(\$iopadmap$P ),
    .EN(1'h1),
    .I(P)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf0_en  (
    .O(\$iopadmap$ibuf0_en ),
    .EN(1'h1),
    .I(ibuf0_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.clk  (
    .O(\$iopadmap$clk ),
    .EN(1'h1),
    .I(clk)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ram_addr_1  (
    .O(\$iopadmap$ram_addr [1]),
    .EN(1'h1),
    .I(ram_addr[1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ram_addr_2  (
    .O(\$iopadmap$ram_addr [2]),
    .EN(1'h1),
    .I(ram_addr[2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ram_addr  (
    .O(\$iopadmap$ram_addr [0]),
    .EN(1'h1),
    .I(ram_addr[0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf3_en  (
    .O(\$iopadmap$ibuf3_en ),
    .EN(1'h1),
    .I(ibuf3_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf16_en  (
    .O(\$iopadmap$ibuf16_en ),
    .EN(1'h1),
    .I(ibuf16_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.in  (
    .O(\$iopadmap$in [0]),
    .EN(1'h1),
    .I(in[0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf9_en  (
    .O(\$iopadmap$ibuf9_en ),
    .EN(1'h1),
    .I(ibuf9_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf8_en  (
    .O(\$iopadmap$ibuf8_en ),
    .EN(1'h1),
    .I(ibuf8_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf7_en  (
    .O(\$iopadmap$ibuf7_en ),
    .EN(1'h1),
    .I(ibuf7_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf6_en  (
    .O(\$iopadmap$ibuf6_en ),
    .EN(1'h1),
    .I(ibuf6_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.G  (
    .O(\$iopadmap$G ),
    .EN(1'h1),
    .I(G)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf4_en  (
    .O(\$iopadmap$ibuf4_en ),
    .EN(1'h1),
    .I(ibuf4_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_1.buft_out  (
    .O(buft_out),
    .I(\$iopadmap$buft_out )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ram_addr_4  (
    .O(\$iopadmap$ram_addr [4]),
    .EN(1'h1),
    .I(ram_addr[4])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ram_we  (
    .O(\$iopadmap$ram_we ),
    .EN(1'h1),
    .I(ram_we)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ram_addr_3  (
    .O(\$iopadmap$ram_addr [3]),
    .EN(1'h1),
    .I(ram_addr[3])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf11_en  (
    .O(\$iopadmap$ibuf11_en ),
    .EN(1'h1),
    .I(ibuf11_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf13_en  (
    .O(\$iopadmap$ibuf13_en ),
    .EN(1'h1),
    .I(ibuf13_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.in_1  (
    .O(\$iopadmap$in [1]),
    .EN(1'h1),
    .I(in[1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf14_en  (
    .O(\$iopadmap$ibuf14_en ),
    .EN(1'h1),
    .I(ibuf14_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.mux2_sel  (
    .O(\$iopadmap$mux2_sel ),
    .EN(1'h1),
    .I(mux2_sel)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf15_en  (
    .O(\$iopadmap$ibuf15_en ),
    .EN(1'h1),
    .I(ibuf15_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.obuft_oe  (
    .O(\$iopadmap$obuft_oe ),
    .EN(1'h1),
    .I(obuft_oe)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$primitive_example_design_1.Q  (
    .O(Q),
    .I(\$iopadmap$Q )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf12_en  (
    .O(\$iopadmap$ibuf12_en ),
    .EN(1'h1),
    .I(ibuf12_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf2_en  (
    .O(\$iopadmap$ibuf2_en ),
    .EN(1'h1),
    .I(ibuf2_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf10_en  (
    .O(\$iopadmap$ibuf10_en ),
    .EN(1'h1),
    .I(ibuf10_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf5_en  (
    .O(\$iopadmap$ibuf5_en ),
    .EN(1'h1),
    .I(ibuf5_en)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.ibuf1_en  (
    .O(\$iopadmap$ibuf1_en ),
    .EN(1'h1),
    .I(ibuf1_en)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:261:execute$663  (
    .O(\$auto$clkbufmap.cc:294:execute$665 ),
    .I(\$auto$clkbufmap.cc:262:execute$664 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:261:execute$666  (
    .O(clk_buf_out),
    .I(\$auto$clkbufmap.cc:262:execute$667 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:42.11-42.70" *)
  I_BUF ibuf_inst16 (
    .EN(\$iopadmap$ibuf16_en ),
    .I(\$iopadmap$obuft_oe ),
    .O(ibuf_obuft_oe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:28.11-28.64" *)
  I_BUF ibuf_inst2 (
    .EN(\$iopadmap$ibuf2_en ),
    .I(\$iopadmap$in [1]),
    .O(i_buf_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:29.11-29.64" *)
  I_BUF ibuf_inst3 (
    .EN(\$iopadmap$ibuf3_en ),
    .I(\$iopadmap$in [2]),
    .O(i_buf_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:30.11-30.63" *)
  I_BUF ibuf_inst4 (
    .EN(\$iopadmap$ibuf4_en ),
    .I(\$iopadmap$rst ),
    .O(rst_i_buf_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:31.11-31.69" *)
  I_BUF ibuf_inst5 (
    .EN(\$iopadmap$ibuf5_en ),
    .I(\$iopadmap$mux1_sel ),
    .O(i_buf_mux1_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:32.11-32.69" *)
  I_BUF ibuf_inst6 (
    .EN(\$iopadmap$ibuf6_en ),
    .I(\$iopadmap$mux2_sel ),
    .O(i_buf_mux2_sel)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$primitive_example_design_1.mux1_sel  (
    .O(\$iopadmap$mux1_sel ),
    .EN(1'h1),
    .I(mux1_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:33.11-33.54" *)
  I_BUF ibuf_inst7 (
    .EN(\$iopadmap$ibuf7_en ),
    .I(\$iopadmap$P ),
    .O(p_ibuf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:34.11-34.54" *)
  I_BUF ibuf_inst8 (
    .EN(\$iopadmap$ibuf8_en ),
    .I(\$iopadmap$G ),
    .O(g_ibuf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:35.11-35.65" *)
  I_BUF ibuf_inst9 (
    .EN(\$iopadmap$ibuf9_en ),
    .I(\$iopadmap$ram_we ),
    .O(\ram_inst.we )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:25.11-25.63" *)
  I_BUF clk_buf_inst (
    .EN(\$iopadmap$ibuf0_en ),
    .I(\$auto$clkbufmap.cc:294:execute$665 ),
    .O(\$auto$clkbufmap.cc:262:execute$667 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:52.11-52.42" *)
  O_BUF o_buff_inst (
    .I(ram_out),
    .O(\$iopadmap$Q )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:50.12-50.65" *)
  O_BUFT obuft_inst (
    .I(\ff_inst1.Q ),
    .O(\$iopadmap$buft_out ),
    .T(ibuf_obuft_oe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:27.11-27.64" *)
  I_BUF ibuf_inst1 (
    .EN(\$iopadmap$ibuf1_en ),
    .I(\$iopadmap$in [0]),
    .O(i_buf_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:36.11-36.77" *)
  I_BUF ibuf_inst10 (
    .EN(\$iopadmap$ibuf10_en ),
    .I(\$iopadmap$ram_addr [0]),
    .O(\ram_inst.addr [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:37.11-37.77" *)
  I_BUF ibuf_inst11 (
    .EN(\$iopadmap$ibuf11_en ),
    .I(\$iopadmap$ram_addr [1]),
    .O(\ram_inst.addr [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:38.11-38.77" *)
  I_BUF ibuf_inst12 (
    .EN(\$iopadmap$ibuf12_en ),
    .I(\$iopadmap$ram_addr [2]),
    .O(\ram_inst.addr [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:39.11-39.77" *)
  I_BUF ibuf_inst13 (
    .EN(\$iopadmap$ibuf13_en ),
    .I(\$iopadmap$ram_addr [3]),
    .O(\ram_inst.addr [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_1.v:40.11-40.77" *)
  I_BUF ibuf_inst14 (
    .EN(\$iopadmap$ibuf14_en ),
    .I(\$iopadmap$ram_addr [4]),
    .O(\ram_inst.addr [4])
  );
endmodule
