/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module wrapper_primitive_example_design_2(in_n, in_p, clk, rst_n, rst_p, mux1_sel_n, mux1_sel_p, mux2_sel_n, mux2_sel_p, ibuf0_en, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en, ibuf5_en, ibuf6_en, ibuf7_en, ibuf8_en, ibuf9_en, ibuf10_en, ibuf11_en
, ibuf12_en, ibuf13_en, ibuf14_en, ibuf15_en, ibuf16_en, P, G, ram_addr, ram_we, obuft_oe, q_p, q_n, buft_out_p, buft_out_n);
  output q_n;
  input obuft_oe;
  input mux2_sel_n;
  input rst_p;
  input rst_n;
  input ram_we;
  input mux2_sel_p;
  input mux1_sel_p;
  input [2:0] in_p;
  input [5:0] ram_addr;
  input ibuf7_en;
  input ibuf9_en;
  input ibuf8_en;
  input G;
  input P;
  input mux1_sel_n;
  output buft_out_n;
  output buft_out_p;
  input clk;
  input [2:0] in_n;
  output q_p;
  input ibuf0_en;
  input ibuf10_en;
  input ibuf11_en;
  input ibuf12_en;
  input ibuf13_en;
  input ibuf14_en;
  input ibuf15_en;
  input ibuf16_en;
  input ibuf1_en;
  input ibuf2_en;
  input ibuf3_en;
  input ibuf4_en;
  input ibuf5_en;
  input ibuf6_en;
  (* src = "./rtl/primitive_example_design_2.v:10.16-10.19" *)
  (* src = "./rtl/primitive_example_design_2.v:10.16-10.19" *)
  wire q_n;
  (* src = "./rtl/primitive_example_design_2.v:9.11-9.19" *)
  (* src = "./rtl/primitive_example_design_2.v:9.11-9.19" *)
  wire obuft_oe;
  (* src = "./rtl/primitive_example_design_2.v:4.33-4.43" *)
  (* src = "./rtl/primitive_example_design_2.v:4.33-4.43" *)
  wire mux2_sel_n;
  (* src = "./rtl/primitive_example_design_2.v:3.22-3.27" *)
  (* src = "./rtl/primitive_example_design_2.v:3.22-3.27" *)
  wire rst_p;
  (* src = "./rtl/primitive_example_design_2.v:3.16-3.21" *)
  (* src = "./rtl/primitive_example_design_2.v:3.16-3.21" *)
  wire rst_n;
  (* src = "./rtl/primitive_example_design_2.v:17.10-17.23" *)
  wire rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_2.v:18.14-18.20" *)
  wire p_ibuf;
  (* src = "./rtl/primitive_example_design_2.v:8.11-8.17" *)
  (* src = "./rtl/primitive_example_design_2.v:8.11-8.17" *)
  wire ram_we;
  (* src = "./rtl/primitive_example_design_2.v:4.44-4.54" *)
  (* src = "./rtl/primitive_example_design_2.v:4.44-4.54" *)
  wire mux2_sel_p;
  (* src = "./rtl/primitive_example_design_2.v:23.10-23.17" *)
  wire ram_out;
  (* hdlname = "ram_inst we" *)
  (* src = "./rtl/primitive_example_design_2.v:61.27-61.116|./rtl/primitive_example_design_2.v:96.8-96.10" *)
  wire \ram_inst.we ;
  (* src = "./rtl/primitive_example_design_2.v:4.22-4.32" *)
  (* src = "./rtl/primitive_example_design_2.v:4.22-4.32" *)
  wire mux1_sel_p;
  (* src = "./rtl/primitive_example_design_2.v:2.22-2.26" *)
  (* src = "./rtl/primitive_example_design_2.v:2.22-2.26" *)
  wire [2:0] in_p;
  (* src = "./rtl/primitive_example_design_2.v:7.17-7.25" *)
  (* src = "./rtl/primitive_example_design_2.v:7.17-7.25" *)
  wire [5:0] ram_addr;
  (* src = "./rtl/primitive_example_design_2.v:5.74-5.82" *)
  (* src = "./rtl/primitive_example_design_2.v:5.74-5.82" *)
  wire ibuf7_en;
  (* hdlname = "ram_inst addr" *)
  (* src = "./rtl/primitive_example_design_2.v:61.27-61.116|./rtl/primitive_example_design_2.v:95.27-95.31" *)
  wire [5:0] \ram_inst.addr ;
  (* src = "./rtl/primitive_example_design_2.v:5.92-5.100" *)
  (* src = "./rtl/primitive_example_design_2.v:5.92-5.100" *)
  wire ibuf9_en;
  (* src = "./rtl/primitive_example_design_2.v:5.83-5.91" *)
  (* src = "./rtl/primitive_example_design_2.v:5.83-5.91" *)
  wire ibuf8_en;
  (* src = "./rtl/primitive_example_design_2.v:6.13-6.14" *)
  (* src = "./rtl/primitive_example_design_2.v:6.13-6.14" *)
  wire G;
  (* src = "./rtl/primitive_example_design_2.v:6.11-6.12" *)
  (* src = "./rtl/primitive_example_design_2.v:6.11-6.12" *)
  wire P;
  (* src = "./rtl/primitive_example_design_2.v:24.16-24.29" *)
  wire ibuf_obuft_oe;
  (* src = "./rtl/primitive_example_design_2.v:4.11-4.21" *)
  (* src = "./rtl/primitive_example_design_2.v:4.11-4.21" *)
  wire mux1_sel_n;
  (* src = "./rtl/primitive_example_design_2.v:10.31-10.41" *)
  (* src = "./rtl/primitive_example_design_2.v:10.31-10.41" *)
  wire buft_out_n;
  (* src = "./rtl/primitive_example_design_2.v:10.20-10.30" *)
  (* src = "./rtl/primitive_example_design_2.v:10.20-10.30" *)
  wire buft_out_p;
  (* src = "./rtl/primitive_example_design_2.v:3.11-3.14" *)
  (* src = "./rtl/primitive_example_design_2.v:3.11-3.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_2.v:15.21-15.32" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_2.v:2.17-2.21" *)
  (* src = "./rtl/primitive_example_design_2.v:2.17-2.21" *)
  wire [2:0] in_n;
  (* src = "./rtl/primitive_example_design_2.v:10.12-10.15" *)
  (* src = "./rtl/primitive_example_design_2.v:10.12-10.15" *)
  wire q_p;
  (* hdlname = "ff_inst1 Q" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:49.15-49.66|./rtl/primitive_example_design_2.v:81.16-81.17" *)
  wire \ff_inst1.Q ;
  (* src = "./rtl/primitive_example_design_2.v:18.21-18.27" *)
  wire g_ibuf;
  (* src = "./rtl/primitive_example_design_2.v:17.24-17.38" *)
  wire i_buf_mux1_sel;
  (* src = "./rtl/primitive_example_design_2.v:17.39-17.53" *)
  wire i_buf_mux2_sel;
  (* src = "./rtl/primitive_example_design_2.v:13.16-13.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_2.v:5.11-5.19" *)
  (* src = "./rtl/primitive_example_design_2.v:5.11-5.19" *)
  wire ibuf0_en;
  (* src = "./rtl/primitive_example_design_2.v:5.101-5.110" *)
  (* src = "./rtl/primitive_example_design_2.v:5.101-5.110" *)
  wire ibuf10_en;
  (* src = "./rtl/primitive_example_design_2.v:5.111-5.120" *)
  (* src = "./rtl/primitive_example_design_2.v:5.111-5.120" *)
  wire ibuf11_en;
  (* src = "./rtl/primitive_example_design_2.v:5.121-5.130" *)
  (* src = "./rtl/primitive_example_design_2.v:5.121-5.130" *)
  wire ibuf12_en;
  (* src = "./rtl/primitive_example_design_2.v:5.131-5.140" *)
  (* src = "./rtl/primitive_example_design_2.v:5.131-5.140" *)
  wire ibuf13_en;
  (* src = "./rtl/primitive_example_design_2.v:5.141-5.150" *)
  (* src = "./rtl/primitive_example_design_2.v:5.141-5.150" *)
  wire ibuf14_en;
  (* src = "./rtl/primitive_example_design_2.v:5.151-5.160" *)
  (* src = "./rtl/primitive_example_design_2.v:5.151-5.160" *)
  wire ibuf15_en;
  (* src = "./rtl/primitive_example_design_2.v:5.161-5.170" *)
  (* src = "./rtl/primitive_example_design_2.v:5.161-5.170" *)
  wire ibuf16_en;
  (* src = "./rtl/primitive_example_design_2.v:5.20-5.28" *)
  (* src = "./rtl/primitive_example_design_2.v:5.20-5.28" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_2.v:5.29-5.37" *)
  (* src = "./rtl/primitive_example_design_2.v:5.29-5.37" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_2.v:5.38-5.46" *)
  (* src = "./rtl/primitive_example_design_2.v:5.38-5.46" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_2.v:5.47-5.55" *)
  (* src = "./rtl/primitive_example_design_2.v:5.47-5.55" *)
  wire ibuf4_en;
  (* src = "./rtl/primitive_example_design_2.v:5.56-5.64" *)
  (* src = "./rtl/primitive_example_design_2.v:5.56-5.64" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_2.v:5.65-5.73" *)
  (* src = "./rtl/primitive_example_design_2.v:5.65-5.73" *)
  wire ibuf6_en;
  primitive_example_design_2 _0_ (
    .clk(clk),
    .clk_buf_out(clk_buf_out),
    .\ff_inst1.Q (\ff_inst1.Q ),
    .g_ibuf(g_ibuf),
    .i_buf_mux1_sel(i_buf_mux1_sel),
    .i_buf_mux2_sel(i_buf_mux2_sel),
    .i_buf_out(i_buf_out),
    .p_ibuf(p_ibuf),
    .\ram_inst.addr (\ram_inst.addr ),
    .\ram_inst.we (\ram_inst.we ),
    .ram_out(ram_out),
    .rst_i_buf_out(rst_i_buf_out)
  );
  interface_primitive_example_design_2 _1_ (
    .G(G),
    .P(P),
    .buft_out_n(buft_out_n),
    .buft_out_p(buft_out_p),
    .clk(clk),
    .clk_buf_out(clk_buf_out),
    .\ff_inst1.Q (\ff_inst1.Q ),
    .g_ibuf(g_ibuf),
    .i_buf_mux1_sel(i_buf_mux1_sel),
    .i_buf_mux2_sel(i_buf_mux2_sel),
    .i_buf_out(i_buf_out),
    .ibuf0_en(ibuf0_en),
    .ibuf10_en(ibuf10_en),
    .ibuf11_en(ibuf11_en),
    .ibuf12_en(ibuf12_en),
    .ibuf13_en(ibuf13_en),
    .ibuf14_en(ibuf14_en),
    .ibuf15_en(ibuf15_en),
    .ibuf16_en(ibuf16_en),
    .ibuf1_en(ibuf1_en),
    .ibuf2_en(ibuf2_en),
    .ibuf3_en(ibuf3_en),
    .ibuf4_en(ibuf4_en),
    .ibuf5_en(ibuf5_en),
    .ibuf6_en(ibuf6_en),
    .ibuf7_en(ibuf7_en),
    .ibuf8_en(ibuf8_en),
    .ibuf9_en(ibuf9_en),
    .in_n(in_n),
    .in_p(in_p),
    .mux1_sel_n(mux1_sel_n),
    .mux1_sel_p(mux1_sel_p),
    .mux2_sel_n(mux2_sel_n),
    .mux2_sel_p(mux2_sel_p),
    .obuft_oe(obuft_oe),
    .p_ibuf(p_ibuf),
    .q_n(q_n),
    .q_p(q_p),
    .ram_addr(ram_addr),
    .\ram_inst.addr (\ram_inst.addr ),
    .\ram_inst.we (\ram_inst.we ),
    .ram_out(ram_out),
    .ram_we(ram_we),
    .rst_i_buf_out(rst_i_buf_out),
    .rst_n(rst_n),
    .rst_p(rst_p)
  );
endmodule

module interface_primitive_example_design_2(in_n, in_p, clk, rst_n, rst_p, mux1_sel_n, mux1_sel_p, mux2_sel_n, mux2_sel_p, ibuf0_en, ibuf1_en, ibuf2_en, ibuf3_en, ibuf4_en, ibuf5_en, ibuf6_en, ibuf7_en, ibuf8_en, ibuf9_en, ibuf10_en, ibuf11_en
, ibuf12_en, ibuf13_en, ibuf14_en, ibuf15_en, ibuf16_en, P, G, ram_addr, ram_we, obuft_oe, q_p, q_n, buft_out_p, buft_out_n, i_buf_out, clk_buf_out, rst_i_buf_out, i_buf_mux1_sel, i_buf_mux2_sel, p_ibuf, g_ibuf
, ram_out, \ram_inst.addr , \ram_inst.we , \ff_inst1.Q );
  input rst_p;
  output rst_i_buf_out;
  input mux1_sel_n;
  input rst_n;
  input [2:0] in_n;
  input ibuf9_en;
  output q_n;
  input ram_we;
  input ram_out;
  output \ram_inst.we ;
  output [5:0] \ram_inst.addr ;
  input [5:0] ram_addr;
  input ibuf7_en;
  input [2:0] in_p;
  output q_p;
  input ibuf8_en;
  input mux1_sel_p;
  input G;
  input P;
  input mux2_sel_p;
  input obuft_oe;
  output buft_out_n;
  output buft_out_p;
  input clk;
  output clk_buf_out;
  input mux2_sel_n;
  output p_ibuf;
  input \ff_inst1.Q ;
  output g_ibuf;
  output i_buf_mux1_sel;
  output i_buf_mux2_sel;
  output [2:0] i_buf_out;
  input ibuf0_en;
  input ibuf10_en;
  input ibuf11_en;
  input ibuf12_en;
  input ibuf13_en;
  input ibuf14_en;
  input ibuf15_en;
  input ibuf16_en;
  input ibuf1_en;
  input ibuf2_en;
  input ibuf3_en;
  input ibuf4_en;
  input ibuf5_en;
  input ibuf6_en;
  (* src = "./rtl/primitive_example_design_2.v:3.22-3.27" *)
  (* src = "./rtl/primitive_example_design_2.v:3.22-3.27" *)
  wire rst_p;
  (* src = "./rtl/primitive_example_design_2.v:17.10-17.23" *)
  (* src = "./rtl/primitive_example_design_2.v:17.10-17.23" *)
  wire rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_2.v:4.11-4.21" *)
  (* src = "./rtl/primitive_example_design_2.v:4.11-4.21" *)
  wire mux1_sel_n;
  (* src = "./rtl/primitive_example_design_2.v:3.16-3.21" *)
  (* src = "./rtl/primitive_example_design_2.v:3.16-3.21" *)
  wire rst_n;
  (* src = "./rtl/primitive_example_design_2.v:2.17-2.21" *)
  (* src = "./rtl/primitive_example_design_2.v:2.17-2.21" *)
  wire [2:0] in_n;
  (* src = "./rtl/primitive_example_design_2.v:5.92-5.100" *)
  (* src = "./rtl/primitive_example_design_2.v:5.92-5.100" *)
  wire ibuf9_en;
  (* src = "./rtl/primitive_example_design_2.v:10.16-10.19" *)
  (* src = "./rtl/primitive_example_design_2.v:10.16-10.19" *)
  wire q_n;
  (* src = "./rtl/primitive_example_design_2.v:8.11-8.17" *)
  (* src = "./rtl/primitive_example_design_2.v:8.11-8.17" *)
  wire ram_we;
  (* src = "./rtl/primitive_example_design_2.v:23.10-23.17" *)
  (* src = "./rtl/primitive_example_design_2.v:23.10-23.17" *)
  wire ram_out;
  (* hdlname = "ram_inst we" *)
  (* src = "./rtl/primitive_example_design_2.v:61.27-61.116|./rtl/primitive_example_design_2.v:96.8-96.10" *)
  (* hdlname = "ram_inst we" *)
  (* src = "./rtl/primitive_example_design_2.v:61.27-61.116|./rtl/primitive_example_design_2.v:96.8-96.10" *)
  wire \ram_inst.we ;
  (* hdlname = "ram_inst addr" *)
  (* src = "./rtl/primitive_example_design_2.v:61.27-61.116|./rtl/primitive_example_design_2.v:95.27-95.31" *)
  (* hdlname = "ram_inst addr" *)
  (* src = "./rtl/primitive_example_design_2.v:61.27-61.116|./rtl/primitive_example_design_2.v:95.27-95.31" *)
  wire [5:0] \ram_inst.addr ;
  (* src = "./rtl/primitive_example_design_2.v:7.17-7.25" *)
  (* src = "./rtl/primitive_example_design_2.v:7.17-7.25" *)
  wire [5:0] ram_addr;
  (* src = "./rtl/primitive_example_design_2.v:24.16-24.29" *)
  wire ibuf_obuft_oe;
  (* src = "./rtl/primitive_example_design_2.v:5.74-5.82" *)
  (* src = "./rtl/primitive_example_design_2.v:5.74-5.82" *)
  wire ibuf7_en;
  (* src = "./rtl/primitive_example_design_2.v:2.22-2.26" *)
  (* src = "./rtl/primitive_example_design_2.v:2.22-2.26" *)
  wire [2:0] in_p;
  (* src = "./rtl/primitive_example_design_2.v:10.12-10.15" *)
  (* src = "./rtl/primitive_example_design_2.v:10.12-10.15" *)
  wire q_p;
  (* src = "./rtl/primitive_example_design_2.v:5.83-5.91" *)
  (* src = "./rtl/primitive_example_design_2.v:5.83-5.91" *)
  wire ibuf8_en;
  (* src = "./rtl/primitive_example_design_2.v:4.22-4.32" *)
  (* src = "./rtl/primitive_example_design_2.v:4.22-4.32" *)
  wire mux1_sel_p;
  (* src = "./rtl/primitive_example_design_2.v:6.13-6.14" *)
  (* src = "./rtl/primitive_example_design_2.v:6.13-6.14" *)
  wire G;
  (* src = "./rtl/primitive_example_design_2.v:6.11-6.12" *)
  (* src = "./rtl/primitive_example_design_2.v:6.11-6.12" *)
  wire P;
  (* src = "./rtl/primitive_example_design_2.v:4.44-4.54" *)
  (* src = "./rtl/primitive_example_design_2.v:4.44-4.54" *)
  wire mux2_sel_p;
  (* src = "./rtl/primitive_example_design_2.v:9.11-9.19" *)
  (* src = "./rtl/primitive_example_design_2.v:9.11-9.19" *)
  wire obuft_oe;
  (* src = "./rtl/primitive_example_design_2.v:10.31-10.41" *)
  (* src = "./rtl/primitive_example_design_2.v:10.31-10.41" *)
  wire buft_out_n;
  (* src = "./rtl/primitive_example_design_2.v:10.20-10.30" *)
  (* src = "./rtl/primitive_example_design_2.v:10.20-10.30" *)
  wire buft_out_p;
  (* src = "./rtl/primitive_example_design_2.v:3.11-3.14" *)
  (* src = "./rtl/primitive_example_design_2.v:3.11-3.14" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_2.v:15.21-15.32" *)
  (* src = "./rtl/primitive_example_design_2.v:15.21-15.32" *)
  wire clk_buf_out;
  (* src = "./rtl/primitive_example_design_2.v:4.33-4.43" *)
  (* src = "./rtl/primitive_example_design_2.v:4.33-4.43" *)
  wire mux2_sel_n;
  (* src = "./rtl/primitive_example_design_2.v:18.14-18.20" *)
  (* src = "./rtl/primitive_example_design_2.v:18.14-18.20" *)
  wire p_ibuf;
  (* hdlname = "ff_inst1 Q" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:49.15-49.66|./rtl/primitive_example_design_2.v:81.16-81.17" *)
  (* hdlname = "ff_inst1 Q" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:49.15-49.66|./rtl/primitive_example_design_2.v:81.16-81.17" *)
  wire \ff_inst1.Q ;
  (* src = "./rtl/primitive_example_design_2.v:18.21-18.27" *)
  (* src = "./rtl/primitive_example_design_2.v:18.21-18.27" *)
  wire g_ibuf;
  (* src = "./rtl/primitive_example_design_2.v:17.24-17.38" *)
  (* src = "./rtl/primitive_example_design_2.v:17.24-17.38" *)
  wire i_buf_mux1_sel;
  (* src = "./rtl/primitive_example_design_2.v:17.39-17.53" *)
  (* src = "./rtl/primitive_example_design_2.v:17.39-17.53" *)
  wire i_buf_mux2_sel;
  (* src = "./rtl/primitive_example_design_2.v:13.16-13.25" *)
  (* src = "./rtl/primitive_example_design_2.v:13.16-13.25" *)
  wire [2:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_2.v:5.11-5.19" *)
  (* src = "./rtl/primitive_example_design_2.v:5.11-5.19" *)
  wire ibuf0_en;
  (* src = "./rtl/primitive_example_design_2.v:5.101-5.110" *)
  (* src = "./rtl/primitive_example_design_2.v:5.101-5.110" *)
  wire ibuf10_en;
  (* src = "./rtl/primitive_example_design_2.v:5.111-5.120" *)
  (* src = "./rtl/primitive_example_design_2.v:5.111-5.120" *)
  wire ibuf11_en;
  (* src = "./rtl/primitive_example_design_2.v:5.121-5.130" *)
  (* src = "./rtl/primitive_example_design_2.v:5.121-5.130" *)
  wire ibuf12_en;
  (* src = "./rtl/primitive_example_design_2.v:5.131-5.140" *)
  (* src = "./rtl/primitive_example_design_2.v:5.131-5.140" *)
  wire ibuf13_en;
  (* src = "./rtl/primitive_example_design_2.v:5.141-5.150" *)
  (* src = "./rtl/primitive_example_design_2.v:5.141-5.150" *)
  wire ibuf14_en;
  (* src = "./rtl/primitive_example_design_2.v:5.151-5.160" *)
  (* src = "./rtl/primitive_example_design_2.v:5.151-5.160" *)
  wire ibuf15_en;
  (* src = "./rtl/primitive_example_design_2.v:5.161-5.170" *)
  (* src = "./rtl/primitive_example_design_2.v:5.161-5.170" *)
  wire ibuf16_en;
  (* src = "./rtl/primitive_example_design_2.v:5.20-5.28" *)
  (* src = "./rtl/primitive_example_design_2.v:5.20-5.28" *)
  wire ibuf1_en;
  (* src = "./rtl/primitive_example_design_2.v:5.29-5.37" *)
  (* src = "./rtl/primitive_example_design_2.v:5.29-5.37" *)
  wire ibuf2_en;
  (* src = "./rtl/primitive_example_design_2.v:5.38-5.46" *)
  (* src = "./rtl/primitive_example_design_2.v:5.38-5.46" *)
  wire ibuf3_en;
  (* src = "./rtl/primitive_example_design_2.v:5.47-5.55" *)
  (* src = "./rtl/primitive_example_design_2.v:5.47-5.55" *)
  wire ibuf4_en;
  (* src = "./rtl/primitive_example_design_2.v:5.56-5.64" *)
  (* src = "./rtl/primitive_example_design_2.v:5.56-5.64" *)
  wire ibuf5_en;
  (* src = "./rtl/primitive_example_design_2.v:5.65-5.73" *)
  (* src = "./rtl/primitive_example_design_2.v:5.65-5.73" *)
  wire ibuf6_en;
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:39.11-39.77" *)
  I_BUF ibuf_inst12 (
    .EN(ibuf12_en),
    .I(ram_addr[2]),
    .O(\ram_inst.addr [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:40.11-40.77" *)
  I_BUF ibuf_inst13 (
    .EN(ibuf13_en),
    .I(ram_addr[3]),
    .O(\ram_inst.addr [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:41.11-41.77" *)
  I_BUF ibuf_inst14 (
    .EN(ibuf14_en),
    .I(ram_addr[4]),
    .O(\ram_inst.addr [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:42.11-42.77" *)
  I_BUF ibuf_inst15 (
    .EN(ibuf15_en),
    .I(ram_addr[5]),
    .O(\ram_inst.addr [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:43.11-43.70" *)
  I_BUF ibuf_inst16 (
    .EN(ibuf16_en),
    .I(obuft_oe),
    .O(ibuf_obuft_oe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:34.11-34.54" *)
  I_BUF ibuf_inst7 (
    .EN(ibuf7_en),
    .I(P),
    .O(p_ibuf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:35.11-35.54" *)
  I_BUF ibuf_inst8 (
    .EN(ibuf8_en),
    .I(G),
    .O(g_ibuf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:36.11-36.65" *)
  I_BUF ibuf_inst9 (
    .EN(ibuf9_en),
    .I(ram_we),
    .O(\ram_inst.we )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:26.11-26.63" *)
  I_BUF clk_buf_inst (
    .EN(ibuf0_en),
    .I(clk),
    .O(clk_buf_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:53.14-53.62" *)
  O_BUF_DS o_buff_ds_inst (
    .I(ram_out),
    .O_N(q_n),
    .O_P(q_p)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:51.15-51.92" *)
  O_BUFT_DS obuft_ds_inst (
    .I(\ff_inst1.Q ),
    .O_N(buft_out_n),
    .O_P(buft_out_p),
    .T(ibuf_obuft_oe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:28.14-28.88" *)
  I_BUF_DS ibuf_ds_inst1 (
    .EN(ibuf1_en),
    .I_N(in_n[0]),
    .I_P(in_p[0]),
    .O(i_buf_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:29.14-29.88" *)
  I_BUF_DS ibuf_ds_inst2 (
    .EN(ibuf2_en),
    .I_N(in_n[1]),
    .I_P(in_p[1]),
    .O(i_buf_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:30.14-30.88" *)
  I_BUF_DS ibuf_ds_inst3 (
    .EN(ibuf3_en),
    .I_N(in_n[2]),
    .I_P(in_p[2]),
    .O(i_buf_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:31.14-31.85" *)
  I_BUF_DS ibuf_ds_inst4 (
    .EN(ibuf4_en),
    .I_N(rst_n),
    .I_P(rst_p),
    .O(rst_i_buf_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:32.14-32.96" *)
  I_BUF_DS ibuf_ds_inst5 (
    .EN(ibuf5_en),
    .I_N(mux1_sel_n),
    .I_P(mux1_sel_p),
    .O(i_buf_mux1_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:33.14-33.96" *)
  I_BUF_DS ibuf_ds_inst6 (
    .EN(ibuf6_en),
    .I_N(mux2_sel_n),
    .I_P(mux2_sel_p),
    .O(i_buf_mux2_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:37.11-37.77" *)
  I_BUF ibuf_inst10 (
    .EN(ibuf10_en),
    .I(ram_addr[0]),
    .O(\ram_inst.addr [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_2.v:38.11-38.77" *)
  I_BUF ibuf_inst11 (
    .EN(ibuf11_en),
    .I(ram_addr[1]),
    .O(\ram_inst.addr [1])
  );
endmodule
