/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module and2x2(a, b, clk1, clk2, reset, c1, c2);
  input clk2;
  input a;
  input b;
  output c1;
  output c2;
  input clk1;
  input reset;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [2:0] \$techmap584$abc$561$auto$blifparse.cc:515:parse_blif$564.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap584$abc$561$auto$blifparse.cc:515:parse_blif$564.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [2:0] \$techmap583$abc$561$auto$blifparse.cc:515:parse_blif$562.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap583$abc$561$auto$blifparse.cc:515:parse_blif$562.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] \$techmap582$abc$561$auto$blifparse.cc:515:parse_blif$563.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap582$abc$561$auto$blifparse.cc:515:parse_blif$563.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] \$techmap581$abc$561$auto$blifparse.cc:515:parse_blif$565.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap581$abc$561$auto$blifparse.cc:515:parse_blif$565.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap580$iopadmap$and2x2.b.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap580$iopadmap$and2x2.b.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap580$iopadmap$and2x2.b.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap579$iopadmap$and2x2.reset.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap579$iopadmap$and2x2.reset.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap579$iopadmap$and2x2.reset.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap578$iopadmap$and2x2.clk1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap578$iopadmap$and2x2.clk1.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap578$iopadmap$and2x2.clk1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap577$iopadmap$and2x2.c2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap577$iopadmap$and2x2.c2.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap577$iopadmap$and2x2.c2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap576$iopadmap$and2x2.c1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap576$iopadmap$and2x2.c1.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap576$iopadmap$and2x2.c1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap575$iopadmap$and2x2.clk2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap575$iopadmap$and2x2.clk2.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap575$iopadmap$and2x2.clk2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap574$iopadmap$and2x2.a.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap574$iopadmap$and2x2.a.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap574$iopadmap$and2x2.a.O ;
  wire \$iopadmap$clk2 ;
  (* src = "./Src/and2x2.v:36.9-36.13" *)
  (* src = "./Src/and2x2.v:36.9-36.13" *)
  wire clk2;
  (* src = "./Src/and2x2.v:33.9-33.10" *)
  (* src = "./Src/and2x2.v:33.9-33.10" *)
  wire a;
  (* src = "./Src/and2x2.v:34.9-34.10" *)
  (* src = "./Src/and2x2.v:34.9-34.10" *)
  wire b;
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:38.15-38.17" *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:38.15-38.17" *)
  wire c1;
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:39.15-39.17" *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:39.15-39.17" *)
  wire c2;
  (* src = "./Src/and2x2.v:35.9-35.13" *)
  (* src = "./Src/and2x2.v:35.9-35.13" *)
  wire clk1;
  (* src = "./Src/and2x2.v:37.9-37.14" *)
  (* src = "./Src/and2x2.v:37.9-37.14" *)
  wire reset;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap573$auto$clkbufmap.cc:262:execute$566.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap572$auto$clkbufmap.cc:262:execute$569.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap572$auto$clkbufmap.cc:262:execute$569.O ;
  wire \$auto$clkbufmap.cc:295:execute$571 ;
  wire \$iopadmap$a ;
  wire \$auto$clkbufmap.cc:295:execute$568 ;
  wire \$auto$clkbufmap.cc:263:execute$567 ;
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:18.3-27.8" *)
  wire \$abc$212$flatten\u1.$0\a_reg[0:0] ;
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:18.3-27.8" *)
  wire \$abc$212$flatten\u1.$0\b_reg[0:0] ;
  wire \$abc$236$li2_li2 ;
  wire \$abc$249$li2_li2 ;
  wire \$iopadmap$b ;
  (* init = 1'h0 *)
  wire \$iopadmap$c1 ;
  (* init = 1'h0 *)
  wire \$iopadmap$c2 ;
  wire \$iopadmap$clk1 ;
  wire \$auto$clkbufmap.cc:263:execute$570 ;
  wire \$iopadmap$reset ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap573$auto$clkbufmap.cc:262:execute$566.I ;
  (* hdlname = "u1 a_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:16.7-16.12" *)
  wire \u1.a_reg ;
  (* hdlname = "u1 b_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:16.14-16.19" *)
  wire \u1.b_reg ;
  (* hdlname = "u1 c" *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:13.14-13.15" *)
  wire \u1.c ;
  (* hdlname = "u2 a_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:43.9-43.34|./Src/and2x2.v:16.7-16.12" *)
  wire \u2.a_reg ;
  (* hdlname = "u2 b_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:43.9-43.34|./Src/and2x2.v:16.14-16.19" *)
  wire \u2.b_reg ;
  (* hdlname = "u2 c" *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:43.9-43.34|./Src/and2x2.v:13.14-13.15" *)
  wire \u2.c ;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h40)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$564  (
    .Y(\$abc$236$li2_li2 ),
    .A({ \u1.a_reg , \u1.b_reg , \$iopadmap$reset  })
  );
  (* keep = 32'h00000001 *)
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$and2x2.c2  (
    .O(c2),
    .I(\$iopadmap$c2 )
  );
  (* keep = 32'h00000001 *)
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$and2x2.c1  (
    .O(c1),
    .I(\$iopadmap$c1 )
  );
  (* keep = 32'h00000001 *)
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$and2x2.clk2  (
    .O(\$iopadmap$clk2 ),
    .EN(1'h1),
    .I(clk2)
  );
  (* keep = 32'h00000001 *)
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$and2x2.reset  (
    .O(\$iopadmap$reset ),
    .EN(1'h1),
    .I(reset)
  );
  (* keep = 32'h00000001 *)
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$and2x2.clk1  (
    .O(\$iopadmap$clk1 ),
    .EN(1'h1),
    .I(clk1)
  );
  (* keep = 32'h00000001 *)
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$and2x2.a  (
    .O(\$iopadmap$a ),
    .EN(1'h1),
    .I(a)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:262:execute$566  (
    .O(\$auto$clkbufmap.cc:295:execute$568 ),
    .I(\$auto$clkbufmap.cc:263:execute$567 )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:262:execute$569  (
    .O(\$auto$clkbufmap.cc:295:execute$571 ),
    .I(\$auto$clkbufmap.cc:263:execute$570 )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$236$auto$blifparse.cc:362:parse_blif$237  (
    .C(\$auto$clkbufmap.cc:295:execute$568 ),
    .D(\$abc$212$flatten\u1.$0\a_reg[0:0] ),
    .E(1'h1),
    .Q(\u1.a_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$236$auto$blifparse.cc:362:parse_blif$238  (
    .C(\$auto$clkbufmap.cc:295:execute$568 ),
    .D(\$abc$212$flatten\u1.$0\b_reg[0:0] ),
    .E(1'h1),
    .Q(\u1.b_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$236$auto$blifparse.cc:362:parse_blif$239  (
    .C(\$auto$clkbufmap.cc:295:execute$568 ),
    .D(\$abc$236$li2_li2 ),
    .E(1'h1),
    .Q(\$iopadmap$c1 ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$249$auto$blifparse.cc:362:parse_blif$250  (
    .C(\$auto$clkbufmap.cc:295:execute$571 ),
    .D(\$abc$212$flatten\u1.$0\a_reg[0:0] ),
    .E(1'h1),
    .Q(\u2.a_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$249$auto$blifparse.cc:362:parse_blif$251  (
    .C(\$auto$clkbufmap.cc:295:execute$571 ),
    .D(\$abc$212$flatten\u1.$0\b_reg[0:0] ),
    .E(1'h1),
    .Q(\u2.b_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$249$auto$blifparse.cc:362:parse_blif$252  (
    .C(\$auto$clkbufmap.cc:295:execute$571 ),
    .D(\$abc$249$li2_li2 ),
    .E(1'h1),
    .Q(\$iopadmap$c2 ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h4)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$563  (
    .Y(\$abc$212$flatten\u1.$0\a_reg[0:0] ),
    .A({ \$iopadmap$a , \$iopadmap$reset  })
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h4)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$565  (
    .Y(\$abc$212$flatten\u1.$0\b_reg[0:0] ),
    .A({ \$iopadmap$b , \$iopadmap$reset  })
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h40)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$562  (
    .Y(\$abc$249$li2_li2 ),
    .A({ \u2.a_reg , \u2.b_reg , \$iopadmap$reset  })
  );
  (* keep = 32'h00000001 *)
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$and2x2.b  (
    .O(\$iopadmap$b ),
    .EN(1'h1),
    .I(b)
  );
  assign \u1.c  = \$iopadmap$c1 ;
  assign \u2.c  = \$iopadmap$c2 ;
  assign \$auto$clkbufmap.cc:263:execute$567  = \$iopadmap$clk1 ;
  assign \$auto$clkbufmap.cc:263:execute$570  = \$iopadmap$clk2 ;
endmodule
