/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module fabric_and2x2(\$iopadmap$c2 , \$iopadmap$b , \$auto$clkbufmap.cc:295:execute$568 , \$auto$clkbufmap.cc:295:execute$571 , \$iopadmap$reset , \$iopadmap$c1 , \$iopadmap$a );
  input \$iopadmap$b ;
  output \$iopadmap$c1 ;
  output \$iopadmap$c2 ;
  input \$iopadmap$reset ;
  input \$iopadmap$a ;
  input \$auto$clkbufmap.cc:295:execute$568 ;
  input \$auto$clkbufmap.cc:295:execute$571 ;
  wire \$iopadmap$b ;
  (* init = 1'h0 *)
  (* init = 1'h0 *)
  wire \$iopadmap$c1 ;
  (* init = 1'h0 *)
  (* init = 1'h0 *)
  wire \$iopadmap$c2 ;
  wire \$iopadmap$clk1 ;
  wire \$iopadmap$clk2 ;
  wire \$iopadmap$reset ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap572$auto$clkbufmap.cc:262:execute$569.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap572$auto$clkbufmap.cc:262:execute$569.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap573$auto$clkbufmap.cc:262:execute$566.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap573$auto$clkbufmap.cc:262:execute$566.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap574$iopadmap$and2x2.a.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap574$iopadmap$and2x2.a.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap574$iopadmap$and2x2.a.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap575$iopadmap$and2x2.clk2.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap575$iopadmap$and2x2.clk2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap575$iopadmap$and2x2.clk2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap576$iopadmap$and2x2.c1.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap576$iopadmap$and2x2.c1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap576$iopadmap$and2x2.c1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap577$iopadmap$and2x2.c2.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap577$iopadmap$and2x2.c2.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap577$iopadmap$and2x2.c2.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap578$iopadmap$and2x2.clk1.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap578$iopadmap$and2x2.clk1.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap578$iopadmap$and2x2.clk1.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap579$iopadmap$and2x2.reset.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap579$iopadmap$and2x2.reset.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap579$iopadmap$and2x2.reset.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap580$iopadmap$and2x2.b.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap580$iopadmap$and2x2.b.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap580$iopadmap$and2x2.b.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] \$techmap581$abc$561$auto$blifparse.cc:515:parse_blif$565.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap581$abc$561$auto$blifparse.cc:515:parse_blif$565.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] \$techmap582$abc$561$auto$blifparse.cc:515:parse_blif$563.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap582$abc$561$auto$blifparse.cc:515:parse_blif$563.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [2:0] \$techmap583$abc$561$auto$blifparse.cc:515:parse_blif$562.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap583$abc$561$auto$blifparse.cc:515:parse_blif$562.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [2:0] \$techmap584$abc$561$auto$blifparse.cc:515:parse_blif$564.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap584$abc$561$auto$blifparse.cc:515:parse_blif$564.Y ;
  wire \$iopadmap$a ;
  wire \$abc$249$li2_li2 ;
  wire \$auto$clkbufmap.cc:295:execute$568 ;
  wire \$auto$clkbufmap.cc:295:execute$571 ;
  wire \$abc$236$li2_li2 ;
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:18.3-27.8" *)
  wire \$abc$212$flatten\u1.$0\b_reg[0:0] ;
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:18.3-27.8" *)
  wire \$abc$212$flatten\u1.$0\a_reg[0:0] ;
  (* hdlname = "u1 a_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:16.7-16.12" *)
  wire \u1.a_reg ;
  (* hdlname = "u1 b_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:16.14-16.19" *)
  wire \u1.b_reg ;
  (* hdlname = "u1 c" *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:42.9-42.34|./Src/and2x2.v:13.14-13.15" *)
  wire \u1.c ;
  (* hdlname = "u2 a_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:43.9-43.34|./Src/and2x2.v:16.7-16.12" *)
  wire \u2.a_reg ;
  (* hdlname = "u2 b_reg" *)
  (* init = 1'h0 *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:43.9-43.34|./Src/and2x2.v:16.14-16.19" *)
  wire \u2.b_reg ;
  (* hdlname = "u2 c" *)
  (* keep = 32'h00000001 *)
  (* src = "./Src/and2x2.v:43.9-43.34|./Src/and2x2.v:13.14-13.15" *)
  wire \u2.c ;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h4)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$565  (
    .A({ \$iopadmap$b , \$iopadmap$reset  }),
    .Y(\$abc$212$flatten\u1.$0\b_reg[0:0] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$236$auto$blifparse.cc:362:parse_blif$237  (
    .C(\$auto$clkbufmap.cc:295:execute$568 ),
    .D(\$abc$212$flatten\u1.$0\a_reg[0:0] ),
    .E(1'h1),
    .Q(\u1.a_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$236$auto$blifparse.cc:362:parse_blif$238  (
    .C(\$auto$clkbufmap.cc:295:execute$568 ),
    .D(\$abc$212$flatten\u1.$0\b_reg[0:0] ),
    .E(1'h1),
    .Q(\u1.b_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$236$auto$blifparse.cc:362:parse_blif$239  (
    .C(\$auto$clkbufmap.cc:295:execute$568 ),
    .D(\$abc$236$li2_li2 ),
    .E(1'h1),
    .Q(\$iopadmap$c1 ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$249$auto$blifparse.cc:362:parse_blif$250  (
    .C(\$auto$clkbufmap.cc:295:execute$571 ),
    .D(\$abc$212$flatten\u1.$0\a_reg[0:0] ),
    .E(1'h1),
    .Q(\u2.a_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$249$auto$blifparse.cc:362:parse_blif$251  (
    .C(\$auto$clkbufmap.cc:295:execute$571 ),
    .D(\$abc$212$flatten\u1.$0\b_reg[0:0] ),
    .E(1'h1),
    .Q(\u2.b_reg ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$249$auto$blifparse.cc:362:parse_blif$252  (
    .C(\$auto$clkbufmap.cc:295:execute$571 ),
    .D(\$abc$249$li2_li2 ),
    .E(1'h1),
    .Q(\$iopadmap$c2 ),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h40)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$562  (
    .A({ \u2.a_reg , \u2.b_reg , \$iopadmap$reset  }),
    .Y(\$abc$249$li2_li2 )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h4)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$563  (
    .A({ \$iopadmap$a , \$iopadmap$reset  }),
    .Y(\$abc$212$flatten\u1.$0\a_reg[0:0] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:25.38-25.69" *)
  LUT3 #(
    .INIT_VALUE(8'h40)
  ) \$abc$561$auto$blifparse.cc:515:parse_blif$564  (
    .A({ \u1.a_reg , \u1.b_reg , \$iopadmap$reset  }),
    .Y(\$abc$236$li2_li2 )
  );
  assign \u1.c  = \$iopadmap$c1 ;
  assign \u2.c  = \$iopadmap$c2 ;
endmodule
