/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module and2x2(a, b, clk1, clk2, reset, c1, c2);
  input clk1;
  input clk2;
  input a;
  output c2;
  input reset;
  input b;
  output c1;
  (* keep = 32'd1 *)
  (* src = "./Src/and2x2.v:39.15-39.17" *)
  wire \$auto$rs_design_edit.cc:682:execute$586.c2 ;
  (* keep = 32'd1 *)
  (* src = "./Src/and2x2.v:38.15-38.17" *)
  wire \$auto$rs_design_edit.cc:682:execute$586.c1 ;
  (* src = "./Src/and2x2.v:36.9-36.13" *)
  wire \$auto$rs_design_edit.cc:682:execute$586.clk2 ;
  (* src = "./Src/and2x2.v:33.9-33.10" *)
  wire \$auto$rs_design_edit.cc:682:execute$586.a ;
  (* src = "./Src/and2x2.v:37.9-37.14" *)
  wire \$auto$rs_design_edit.cc:682:execute$586.reset ;
  (* src = "./Src/and2x2.v:35.9-35.13" *)
  wire \$auto$rs_design_edit.cc:682:execute$586.clk1 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:295:execute$568 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:295:execute$571 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$a ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$b ;
  (* init = 1'h0 *)
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$c1 ;
  (* init = 1'h0 *)
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$c2 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$clk1 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$clk2 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$reset ;
  (* src = "./Src/and2x2.v:34.9-34.10" *)
  wire \$auto$rs_design_edit.cc:682:execute$586.b ;
  (* src = "./Src/and2x2.v:35.9-35.13" *)
  (* src = "./Src/and2x2.v:35.9-35.13" *)
  wire clk1;
  (* src = "./Src/and2x2.v:36.9-36.13" *)
  (* src = "./Src/and2x2.v:36.9-36.13" *)
  wire clk2;
  (* init = 1'h0 *)
  wire \$iopadmap$c2 ;
  (* init = 1'h0 *)
  wire \$iopadmap$c1 ;
  wire \$iopadmap$b ;
  wire \$iopadmap$a ;
  wire \$auto$clkbufmap.cc:295:execute$571 ;
  wire \$auto$clkbufmap.cc:295:execute$568 ;
  wire \$iopadmap$reset ;
  (* src = "./Src/and2x2.v:33.9-33.10" *)
  (* src = "./Src/and2x2.v:33.9-33.10" *)
  wire a;
  (* keep = 32'd1 *)
  (* src = "./Src/and2x2.v:39.15-39.17" *)
  (* keep = 32'd1 *)
  (* src = "./Src/and2x2.v:39.15-39.17" *)
  wire c2;
  (* src = "./Src/and2x2.v:37.9-37.14" *)
  (* src = "./Src/and2x2.v:37.9-37.14" *)
  wire reset;
  (* src = "./Src/and2x2.v:34.9-34.10" *)
  (* src = "./Src/and2x2.v:34.9-34.10" *)
  wire b;
  (* keep = 32'd1 *)
  (* src = "./Src/and2x2.v:38.15-38.17" *)
  (* keep = 32'd1 *)
  (* src = "./Src/and2x2.v:38.15-38.17" *)
  wire c1;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:262:execute$566  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$clk1 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:295:execute$568 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:262:execute$569  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$clk2 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:295:execute$571 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$and2x2.a  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$586.a ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$a )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$and2x2.b  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$586.b ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$b )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$and2x2.c1  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$c1 ),
    .O(\$auto$rs_design_edit.cc:682:execute$586.c1 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$and2x2.c2  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$c2 ),
    .O(\$auto$rs_design_edit.cc:682:execute$586.c2 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$and2x2.clk1  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$586.clk1 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$clk1 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$and2x2.clk2  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$586.clk2 ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$clk2 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$and2x2.reset  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$586.reset ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$reset )
  );
  fabric_and2x2 \$auto$rs_design_edit.cc:680:execute$585  (
    .\$auto$clkbufmap.cc:295:execute$568 (\$auto$clkbufmap.cc:295:execute$568 ),
    .\$auto$clkbufmap.cc:295:execute$571 (\$auto$clkbufmap.cc:295:execute$571 ),
    .\$iopadmap$a (\$iopadmap$a ),
    .\$iopadmap$b (\$iopadmap$b ),
    .\$iopadmap$c1 (\$iopadmap$c1 ),
    .\$iopadmap$c2 (\$iopadmap$c2 ),
    .\$iopadmap$reset (\$iopadmap$reset )
  );
  assign \$auto$clkbufmap.cc:295:execute$568  = \$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:295:execute$568 ;
  assign \$auto$clkbufmap.cc:295:execute$571  = \$flatten$auto$rs_design_edit.cc:682:execute$586.$auto$clkbufmap.cc:295:execute$571 ;
  assign \$iopadmap$a  = \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$a ;
  assign \$iopadmap$b  = \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$b ;
  assign \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$c1  = \$iopadmap$c1 ;
  assign \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$c2  = \$iopadmap$c2 ;
  assign \$iopadmap$reset  = \$flatten$auto$rs_design_edit.cc:682:execute$586.$iopadmap$reset ;
  assign \$auto$rs_design_edit.cc:682:execute$586.a  = a;
  assign \$auto$rs_design_edit.cc:682:execute$586.b  = b;
  assign c1 = \$auto$rs_design_edit.cc:682:execute$586.c1 ;
  assign c2 = \$auto$rs_design_edit.cc:682:execute$586.c2 ;
  assign \$auto$rs_design_edit.cc:682:execute$586.clk1  = clk1;
  assign \$auto$rs_design_edit.cc:682:execute$586.clk2  = clk2;
  assign \$auto$rs_design_edit.cc:682:execute$586.reset  = reset;
endmodule
