/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module flop2flop2flop(din, dout, clk);
  output dout;
  input din;
  input clk;
  (* keep = 32'd1 *)
  (* src = "flop2flop2flop.v:15.12-15.16" *)
  (* keep = 32'd1 *)
  (* src = "flop2flop2flop.v:15.12-15.16" *)
  wire dout;
  (* src = "flop2flop2flop.v:13.7-13.10" *)
  (* src = "flop2flop2flop.v:13.7-13.10" *)
  wire din;
  (* src = "flop2flop2flop.v:14.7-14.10" *)
  (* src = "flop2flop2flop.v:14.7-14.10" *)
  wire clk;
  wire \$auto$clkbufmap.cc:294:execute$446 ;
  wire \$iopadmap$clk ;
  wire \$iopadmap$dout ;
  wire \$auto$clkbufmap.cc:262:execute$445 ;
  wire \$iopadmap$din ;
  fabric_flop2flop2flop \$auto$rs_design_edit.cc:578:execute$451  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .\$auto$clkbufmap.cc:294:execute$446 (\$auto$clkbufmap.cc:294:execute$446 ),
    .\$iopadmap$din (\$iopadmap$din ),
    .\$auto$clkbufmap.cc:262:execute$445 (\$auto$clkbufmap.cc:262:execute$445 ),
    .\$iopadmap$dout (\$iopadmap$dout )
  );
  interface_flop2flop2flop \$auto$rs_design_edit.cc:580:execute$452  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .clk(clk),
    .din(din),
    .dout(dout),
    .\$auto$clkbufmap.cc:294:execute$446 (\$auto$clkbufmap.cc:294:execute$446 ),
    .\$iopadmap$din (\$iopadmap$din ),
    .\$auto$clkbufmap.cc:262:execute$445 (\$auto$clkbufmap.cc:262:execute$445 ),
    .\$iopadmap$dout (\$iopadmap$dout )
  );
endmodule

module interface_flop2flop2flop(din, dout, clk, \$auto$clkbufmap.cc:262:execute$445 , \$auto$clkbufmap.cc:294:execute$446 , \$iopadmap$din , \$iopadmap$clk , \$iopadmap$dout );
  output dout;
  input \$iopadmap$dout ;
  input clk;
  input din;
  output \$iopadmap$din ;
  output \$auto$clkbufmap.cc:294:execute$446 ;
  input \$auto$clkbufmap.cc:262:execute$445 ;
  output \$iopadmap$clk ;
  (* keep = 32'd1 *)
  (* src = "flop2flop2flop.v:15.12-15.16" *)
  (* keep = 32'd1 *)
  (* src = "flop2flop2flop.v:15.12-15.16" *)
  wire dout;
  wire \$iopadmap$dout ;
  (* src = "flop2flop2flop.v:14.7-14.10" *)
  (* src = "flop2flop2flop.v:14.7-14.10" *)
  wire clk;
  (* src = "flop2flop2flop.v:13.7-13.10" *)
  (* src = "flop2flop2flop.v:13.7-13.10" *)
  wire din;
  wire \$iopadmap$din ;
  wire \$auto$clkbufmap.cc:294:execute$446 ;
  wire \$auto$clkbufmap.cc:262:execute$445 ;
  wire \$iopadmap$clk ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$flop2flop2flop.din  (
    .O(\$iopadmap$din ),
    .EN(1'h1),
    .I(din)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$flop2flop2flop.clk  (
    .O(\$iopadmap$clk ),
    .EN(1'h1),
    .I(clk)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$flop2flop2flop.dout  (
    .O(dout),
    .I(\$iopadmap$dout )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:261:execute$444  (
    .O(\$auto$clkbufmap.cc:294:execute$446 ),
    .I(\$auto$clkbufmap.cc:262:execute$445 )
  );
endmodule
