/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module flop2flop2flop(din, dout, clk);
  input clk;
  input din;
  output dout;
  (* src = "flop2flop2flop.v:14.7-14.10" *)
  (* src = "flop2flop2flop.v:14.7-14.10" *)
  wire clk;
  (* src = "flop2flop2flop.v:13.7-13.10" *)
  (* src = "flop2flop2flop.v:13.7-13.10" *)
  wire din;
  (* keep = 32'd1 *)
  (* src = "flop2flop2flop.v:15.12-15.16" *)
  (* keep = 32'd1 *)
  (* src = "flop2flop2flop.v:15.12-15.16" *)
  wire dout;
  fabric_flop2flop2flop \$auto$rs_design_edit.cc:561:execute$444  (
    .clk(clk),
    .din(din),
    .dout(dout)
  );
  interface_flop2flop2flop \$auto$rs_design_edit.cc:563:execute$445  (
  );
endmodule

module interface_flop2flop2flop();
endmodule
