/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module tristate(din, oe, tristate_out, clk);
  input clk;
  input din;
  input oe;
  output tristate_out;
  (* src = "/home/manadher/work/Feb24/yosys_rs29/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] _0_;
  (* src = "/home/manadher/work/Feb24/yosys_rs29/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire _1_;
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:15.10-15.13" *)
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:15.10-15.13" *)
  wire clk;
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:14.10-14.13" *)
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:14.10-14.13" *)
  wire din;
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:16.10-16.12" *)
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:16.10-16.12" *)
  wire oe;
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:19.8-19.10" *)
  wire q1;
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:20.8-20.10" *)
  wire q2;
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:17.11-17.23" *)
  (* keep = 32'h00000001 *)
  (* src = "tristate.v:17.11-17.23" *)
  wire tristate_out;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/manadher/work/Feb24/yosys_rs29/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) _2_ (
    .Y(tristate_out),
    .A({ q2, oe })
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/manadher/work/Feb24/yosys_rs29/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE _3_ (
    .C(clk),
    .D(q1),
    .E(1'h1),
    .Q(q2),
    .R(1'h1)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/manadher/work/Feb24/yosys_rs29/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE _4_ (
    .C(clk),
    .D(din),
    .E(1'h1),
    .Q(q1),
    .R(1'h1)
  );
endmodule
