/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module tristate(din, oe, tristate_out, clk);
  output tristate_out;
  input oe;
  input clk;
  input din;
  (* keep = 32'd1 *)
  (* src = "tristate.v:17.11-17.23" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:17.11-17.23" *)
  wire tristate_out;
  (* keep = 32'd1 *)
  (* src = "tristate.v:16.10-16.12" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:16.10-16.12" *)
  wire oe;
  (* keep = 32'd1 *)
  (* src = "tristate.v:15.10-15.13" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:15.10-15.13" *)
  wire clk;
  (* keep = 32'd1 *)
  (* src = "tristate.v:14.10-14.13" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:14.10-14.13" *)
  wire din;
  fabric_tristate \$auto$rs_design_edit.cc:559:execute$444  (
    .clk(clk),
    .din(din),
    .oe(oe),
    .tristate_out(tristate_out)
  );
  interface_tristate \$auto$rs_design_edit.cc:561:execute$445  (
  );
endmodule

module interface_tristate();
endmodule
