/* Generated by Yosys 0.18+10 (git sha1 07c42e625, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module tristate(din, oe, tristate_out, clk);
  input din;
  input oe;
  input clk;
  output tristate_out;
  wire \$iopadmap$tristate_out ;
  (* keep = 32'd1 *)
  (* src = "tristate.v:14.10-14.13" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:14.10-14.13" *)
  wire din;
  (* keep = 32'd1 *)
  (* src = "tristate.v:16.10-16.12" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:16.10-16.12" *)
  wire oe;
  wire \$auto$clkbufmap.cc:262:execute$444 ;
  wire \$iopadmap$oe ;
  wire \$iopadmap$clk ;
  wire \$iopadmap$din ;
  wire \$auto$clkbufmap.cc:294:execute$445 ;
  (* keep = 32'd1 *)
  (* src = "tristate.v:15.10-15.13" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:15.10-15.13" *)
  wire clk;
  (* keep = 32'd1 *)
  (* src = "tristate.v:17.11-17.23" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:17.11-17.23" *)
  wire tristate_out;
  fabric_tristate \$auto$rs_design_edit.cc:578:execute$452  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .\$auto$clkbufmap.cc:294:execute$445 (\$auto$clkbufmap.cc:294:execute$445 ),
    .\$iopadmap$din (\$iopadmap$din ),
    .\$auto$clkbufmap.cc:262:execute$444 (\$auto$clkbufmap.cc:262:execute$444 ),
    .\$iopadmap$oe (\$iopadmap$oe ),
    .\$iopadmap$tristate_out (\$iopadmap$tristate_out )
  );
  interface_tristate \$auto$rs_design_edit.cc:580:execute$453  (
    .\$iopadmap$clk (\$iopadmap$clk ),
    .clk(clk),
    .din(din),
    .oe(oe),
    .tristate_out(tristate_out),
    .\$auto$clkbufmap.cc:294:execute$445 (\$auto$clkbufmap.cc:294:execute$445 ),
    .\$iopadmap$din (\$iopadmap$din ),
    .\$auto$clkbufmap.cc:262:execute$444 (\$auto$clkbufmap.cc:262:execute$444 ),
    .\$iopadmap$oe (\$iopadmap$oe ),
    .\$iopadmap$tristate_out (\$iopadmap$tristate_out )
  );
endmodule

module interface_tristate(din, oe, tristate_out, clk, \$auto$clkbufmap.cc:262:execute$444 , \$iopadmap$oe , \$iopadmap$clk , \$iopadmap$din , \$iopadmap$tristate_out , \$auto$clkbufmap.cc:294:execute$445 );
  output \$iopadmap$clk ;
  input din;
  input \$auto$clkbufmap.cc:262:execute$444 ;
  input \$iopadmap$tristate_out ;
  output \$iopadmap$oe ;
  output \$auto$clkbufmap.cc:294:execute$445 ;
  input clk;
  output tristate_out;
  output \$iopadmap$din ;
  input oe;
  wire \$iopadmap$clk ;
  (* keep = 32'd1 *)
  (* src = "tristate.v:14.10-14.13" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:14.10-14.13" *)
  wire din;
  wire \$auto$clkbufmap.cc:262:execute$444 ;
  wire \$iopadmap$tristate_out ;
  wire \$iopadmap$oe ;
  wire \$auto$clkbufmap.cc:294:execute$445 ;
  (* keep = 32'd1 *)
  (* src = "tristate.v:15.10-15.13" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:15.10-15.13" *)
  wire clk;
  (* keep = 32'd1 *)
  (* src = "tristate.v:17.11-17.23" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:17.11-17.23" *)
  wire tristate_out;
  wire \$iopadmap$din ;
  (* keep = 32'd1 *)
  (* src = "tristate.v:16.10-16.12" *)
  (* keep = 32'd1 *)
  (* src = "tristate.v:16.10-16.12" *)
  wire oe;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$tristate.din  (
    .O(\$iopadmap$din ),
    .EN(1'h1),
    .I(din)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$tristate.clk  (
    .O(\$iopadmap$clk ),
    .EN(1'h1),
    .I(clk)
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$iopadmap$tristate.tristate_out  (
    .O(tristate_out),
    .I(\$iopadmap$tristate_out )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$iopadmap$tristate.oe  (
    .O(\$iopadmap$oe ),
    .EN(1'h1),
    .I(oe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$auto$clkbufmap.cc:261:execute$443  (
    .O(\$auto$clkbufmap.cc:294:execute$445 ),
    .I(\$auto$clkbufmap.cc:262:execute$444 )
  );
endmodule
