/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module ft(din, dout);
  input din;
  output dout;
  (* keep = 32'd1 *)
  (* src = "ft.v:10.9-10.12" *)
  (* keep = 32'd1 *)
  (* src = "ft.v:10.9-10.12" *)
  wire din;
  (* keep = 32'd1 *)
  (* src = "ft.v:11.10-11.14" *)
  (* keep = 32'd1 *)
  (* src = "ft.v:11.10-11.14" *)
  wire dout;
  fabric_ft \$auto$rs_design_edit.cc:559:execute$392  (
    .din(din),
    .dout(dout)
  );
  interface_ft \$auto$rs_design_edit.cc:561:execute$393  (
  );
endmodule

module interface_ft();
endmodule
