/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module primitive_example_design_6(clk, in, rst, q_p, q_n, oddr_en, ibuf_oe1, ibuf_oe2, ibuf_oe3, ibuf_oe4);
  input clk;
  input ibuf_oe1;
  input ibuf_oe2;
  input ibuf_oe3;
  input ibuf_oe4;
  input [1:0] in;
  input oddr_en;
  output q_n;
  output q_p;
  input rst;
  (* src = "./rtl/primitive_example_design_6.v:4.7-4.10" *)
  (* src = "./rtl/primitive_example_design_6.v:4.7-4.10" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_6.v:15.46-15.57" *)
  wire clk_buf_out;
  wire dffre_out;
  (* src = "./rtl/primitive_example_design_6.v:12.12-12.21" *)
  wire [1:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_6.v:5.7-5.15" *)
  (* src = "./rtl/primitive_example_design_6.v:5.7-5.15" *)
  wire ibuf_oe1;
  (* src = "./rtl/primitive_example_design_6.v:5.16-5.24" *)
  (* src = "./rtl/primitive_example_design_6.v:5.16-5.24" *)
  wire ibuf_oe2;
  (* src = "./rtl/primitive_example_design_6.v:5.25-5.33" *)
  (* src = "./rtl/primitive_example_design_6.v:5.25-5.33" *)
  wire ibuf_oe3;
  (* src = "./rtl/primitive_example_design_6.v:5.34-5.42" *)
  (* src = "./rtl/primitive_example_design_6.v:5.34-5.42" *)
  wire ibuf_oe4;
  (* src = "./rtl/primitive_example_design_6.v:3.13-3.15" *)
  (* src = "./rtl/primitive_example_design_6.v:3.13-3.15" *)
  wire [1:0] in;
  (* src = "./rtl/primitive_example_design_6.v:6.7-6.14" *)
  (* src = "./rtl/primitive_example_design_6.v:6.7-6.14" *)
  wire oddr_en;
  wire oddr_out;
  (* src = "./rtl/primitive_example_design_6.v:8.8-8.11" *)
  (* src = "./rtl/primitive_example_design_6.v:8.8-8.11" *)
  wire q_n;
  (* src = "./rtl/primitive_example_design_6.v:7.8-7.11" *)
  (* src = "./rtl/primitive_example_design_6.v:7.8-7.11" *)
  wire q_p;
  (* src = "./rtl/primitive_example_design_6.v:4.12-4.15" *)
  (* src = "./rtl/primitive_example_design_6.v:4.12-4.15" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  wire rst_i_buf_out;
  fabric_primitive_example_design_6 \$auto$rs_design_edit.cc:559:execute$398  (
    .dffre_out(dffre_out),
    .oddr_out(oddr_out),
    .rst_i_buf_out(rst_i_buf_out)
  );
  interface_primitive_example_design_6 \$auto$rs_design_edit.cc:561:execute$399  (
    .clk(clk),
    .dffre_out(dffre_out),
    .ibuf_oe1(ibuf_oe1),
    .ibuf_oe2(ibuf_oe2),
    .ibuf_oe3(ibuf_oe3),
    .ibuf_oe4(ibuf_oe4),
    .in(in),
    .oddr_en(oddr_en),
    .oddr_out(oddr_out),
    .q_n(q_n),
    .q_p(q_p),
    .rst(rst),
    .rst_i_buf_out(rst_i_buf_out)
  );
endmodule

module interface_primitive_example_design_6(clk, in, rst, q_p, q_n, oddr_en, ibuf_oe1, ibuf_oe2, ibuf_oe3, ibuf_oe4, oddr_out, dffre_out, rst_i_buf_out);
  input clk;
  input dffre_out;
  input ibuf_oe1;
  input ibuf_oe2;
  input ibuf_oe3;
  input ibuf_oe4;
  input [1:0] in;
  input oddr_en;
  output oddr_out;
  output q_n;
  output q_p;
  input rst;
  output rst_i_buf_out;
  (* src = "./rtl/primitive_example_design_6.v:4.7-4.10" *)
  (* src = "./rtl/primitive_example_design_6.v:4.7-4.10" *)
  wire clk;
  (* src = "./rtl/primitive_example_design_6.v:15.46-15.57" *)
  wire clk_buf_out;
  wire dffre_out;
  (* src = "./rtl/primitive_example_design_6.v:12.12-12.21" *)
  wire [1:0] i_buf_out;
  (* src = "./rtl/primitive_example_design_6.v:5.7-5.15" *)
  (* src = "./rtl/primitive_example_design_6.v:5.7-5.15" *)
  wire ibuf_oe1;
  (* src = "./rtl/primitive_example_design_6.v:5.16-5.24" *)
  (* src = "./rtl/primitive_example_design_6.v:5.16-5.24" *)
  wire ibuf_oe2;
  (* src = "./rtl/primitive_example_design_6.v:5.25-5.33" *)
  (* src = "./rtl/primitive_example_design_6.v:5.25-5.33" *)
  wire ibuf_oe3;
  (* src = "./rtl/primitive_example_design_6.v:5.34-5.42" *)
  (* src = "./rtl/primitive_example_design_6.v:5.34-5.42" *)
  wire ibuf_oe4;
  (* src = "./rtl/primitive_example_design_6.v:3.13-3.15" *)
  (* src = "./rtl/primitive_example_design_6.v:3.13-3.15" *)
  wire [1:0] in;
  (* src = "./rtl/primitive_example_design_6.v:6.7-6.14" *)
  (* src = "./rtl/primitive_example_design_6.v:6.7-6.14" *)
  wire oddr_en;
  wire oddr_out;
  (* src = "./rtl/primitive_example_design_6.v:8.8-8.11" *)
  (* src = "./rtl/primitive_example_design_6.v:8.8-8.11" *)
  wire q_n;
  (* src = "./rtl/primitive_example_design_6.v:7.8-7.11" *)
  (* src = "./rtl/primitive_example_design_6.v:7.8-7.11" *)
  wire q_p;
  (* src = "./rtl/primitive_example_design_6.v:4.12-4.15" *)
  (* src = "./rtl/primitive_example_design_6.v:4.12-4.15" *)
  wire rst;
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  (* src = "./rtl/primitive_example_design_6.v:13.6-13.19" *)
  wire rst_i_buf_out;
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:15.7-15.59" *)
  I_BUF clk_buf_inst (
    .EN(ibuf_oe1),
    .I(clk),
    .O(clk_buf_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:19.11-19.69" *)
  O_BUFT_DS o_buft_inst1 (
    .I(in[0]),
    .O_N(q_n),
    .O_P(q_p),
    .T(dffre_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:21.7-21.60" *)
  I_BUF ibuf_inst1 (
    .EN(ibuf_oe2),
    .I(in[0]),
    .O(i_buf_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:22.7-22.60" *)
  I_BUF ibuf_inst2 (
    .EN(ibuf_oe3),
    .I(in[1]),
    .O(i_buf_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:23.7-23.59" *)
  I_BUF ibuf_inst4 (
    .EN(ibuf_oe4),
    .I(rst),
    .O(rst_i_buf_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/primitive_example_design_6.v:17.7-17.81" *)
  O_DDR iddr_ist1 (
    .C(clk_buf_out),
    .D(i_buf_out),
    .E(oddr_en),
    .Q(oddr_out),
    .R(rst)
  );
endmodule
