/* Generated by Yosys 0.44 (git sha1 86a09ee26, g++ 11.2.1 -fPIC -O3) */

module GJC21(data_i_buf, reset_n_buf, enable_buf, clk_i_buf, dly_inc_pulse_inv_buf, data_o);
  input clk_i_buf;
  input [1:0] data_i_buf;
  output data_o;
  input dly_inc_pulse_inv_buf;
  input enable_buf;
  input reset_n_buf;
  wire \$abc$237$auto_52 ;
  wire \$abc$249$li0_li0 ;
  wire \$abc$249$li1_li1 ;
  wire \$abc$249$li2_li2 ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:22.10-22.17" *)
  wire \$f2g_trx_dly_adj_dly_adj ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:22.10-22.17" *)
  wire \$f2g_trx_dly_inc_dly_adj ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:21.9-21.15" *)
  wire \$f2g_trx_dly_ld_dly_ld ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:23.10-23.17" *)
  wire \$f2g_trx_reset_n_reset_n ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:19.15-19.23" *)
  wire \$f2g_tx_out_data_reg[0] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:19.15-19.23" *)
  wire \$f2g_tx_out_data_reg[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:24.10-24.16" *)
  wire \$ofab_enable ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:25.16-25.25" *)
  wire clk_buf_i;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:25.10-25.15" *)
  wire clk_i;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:14.18-14.27" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:14.18-14.27" *)
  wire clk_i_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:27.17-27.23" *)
  wire \data_i[0] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:27.17-27.23" *)
  wire \data_i[1] ;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:11.24-11.34" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:11.24-11.34" *)
  wire [1:0] data_i_buf;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:16.18-16.24" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:16.18-16.24" *)
  wire data_o;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:20.10-20.20" *)
  wire data_o_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:20.22-20.36" *)
  wire data_o_delayed;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:19.15-19.23" *)
  wire \data_reg[0] ;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:19.15-19.23" *)
  wire \data_reg[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:22.10-22.17" *)
  wire dly_adj;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:26.10-26.27" *)
  wire dly_inc_pulse_inv;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:15.18-15.39" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:15.18-15.39" *)
  wire dly_inc_pulse_inv_buf;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:21.9-21.15" *)
  wire dly_ld;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:24.10-24.16" *)
  wire enable;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:13.18-13.28" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:13.18-13.28" *)
  wire enable_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:23.10-23.17" *)
  wire reset_n;
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:12.18-12.29" *)
  (* keep = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:12.18-12.29" *)
  wire reset_n_buf;
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$249$auto_250  (
    .C(clk_i),
    .D(\$abc$249$li0_li0 ),
    .E(\$abc$237$auto_52 ),
    .Q(\data_reg[0] ),
    .R(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$249$auto_251  (
    .C(clk_i),
    .D(\$abc$249$li1_li1 ),
    .E(\$abc$237$auto_52 ),
    .Q(\data_reg[1] ),
    .R(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:80.11-80.65" *)
  DFFRE \$abc$249$auto_252  (
    .C(clk_i),
    .D(\$abc$249$li2_li2 ),
    .E(\$abc$237$auto_52 ),
    .Q(dly_ld),
    .R(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) \$abc$595$auto_596  (
    .A({ \data_i[1] , reset_n }),
    .Y(\$abc$249$li1_li1 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) \$abc$595$auto_597  (
    .A({ \data_i[0] , reset_n }),
    .Y(\$abc$249$li0_li0 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'hb)
  ) \$abc$595$auto_598  (
    .A({ reset_n, enable }),
    .Y(\$abc$237$auto_52 )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$595$auto_599  (
    .A(dly_inc_pulse_inv),
    .Y(dly_adj)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/10_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$595$auto_600  (
    .A(reset_n),
    .Y(\$abc$249$li2_li2 )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_dly_adj_dly_adj_1  (
    .I(dly_adj),
    .O(\$f2g_trx_dly_adj_dly_adj )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_dly_inc_dly_adj_1  (
    .I(dly_adj),
    .O(\$f2g_trx_dly_inc_dly_adj )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_dly_ld_dly_ld_1  (
    .I(dly_ld),
    .O(\$f2g_trx_dly_ld_dly_ld )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_trx_reset_n_reset_n_1  (
    .I(reset_n),
    .O(\$f2g_trx_reset_n_reset_n )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_reg[0]_1  (
    .I(\data_reg[0] ),
    .O(\$f2g_tx_out_data_reg[0] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$f2g_tx_out_data_reg[1]_1  (
    .I(\data_reg[1] ),
    .O(\$f2g_tx_out_data_reg[1] )
  );
  (* keep = 32'sh00000001 *)
  O_FAB \$ofab_enable_1  (
    .I(enable),
    .O(\$ofab_enable )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:30.39-30.73" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf0_ (
    .EN(1'h1),
    .I(reset_n_buf),
    .O(reset_n)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:31.39-31.71" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf1_ (
    .EN(1'h1),
    .I(enable_buf),
    .O(enable)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:32.39-32.73" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf2_ (
    .EN(1'h1),
    .I(clk_i_buf),
    .O(clk_buf_i)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:33.39-33.93" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf3_ (
    .EN(1'h1),
    .I(dly_inc_pulse_inv_buf),
    .O(dly_inc_pulse_inv)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:34.39-34.77" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf4_ (
    .EN(1'h1),
    .I(data_i_buf[0]),
    .O(\data_i[0] )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:35.39-35.77" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf5_ (
    .EN(1'h1),
    .I(data_i_buf[1]),
    .O(\data_i[1] )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:39.13-39.43" *)
  CLK_BUF clock_buffer (
    .I(clk_buf_i),
    .O(clk_i)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:51.11-51.68" *)
  O_DDR data_o_ddr (
    .C(clk_i),
    .D({ \$f2g_tx_out_data_reg[1] , \$f2g_tx_out_data_reg[0]  }),
    .E(\$ofab_enable ),
    .Q(data_o_delayed),
    .R(\$f2g_trx_reset_n_reset_n )
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:45.13-50.44" *)
  O_DELAY #(
    .DELAY(32'sh00000000)
  ) data_o_delay (
    .CLK_IN(clk_i),
    .DLY_ADJ(\$f2g_trx_dly_adj_dly_adj ),
    .DLY_INCDEC(\$f2g_trx_dly_inc_dly_adj ),
    .DLY_LOAD(\$f2g_trx_dly_ld_dly_ld ),
    .I(data_o_delayed),
    .O(data_o_buf)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC21/results_dir/.././rtl/GJC21.v:44.11-44.38" *)
  O_BUFT ddr_buf (
    .I(data_o_buf),
    .O(data_o),
    .T(1'h1)
  );
endmodule
