/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.1.0-1ubuntu1~20.04 -fPIC -Os) */

module ft(din, dout);
  input din;
  output dout;
  (* keep = 32'h00000001 *)
  (* src = "ft.v:10.9-10.12" *)
  (* keep = 32'h00000001 *)
  (* src = "ft.v:10.9-10.12" *)
  wire din;
  (* keep = 32'h00000001 *)
  (* src = "ft.v:11.10-11.14" *)
  (* keep = 32'h00000001 *)
  (* src = "ft.v:11.10-11.14" *)
  wire dout;
  assign dout = din;
endmodule
