/* Generated by Yosys 0.38 (git sha1 6c475f1f1, gcc 11.2.1 -fPIC -Os) */

module GJC19(clk_i_buf, data_i, dly_incdec_buf, dly_ld_buf, dly_adj_buf, data_o_inv_delayed_buf, dly_tap_val_inv_buf);
  input clk_i_buf;
  input data_i;
  output data_o_inv_delayed_buf;
  input dly_adj_buf;
  input dly_incdec_buf;
  input dly_ld_buf;
  output [5:0] dly_tap_val_inv_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:21.26-21.37" *)
  wire \$f2g_trx_dly_adj_dly_adj_inv ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:21.10-21.24" *)
  wire \$f2g_trx_dly_inc_dly_incdec_inv ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:21.39-21.49" *)
  wire \$f2g_trx_dly_ld_dly_ld_inv ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \$ifab_dly_tap_val[0] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \$ifab_dly_tap_val[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \$ifab_dly_tap_val[2] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \$ifab_dly_tap_val[3] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \$ifab_dly_tap_val[4] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \$ifab_dly_tap_val[5] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:24.10-24.19" *)
  wire clk_buf_i;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:25.10-25.15" *)
  wire clk_i;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:10.16-10.25" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:10.16-10.25" *)
  wire clk_i_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:11.16-11.22" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:11.16-11.22" *)
  wire data_i;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:23.10-23.20" *)
  wire data_i_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:19.10-19.16" *)
  wire data_o;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:30.10-30.28" *)
  wire data_o_inv_delayed;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:15.17-15.39" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:15.17-15.39" *)
  wire data_o_inv_delayed_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:28.10-28.17" *)
  wire dly_adj;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:14.16-14.27" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:14.16-14.27" *)
  wire dly_adj_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:21.26-21.37" *)
  wire dly_adj_inv;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:26.10-26.20" *)
  wire dly_incdec;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:12.16-12.30" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:12.16-12.30" *)
  wire dly_incdec_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:21.10-21.24" *)
  wire dly_incdec_inv;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:27.10-27.16" *)
  wire dly_ld;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:13.16-13.26" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:13.16-13.26" *)
  wire dly_ld_buf;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:21.39-21.49" *)
  wire dly_ld_inv;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \dly_tap_val[0] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \dly_tap_val[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \dly_tap_val[2] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \dly_tap_val[3] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \dly_tap_val[4] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:20.16-20.27" *)
  wire \dly_tap_val[5] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:31.16-31.31" *)
  wire \dly_tap_val_inv[0] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:31.16-31.31" *)
  wire \dly_tap_val_inv[1] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:31.16-31.31" *)
  wire \dly_tap_val_inv[2] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:31.16-31.31" *)
  wire \dly_tap_val_inv[3] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:31.16-31.31" *)
  wire \dly_tap_val_inv[4] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:31.16-31.31" *)
  wire \dly_tap_val_inv[5] ;
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:16.23-16.42" *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:16.23-16.42" *)
  wire [5:0] dly_tap_val_inv_buf;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_481  (
    .A(data_o),
    .Y(data_o_inv_delayed)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_482  (
    .A(dly_incdec),
    .Y(dly_incdec_inv)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_483  (
    .A(dly_adj),
    .Y(dly_adj_inv)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_484  (
    .A(dly_ld),
    .Y(dly_ld_inv)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_485  (
    .A(\dly_tap_val[5] ),
    .Y(\dly_tap_val_inv[5] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_486  (
    .A(\dly_tap_val[4] ),
    .Y(\dly_tap_val_inv[4] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_487  (
    .A(\dly_tap_val[3] ),
    .Y(\dly_tap_val_inv[3] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_488  (
    .A(\dly_tap_val[2] ),
    .Y(\dly_tap_val_inv[2] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_489  (
    .A(\dly_tap_val[1] ),
    .Y(\dly_tap_val_inv[1] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$480$auto_490  (
    .A(\dly_tap_val[0] ),
    .Y(\dly_tap_val_inv[0] )
  );
  (* keep = 32'h00000001 *)
  O_FAB \$f2g_trx_dly_adj_dly_adj_inv_1  (
    .I(dly_adj_inv),
    .O(\$f2g_trx_dly_adj_dly_adj_inv )
  );
  (* keep = 32'h00000001 *)
  O_FAB \$f2g_trx_dly_inc_dly_incdec_inv_1  (
    .I(dly_incdec_inv),
    .O(\$f2g_trx_dly_inc_dly_incdec_inv )
  );
  (* keep = 32'h00000001 *)
  O_FAB \$f2g_trx_dly_ld_dly_ld_inv_1  (
    .I(dly_ld_inv),
    .O(\$f2g_trx_dly_ld_dly_ld_inv )
  );
  (* keep = 32'h00000001 *)
  I_FAB \$ifab_dly_tap_val[0]_1  (
    .I(\$ifab_dly_tap_val[0] ),
    .O(\dly_tap_val[0] )
  );
  (* keep = 32'h00000001 *)
  I_FAB \$ifab_dly_tap_val[1]_1  (
    .I(\$ifab_dly_tap_val[1] ),
    .O(\dly_tap_val[1] )
  );
  (* keep = 32'h00000001 *)
  I_FAB \$ifab_dly_tap_val[2]_1  (
    .I(\$ifab_dly_tap_val[2] ),
    .O(\dly_tap_val[2] )
  );
  (* keep = 32'h00000001 *)
  I_FAB \$ifab_dly_tap_val[3]_1  (
    .I(\$ifab_dly_tap_val[3] ),
    .O(\dly_tap_val[3] )
  );
  (* keep = 32'h00000001 *)
  I_FAB \$ifab_dly_tap_val[4]_1  (
    .I(\$ifab_dly_tap_val[4] ),
    .O(\dly_tap_val[4] )
  );
  (* keep = 32'h00000001 *)
  I_FAB \$ifab_dly_tap_val[5]_1  (
    .I(\$ifab_dly_tap_val[5] ),
    .O(\dly_tap_val[5] )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:33.39-33.69" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf0_ (
    .EN(1'h1),
    .I(clk_i_buf),
    .O(clk_i)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:34.39-34.79" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf1_ (
    .EN(1'h1),
    .I(dly_incdec_buf),
    .O(dly_incdec)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:35.39-35.71" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf2_ (
    .EN(1'h1),
    .I(dly_ld_buf),
    .O(dly_ld)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:36.39-36.73" *)
  I_BUF #(
    .WEAK_KEEPER("PULLDOWN")
  ) buf3_ (
    .EN(1'h1),
    .I(dly_adj_buf),
    .O(dly_adj)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:47.13-47.43" *)
  CLK_BUF clock_buffer (
    .I(clk_i),
    .O(clk_buf_i)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:56.11-56.46" *)
  I_BUF data_buf (
    .EN(1'h1),
    .I(data_i),
    .O(data_i_buf)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:57.13-63.40" *)
  I_DELAY #(
    .DELAY(32'h00000000)
  ) data_i_delay (
    .CLK_IN(clk_buf_i),
    .DLY_ADJ(dly_adj_buf ),
    .DLY_INCDEC(\$f2g_trx_dly_inc_dly_incdec_inv ),
    .DLY_LOAD(\$f2g_trx_dly_ld_dly_ld_inv ),
    .DLY_TAP_VALUE({ \$ifab_dly_tap_val[5] , \$ifab_dly_tap_val[4] , \$ifab_dly_tap_val[3] , \$ifab_dly_tap_val[2] , \$ifab_dly_tap_val[1] , \$ifab_dly_tap_val[0]  }),
    .I(data_i_buf),
    .O(data_o)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:37.11-37.62" *)
  O_BUF obuf00_ (
    .I(data_o_inv_delayed),
    .O(data_o_inv_delayed_buf)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:38.11-38.62" *)
  O_BUF obuf0_ (
    .I(\dly_tap_val_inv[0] ),
    .O(dly_tap_val_inv_buf[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:39.11-39.62" *)
  O_BUF obuf1_ (
    .I(\dly_tap_val_inv[1] ),
    .O(dly_tap_val_inv_buf[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:40.11-40.62" *)
  O_BUF obuf2_ (
    .I(\dly_tap_val_inv[2] ),
    .O(dly_tap_val_inv_buf[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:41.11-41.62" *)
  O_BUF obuf3_ (
    .I(\dly_tap_val_inv[3] ),
    .O(dly_tap_val_inv_buf[3])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:42.11-42.62" *)
  O_BUF obuf4_ (
    .I(\dly_tap_val_inv[4] ),
    .O(dly_tap_val_inv_buf[4])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/nfs_scratch/scratch/eda/behzad/Validation/RTL_testcases/GJC-IO-Testcases/GJC19/results_dir/.././rtl/GJC19.v:43.11-43.62" *)
  O_BUF obuf5_ (
    .I(\dly_tap_val_inv[5] ),
    .O(dly_tap_val_inv_buf[5])
  );
endmodule
