/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module and2(a, b, c, clk, reset);
  input a;
  input b;
  output c;
  input clk;
  input reset;
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] _0_;
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire _1_;
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire _2_;
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire _3_;
  wire _4_;
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:19.64-19.66" *)
  wire _5_;
  (* src = "./rtl/and2.v:14.12-14.13" *)
  (* src = "./rtl/and2.v:14.12-14.13" *)
  wire a;
  (* src = "./rtl/and2.v:15.12-15.13" *)
  (* src = "./rtl/and2.v:15.12-15.13" *)
  wire b;
  (* keep = 32'h00000001 *)
  (* src = "./rtl/and2.v:18.8-18.9" *)
  (* keep = 32'h00000001 *)
  (* src = "./rtl/and2.v:18.8-18.9" *)
  wire c;
  (* src = "./rtl/and2.v:16.12-16.15" *)
  (* src = "./rtl/and2.v:16.12-16.15" *)
  wire clk;
  (* src = "./rtl/and2.v:17.12-17.17" *)
  (* src = "./rtl/and2.v:17.12-17.17" *)
  wire reset;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) _6_ (
    .Y(_4_),
    .A({ b, a })
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) _7_ (
    .Y(_5_),
    .A(reset)
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/manadher/work/Feb24/yosys_rs27/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:19.11-19.68" *)
  DFFRE _8_ (
    .C(clk),
    .D(_4_),
    .E(1'h1),
    .Q(c),
    .R(_5_)
  );
endmodule
