/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module fabric_and2(\$iopadmap$b , \$iopadmap$c , \$auto$clkbufmap.cc:295:execute$425 , \$iopadmap$a , \$iopadmap$reset );
  output \$iopadmap$c ;
  input \$iopadmap$reset ;
  input \$auto$clkbufmap.cc:295:execute$425 ;
  input \$iopadmap$b ;
  input \$iopadmap$a ;
  wire \$iopadmap$c ;
  wire \$iopadmap$clk ;
  wire \$iopadmap$reset ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:10.12-10.13" *)
  wire \$techmap426$auto$clkbufmap.cc:262:execute$423.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:11.12-11.13" *)
  wire \$techmap426$auto$clkbufmap.cc:262:execute$423.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap427$iopadmap$and2.reset.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap427$iopadmap$and2.reset.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap427$iopadmap$and2.reset.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:38.16-38.17" *)
  wire \$techmap428$iopadmap$and2.c.C ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:37.16-37.17" *)
  wire \$techmap428$iopadmap$and2.c.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:39.16-39.17" *)
  wire \$techmap428$iopadmap$and2.c.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap429$iopadmap$and2.b.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap429$iopadmap$and2.b.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap429$iopadmap$and2.b.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap430$iopadmap$and2.clk.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap430$iopadmap$and2.clk.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap430$iopadmap$and2.clk.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:25.16-25.18" *)
  wire \$techmap431$iopadmap$and2.a.EN ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:24.16-24.17" *)
  wire \$techmap431$iopadmap$and2.a.I ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:26.16-26.17" *)
  wire \$techmap431$iopadmap$and2.a.O ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire \$techmap432$abc$420$auto$blifparse.cc:515:parse_blif$422.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap432$abc$420$auto$blifparse.cc:515:parse_blif$422.Y ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:12.23-12.24" *)
  wire [1:0] \$techmap433$abc$420$auto$blifparse.cc:515:parse_blif$421.A ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:13.13-13.14" *)
  wire \$techmap433$abc$420$auto$blifparse.cc:515:parse_blif$421.Y ;
  wire \$auto$clkbufmap.cc:295:execute$425 ;
  wire \$iopadmap$b ;
  wire \$iopadmap$a ;
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:19.64-19.66" *)
  wire \$abc$420$techmap$techmap336$abc$187$auto$blifparse.cc:362:parse_blif$188.$logic_not$/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:19$278_Y ;
  wire \$abc$187$li0_li0 ;
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:19.11-19.68" *)
  DFFRE \$abc$187$auto$blifparse.cc:362:parse_blif$188  (
    .C(\$auto$clkbufmap.cc:295:execute$425 ),
    .D(\$abc$187$li0_li0 ),
    .E(1'h1),
    .Q(\$iopadmap$c ),
    .R(\$abc$420$techmap$techmap336$abc$187$auto$blifparse.cc:362:parse_blif$188.$logic_not$/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:19$278_Y )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) \$abc$420$auto$blifparse.cc:515:parse_blif$421  (
    .A({ \$iopadmap$b , \$iopadmap$a  }),
    .Y(\$abc$187$li0_li0 )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:17.38-17.69" *)
  LUT1 #(
    .INIT_VALUE(2'h1)
  ) \$abc$420$auto$blifparse.cc:515:parse_blif$422  (
    .A(\$iopadmap$reset ),
    .Y(\$abc$420$techmap$techmap336$abc$187$auto$blifparse.cc:362:parse_blif$188.$logic_not$/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:19$278_Y )
  );
endmodule
