/* Generated by Yosys 0.18+10 (git sha1 9ae216287, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module and2(a, b, c, clk, reset);
  input reset;
  input clk;
  output c;
  input b;
  input a;
  (* src = "./rtl/and2.v:17.12-17.17" *)
  (* src = "./rtl/and2.v:17.12-17.17" *)
  wire reset;
  (* src = "./rtl/and2.v:16.12-16.15" *)
  (* src = "./rtl/and2.v:16.12-16.15" *)
  wire clk;
  (* keep = 32'd1 *)
  (* src = "./rtl/and2.v:18.8-18.9" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/and2.v:18.8-18.9" *)
  wire c;
  (* src = "./rtl/and2.v:15.12-15.13" *)
  (* src = "./rtl/and2.v:15.12-15.13" *)
  wire b;
  (* src = "./rtl/and2.v:14.12-14.13" *)
  (* src = "./rtl/and2.v:14.12-14.13" *)
  wire a;
  fabric_and2 \$auto$rs_design_edit.cc:561:execute$425  (
    .a(a),
    .b(b),
    .c(c),
    .clk(clk),
    .reset(reset)
  );
  interface_and2 \$auto$rs_design_edit.cc:563:execute$426  (
  );
endmodule

module interface_and2();
endmodule
