/* Generated by Yosys 0.18+10 (git sha1 8ecc445e4, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module and2(a, b, c, clk, reset);
  input a;
  input clk;
  output c;
  input reset;
  input b;
  (* keep = 32'd1 *)
  (* src = "./rtl/and2.v:18.8-18.9" *)
  wire \$auto$rs_design_edit.cc:682:execute$435.c ;
  (* src = "./rtl/and2.v:14.12-14.13" *)
  wire \$auto$rs_design_edit.cc:682:execute$435.a ;
  (* src = "./rtl/and2.v:16.12-16.15" *)
  wire \$auto$rs_design_edit.cc:682:execute$435.clk ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$435.$auto$clkbufmap.cc:295:execute$425 ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$a ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$b ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$c ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$clk ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$reset ;
  (* src = "./rtl/and2.v:15.12-15.13" *)
  wire \$auto$rs_design_edit.cc:682:execute$435.b ;
  (* src = "./rtl/and2.v:17.12-17.17" *)
  wire \$auto$rs_design_edit.cc:682:execute$435.reset ;
  (* src = "./rtl/and2.v:14.12-14.13" *)
  (* src = "./rtl/and2.v:14.12-14.13" *)
  wire a;
  wire \$iopadmap$reset ;
  (* src = "./rtl/and2.v:16.12-16.15" *)
  (* src = "./rtl/and2.v:16.12-16.15" *)
  wire clk;
  wire \$iopadmap$c ;
  wire \$iopadmap$b ;
  wire \$iopadmap$a ;
  wire \$auto$clkbufmap.cc:295:execute$425 ;
  (* keep = 32'd1 *)
  (* src = "./rtl/and2.v:18.8-18.9" *)
  (* keep = 32'd1 *)
  (* src = "./rtl/and2.v:18.8-18.9" *)
  wire c;
  (* src = "./rtl/and2.v:17.12-17.17" *)
  (* src = "./rtl/and2.v:17.12-17.17" *)
  wire reset;
  (* src = "./rtl/and2.v:15.12-15.13" *)
  (* src = "./rtl/and2.v:15.12-15.13" *)
  wire b;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$and2.clk  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$435.clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$clk )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$and2.reset  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$435.reset ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$reset )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$435.$auto$clkbufmap.cc:262:execute$423  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$435.$auto$clkbufmap.cc:295:execute$425 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$and2.a  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$435.a ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$a )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$and2.b  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$435.b ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$b )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/cschai/github/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$and2.c  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$c ),
    .O(\$auto$rs_design_edit.cc:682:execute$435.c )
  );
  fabric_and2 \$auto$rs_design_edit.cc:680:execute$434  (
    .\$auto$clkbufmap.cc:295:execute$425 (\$auto$clkbufmap.cc:295:execute$425 ),
    .\$iopadmap$a (\$iopadmap$a ),
    .\$iopadmap$b (\$iopadmap$b ),
    .\$iopadmap$c (\$iopadmap$c ),
    .\$iopadmap$reset (\$iopadmap$reset )
  );
  assign \$auto$clkbufmap.cc:295:execute$425  = \$flatten$auto$rs_design_edit.cc:682:execute$435.$auto$clkbufmap.cc:295:execute$425 ;
  assign \$iopadmap$a  = \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$a ;
  assign \$iopadmap$b  = \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$b ;
  assign \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$c  = \$iopadmap$c ;
  assign \$iopadmap$reset  = \$flatten$auto$rs_design_edit.cc:682:execute$435.$iopadmap$reset ;
  assign \$auto$rs_design_edit.cc:682:execute$435.a  = a;
  assign \$auto$rs_design_edit.cc:682:execute$435.b  = b;
  assign c = \$auto$rs_design_edit.cc:682:execute$435.c ;
  assign \$auto$rs_design_edit.cc:682:execute$435.clk  = clk;
  assign \$auto$rs_design_edit.cc:682:execute$435.reset  = reset;
endmodule
